//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Batched.Reporting.Contracts.Errormap
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Batched.Reporting.Contracts.Errorspace.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This action is restricted. Unscheduled tickets that have been on a master roll can not be separated..
        /// </summary>
        public static string BreakingMasterrollEntry
        {
            get
            {
                return ResourceManager.GetString("BreakingMasterrollEntry", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This action is restricted. Tickets that have been printed on a master roll can not be separated..
        /// </summary>
        public static string BreakingPrintedMasterroll
        {
            get
            {
                return ResourceManager.GetString("BreakingPrintedMasterroll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Already present a lead time exception with the same name..
        /// </summary>
        public static string DuplicateLeadTimeExceptionName
        {
            get
            {
                return ResourceManager.GetString("DuplicateLeadTimeExceptionName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Multiple tickets on the same equipment cannot be scheduled with the same start time. Please select a unique equipment and start time combination..
        /// </summary>
        public static string DuplicateStartsAt
        {
            get
            {
                return ResourceManager.GetString("DuplicateStartsAt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Requested Equipment does not have feasible routes..
        /// </summary>
        public static string EquipmentHasNoFeasibleRoutes
        {
            get
            {
                return ResourceManager.GetString("EquipmentHasNoFeasibleRoutes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Facility not found for facility Id - {0}.
        /// </summary>
        public static string FacilityNotFound
        {
            get
            {
                return ResourceManager.GetString("FacilityNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to create the forced group. Some of the tickets are completed..
        /// </summary>
        public static string ForcedGroupCompletedTicket
        {
            get
            {
                return ResourceManager.GetString("ForcedGroupCompletedTicket", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to create the forced group. A forced group with the same name already exists..
        /// </summary>
        public static string ForcedGroupDuplicateName
        {
            get
            {
                return ResourceManager.GetString("ForcedGroupDuplicateName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to create the forced group. Some of the tickets are in &apos;Locked&apos; state. Please release the locks to create a group including these tickets..
        /// </summary>
        public static string ForcedGroupLockedTicket
        {
            get
            {
                return ResourceManager.GetString("ForcedGroupLockedTicket", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to create the forced group. Some of the tickets are part of &apos;Master Roll&apos;..
        /// </summary>
        public static string ForcedGroupMasterRollTicket
        {
            get
            {
                return ResourceManager.GetString("ForcedGroupMasterRollTicket", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to create forced group. The requested tickets do not have tasks belonging to same facility..
        /// </summary>
        public static string ForcedGroupNoCommonFacility
        {
            get
            {
                return ResourceManager.GetString("ForcedGroupNoCommonFacility", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to create the forced group. The requested tickets do not have any common route for task .
        /// </summary>
        public static string ForcedGroupNoCommonTask
        {
            get
            {
                return ResourceManager.GetString("ForcedGroupNoCommonTask", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to create the forced group. Some of the tickets are OnPress..
        /// </summary>
        public static string ForcedGroupOnPressTicket
        {
            get
            {
                return ResourceManager.GetString("ForcedGroupOnPressTicket", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while processing request..
        /// </summary>
        public static string InternalServerException
        {
            get
            {
                return ResourceManager.GetString("InternalServerException", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to EndDate can not be less than StartDate.
        /// </summary>
        public static string InvalidDate
        {
            get
            {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Date format of {0} is invalid.
        /// </summary>
        public static string InvalidDateFormat
        {
            get
            {
                return ResourceManager.GetString("InvalidDateFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Date {0} must be smaller than {1}.
        /// </summary>
        public static string InvalidDateRange
        {
            get
            {
                return ResourceManager.GetString("InvalidDateRange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Lead time exception not found for provided Exception Id.
        /// </summary>
        public static string InvalidLeadTimeExceptionId
        {
            get
            {
                return ResourceManager.GetString("InvalidLeadTimeExceptionId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid forced group {0} in request.
        /// </summary>
        public static string InvalidForcedGroup
        {
            get
            {
                return ResourceManager.GetString("InvalidForcedGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Requested ticket should be part of Forced Group : .
        /// </summary>
        public static string InvalidForcedGroupTicket
        {
            get
            {
                return ResourceManager.GetString("InvalidForcedGroupTicket", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The location where we are trying to move these tickets do not satisfy forced group requirements.
        /// </summary>
        public static string InvalidMoveToScheduleId
        {
            get
            {
                return ResourceManager.GetString("InvalidMoveToScheduleId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid Request in API call..
        /// </summary>
        public static string InvalidRequest
        {
            get
            {
                return ResourceManager.GetString("InvalidRequest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to StockMaterialId can not be null or empty.
        /// </summary>
        public static string InvalidStockMaterialId
        {
            get
            {
                return ResourceManager.GetString("InvalidStockMaterialId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Equipment(s) unavailable for scheduling..
        /// </summary>
        public static string InvalidTimeLock
        {
            get
            {
                return ResourceManager.GetString("InvalidTimeLock", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This action is restricted. Tickets that have been printed on a master roll can not be reordered..
        /// </summary>
        public static string MoveWithinMasterRollError
        {
            get
            {
                return ResourceManager.GetString("MoveWithinMasterRollError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Parameter {0} can not be null or empty..
        /// </summary>
        public static string ParameterCannotBeNull
        {
            get
            {
                return ResourceManager.GetString("ParameterCannotBeNull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Requested Dates have Holidays..
        /// </summary>
        public static string ScheduleDateCollapsedWithHolidays
        {
            get
            {
                return ResourceManager.GetString("ScheduleDateCollapsedWithHolidays", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Requested Dates have downtimes for given Equipment..
        /// </summary>
        public static string ScheduleDateHasDowntimes
        {
            get
            {
                return ResourceManager.GetString("ScheduleDateHasDowntimes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New schedule available. Please refresh and try again..
        /// </summary>
        public static string ScheduleNotFound
        {
            get
            {
                return ResourceManager.GetString("ScheduleNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Status not found/expired for the key {0}.
        /// </summary>
        public static string StatusNotFound
        {
            get
            {
                return ResourceManager.GetString("StatusNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Provided time range is overlapping with existing tasks..
        /// </summary>
        public static string TaskTimeOverlappingWithAnotherTask
        {
            get
            {
                return ResourceManager.GetString("TaskTimeOverlappingWithAnotherTask", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This action is restricted. Tickets that have been printed on a master roll can not be separated..
        /// </summary>
        public static string TicketMovedBetweenMasteroll
        {
            get
            {
                return ResourceManager.GetString("TicketMovedBetweenMasteroll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Schedule update failed.
        /// </summary>
        public static string TicketMovementUpdateFail
        {
            get
            {
                return ResourceManager.GetString("TicketMovementUpdateFail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Constraints indicate this ticket(s) can not be processed on this equipment. We may not be able to calculate changeover setup time for this ticket..
        /// </summary>
        public static string TicketOnEquipmentIsNotFeasible
        {
            get
            {
                return ResourceManager.GetString("TicketOnEquipmentIsNotFeasible", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This action is restricted. This movement would cause a conflict with the selected or affected ticket(s) subsequent or preceding tasks..
        /// </summary>
        public static string TicketTaskSequenceIncorrect
        {
            get
            {
                return ResourceManager.GetString("TicketTaskSequenceIncorrect", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unavailable equipment - {0}.
        /// </summary>
        public static string UnavailableEquipment
        {
            get
            {
                return ResourceManager.GetString("UnavailableEquipment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ValueStream not found for valuestream Id - {0}.
        /// </summary>
        public static string ValueStreamNotFount
        {
            get
            {
                return ResourceManager.GetString("ValueStreamNotFount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reservation with name {0} already exists.
        /// </summary>
        public static string DuplicateReservationName
        {
            get
            {
                return ResourceManager.GetString("DuplicateReservationName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ther reservation {0} contains the selected Workcenter, Equipment and Customer combination.
        /// </summary>
        public static string ReservationCombinationExists
        {
            get
            {
                return ResourceManager.GetString("ReservationCombinationExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The reservation id passed is not valid.
        /// </summary>
        public static string InvalidReservationId
        {
            get
            {
                return ResourceManager.GetString("InvalidReservationId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reservation should have at least one workcenter associated..
        /// </summary>
        public static string WorkcenterReservationNotFound
        {
            get
            {
                return ResourceManager.GetString("WorkcenterReservationNotFound", resourceCulture);
            }
        }
    }
}
