//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Batched.Reporting.Contracts.Errormap
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorCodes
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorCodes()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Batched.Reporting.Contracts.Errorspace.ErrorCodes", typeof(ErrorCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to 1007.
        /// </summary>
        public static string DuplicateLeadTimeExceptionName
        {
            get
            {
                return ResourceManager.GetString("DuplicateLeadTimeExceptionName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1030.
        /// </summary>
        public static string FacilityNotFound
        {
            get
            {
                return ResourceManager.GetString("FacilityNotFound", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to 999.
        /// </summary>
        public static string InternalServerException
        {
            get
            {
                return ResourceManager.GetString("InternalServerException", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1016.
        /// </summary>
        public static string InvalidDate
        {
            get
            {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1004.
        /// </summary>
        public static string InvalidDateFormat
        {
            get
            {
                return ResourceManager.GetString("InvalidDateFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1005.
        /// </summary>
        public static string InvalidDateRange
        {
            get
            {
                return ResourceManager.GetString("InvalidDateRange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1006.
        /// </summary>
        public static string InvalidLeadTimeExceptionId
        {
            get
            {
                return ResourceManager.GetString("InvalidLeadTimeExceptionId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1001.
        /// </summary>
        public static string InvalidRequest
        {
            get
            {
                return ResourceManager.GetString("InvalidRequest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1002.
        /// </summary>
        public static string InvalidRuleSyntax
        {
            get
            {
                return ResourceManager.GetString("InvalidRuleSyntax", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1015.
        /// </summary>
        public static string InvalidStockMaterialId
        {
            get
            {
                return ResourceManager.GetString("InvalidStockMaterialId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1000.
        /// </summary>
        public static string ParameterCannotBeNull
        {
            get
            {
                return ResourceManager.GetString("ParameterCannotBeNull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1009.
        /// </summary>
        public static string ScheduleNotFound
        {
            get
            {
                return ResourceManager.GetString("ScheduleNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1003.
        /// </summary>
        public static string StatusNotFound
        {
            get
            {
                return ResourceManager.GetString("StatusNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1029.
        /// </summary>
        public static string UnavailableEquipment
        {
            get
            {
                return ResourceManager.GetString("UnavailableEquipment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1031.
        /// </summary>
        public static string DuplicateReservationName
        {
            get
            {
                return ResourceManager.GetString("DuplicateReservationName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1032.
        /// </summary>
        public static string ReservationCombinationExists
        {
            get
            {
                return ResourceManager.GetString("ReservationCombinationExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1033.
        /// </summary>
        public static string InvalidReservationId
        {
            get
            {
                return ResourceManager.GetString("InvalidReservationId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1034.
        /// </summary>
        public static string WorkcenterReservationNotFound
        {
            get
            {
                return ResourceManager.GetString("WorkcenterReservationNotFound", resourceCulture);
            }
        }
    }
}
