CREATE TABLE [dbo].[AllOpenTicketTasks_Table] (
    [TaskDueTime]                  DATETIME         NULL,
    [TaskDone]                     INT              NULL,
    [firstWorkCenterScan]          DATETIME         NULL,
    [TaskStarted]                  INT              NOT NULL,
    [TaskEstimatedHours]           FLOAT (53)       NULL,
    [TotalTaskEstimatedHours]      FLOAT (53)       NULL,
    [TaskEstimatedMeters]          FLOAT (53)       NULL,
    [Pass]                         INT              NULL,
    [DoublePassJob]                INT              NULL,
    [Labels_Act_Net_Timecard]      FLOAT (53)       NULL,
    [TicketPressNumber]            NVARCHAR (255)   NULL,
    [Task]                         VARCHAR (8)      NOT NULL,
    [TaskWorkCenter]               VARCHAR (255)    NULL,
    [Sequence]                     INT              NOT NULL,
    [pressWorkCenter]              VARCHAR (255)    NULL,
    [equipWorkCenter]              VARCHAR (255)    NULL,
    [equip3WorkCenter]             VARCHAR (255)    NULL,
    [equip4WorkCenter]             VARCHAR (255)    NULL,
    [rewinderWorkCenter]           VARCHAR (255)    NULL,
    [Number]                       NVARCHAR (255)   NOT NULL,
    [ID]                           INT              NULL,
    [CustomerNum]                  NVARCHAR (255)   NULL,
    [CustomerName]                 NVARCHAR (255)   NULL,
    [ShipVia]                      NVARCHAR (255)   NULL,
    [OrderDate]                    DATE             NULL,
    [ArtStat]                      NVARCHAR (255)   NULL,
    [ProofStat]                    NVARCHAR (255)   NULL,
    [PlateStat]                    NVARCHAR (255)   NULL,
    [ToolStat]                     NVARCHAR (255)   NULL,
    [PressStat]                    NVARCHAR (255)   NULL,
    [ArtDone]                      BIT              NULL,
    [ProofDone]                    BIT              NULL,
    [PlateDone]                    BIT              NULL,
    [ToolsIn]                      BIT              NULL,
    [StockIn]                      NVARCHAR (255)   NULL,
    [EstPackHrs]                   FLOAT (53)       NULL,
    [ActQuantity]                  INT              NULL,
    [Is_Ink_In]                    BIT              NULL,
    [Ink_Status]                   NVARCHAR (255)   NULL,
    [ActualBillings_NetOfSalesTax] FLOAT (53)       NULL,
    [ActualRewindingHours]         FLOAT (53)       NULL,
    [ActualTotalHours]             FLOAT (53)       NULL,
    [ActualTotalLaborCosts]        FLOAT (53)       NULL,
    [ActStockCost]                 FLOAT (53)       NULL,
    [ActualTotalPOCosts]           FLOAT (53)       NULL,
    [ActualTotalMatAndFreightCost] FLOAT (53)       NULL,
    [ActTotalCost]                 FLOAT (53)       NULL,
    [EstStockCost]                 FLOAT (53)       NULL,
    [DateShipped]                  DATE             NULL,
    [OTSName]                      NVARCHAR (255)   NULL,
    [ITSName]                      NVARCHAR (255)   NULL,
    [EntryDate]                    DATE             NULL,
    [GeneralDescr]                 NVARCHAR (255)   NULL,
    [Notes]                        NVARCHAR (1024)  NULL,
    [FinishStat]                   NVARCHAR (255)   NULL,
    [MiscCharge]                   FLOAT (53)       NULL,
    [NoAcross]                     INT              NULL,
    [POTotal]                      FLOAT (53)       NULL,
    [NoLabAcrossFin]               INT              NULL,
    [Press]                        NVARCHAR (255)   NULL,
    [RowSpace]                     FLOAT (53)       NULL,
    [Ship_by_Date]                 DATE             NULL,
    [LabelsPer_]                   INT              NULL,
    [CoreSize]                     FLOAT (53)       NULL,
    [SizeAround]                   FLOAT (53)       NULL,
    [StockNum1]                    NVARCHAR (255)   NULL,
    [StockNum2]                    NVARCHAR (255)   NULL,
    [Stockwidth2]                  FLOAT (53)       NULL,
    [Priority]                     NVARCHAR (255)   NULL,
    [StockNum3]                    NVARCHAR (255)   NULL,
    [TicketType]                   INT              NULL,
    [TicQuantity]                  INT              NULL,
    [StockDesc2]                   NVARCHAR (255)   NULL,
    [StockDesc3]                   NVARCHAR (255)   NULL,
    [TicketStatus]                 NVARCHAR (255)   NULL,
    [ActFootage]                   INT              NULL,
    [EstMRHrs]                     FLOAT (53)       NULL,
    [EstWuHrs]                     FLOAT (53)       NULL,
    [EstRunHrs]                    FLOAT (53)       NULL,
    [EstPressTime]                 FLOAT (53)       NULL,
    [EstFinHrs]                    FLOAT (53)       NULL,
    [EstPostPressHours]            FLOAT (53)       NULL,
    [EstTotal]                     FLOAT (53)       NULL,
    [RewindEquipNum]               NVARCHAR (255)   NULL,
    [CSA]                          BIT              NULL,
    [UL]                           BIT              NULL,
    [ConsecNo]                     BIT              NULL,
    [MainTool]                     NVARCHAR (255)   NULL,
    [Shape]                        NVARCHAR (255)   NULL,
    [NoArounPlate]                 INT              NULL,
    [ColSpace]                     FLOAT (53)       NULL,
    [EstFootage]                   INT              NULL,
    [Est_SetupFootage]             INT              NULL,
    [Est_SpoilFootage]             INT              NULL,
    [OverRun]                      FLOAT (53)       NULL,
    [LabelRepeat]                  FLOAT (53)       NULL,
    [OutsideDiameter]              FLOAT (53)       NULL,
    [Equip_ID]                     NVARCHAR (255)   NULL,
    [Equip_MakeReadyHours]         FLOAT (53)       NULL,
    [Equip_WashUpHours]            FLOAT (53)       NULL,
    [Equip_EstRunHrs]              FLOAT (53)       NULL,
    [Equip_EstTime]                FLOAT (53)       NULL,
    [Equip3_ID]                    NVARCHAR (255)   NULL,
    [Equip3_MakeReadyHours]        FLOAT (53)       NULL,
    [Equip3_WashUpHours]           FLOAT (53)       NULL,
    [Equip3_EstRunHrs]             FLOAT (53)       NULL,
    [Equip3_EstTime]               FLOAT (53)       NULL,
    [Equip4_ID]                    NVARCHAR (255)   NULL,
    [Equip4_MakeReadyHours]        FLOAT (53)       NULL,
    [Equip4_WashUpHours]           FLOAT (53)       NULL,
    [Equip4_EstRunHrs]             FLOAT (53)       NULL,
    [Equip4_EstTime]               FLOAT (53)       NULL,
    [FinishType]                   NVARCHAR (255)   NULL,
    [Tool2Descr]                   NVARCHAR (255)   NULL,
    [Tool3Descr]                   NVARCHAR (255)   NULL,
    [Tool4Descr]                   NVARCHAR (255)   NULL,
    [Tool5Descr]                   NVARCHAR (255)   NULL,
    [Tab]                          FLOAT (53)       NULL,
    [Backstage_ColorStrategy]      NVARCHAR (255)   NULL,
    [StockDesc1]                   NVARCHAR (255)   NULL,
    [Roto_Quote_Number]            NVARCHAR (255)   NULL,
    [ShrinkSleeve_LayFlat]         FLOAT (53)       NULL,
    [ShrinkSleeve_CutHeight]       FLOAT (53)       NULL,
    [ShrinkSleeve_OverLap]         FLOAT (53)       NULL,
    [PressDone]                    BIT              NULL,
    [Equip_Status]                 NVARCHAR (255)   NULL,
    [Equip_Done]                   BIT              NULL,
    [Due_on_Site_Date]             DATE             NULL,
    [Equip3_Status]                NVARCHAR (255)   NULL,
    [Equip3_Done]                  BIT              NULL,
    [Equip4_Status]                NVARCHAR (255)   NULL,
    [Equip4_Done]                  BIT              NULL,
    [FinishDone]                   BIT              NULL,
    [Backstage_SmartMarkSet]       NVARCHAR (255)   NULL,
    [SizeAcross]                   FLOAT (53)       NULL,
    [FinalUnwind]                  NVARCHAR (255)   NULL,
    [Use_TurretRewinder]           BIT              NULL,
    [StockTicketType]              INT              NULL,
    [PriceMode]                    NVARCHAR (255)   NULL,
    [CustPONum]                    NVARCHAR (255)   NULL,
    [ShipAttn]                     NVARCHAR (255)   NULL,
    [ShipLocation]                 NVARCHAR (255)   NULL,
    [ShipAddr1]                    NVARCHAR (255)   NULL,
    [ShipAddr2]                    NVARCHAR (255)   NULL,
    [ShipCity]                     NVARCHAR (255)   NULL,
    [ShipSt]                       NVARCHAR (255)   NULL,
    [ShipZip]                      NVARCHAR (255)   NULL,
    [ShipCountry]                  NVARCHAR (255)   NULL,
    [Ship_Address_ID]              NVARCHAR (255)   NULL,
    [ShippingInstruc]              NVARCHAR (255)   NULL,
    [ShippingStatus]               NVARCHAR (255)   NULL,
    [ToolNo2]                      NVARCHAR (255)   NULL,
    [ToolNo3]                      NVARCHAR (255)   NULL,
    [ToolNo4]                      NVARCHAR (255)   NULL,
    [ToolNo5]                      NVARCHAR (255)   NULL,
    [Turnbar]                      BIT              NULL,
    [EntryTime]                    INT              NULL,
    [ModifyDate]                   DATE             NULL,
    [ModifyTime]                   INT              NULL,
    [numberOfFinishedRolls]        DECIMAL (10, 5)  NULL,
    [numberOfLeftoverRolls]        DECIMAL (38, 5)  NULL,
    [NoColors]                     INT              NULL,
    [NoItems]                      INT              NULL,
    [NumberofPlateChanges]         INT              NULL,
    [Stock2_LinerCaliper]          INT              NULL,
    [Varnish]                      VARCHAR (103)    NOT NULL,
    [SpotVarnish]                  INT              NOT NULL,
    [PeelandReveal]                INT              NOT NULL,
    [PantoneGreen]                 INT              NOT NULL,
    [PantoneOrange]                INT              NOT NULL,
    [PantoneSilver]                INT              NOT NULL,
    [FourHitsWhite]                INT              NOT NULL,
    [SpecialSilverGold]            INT              NOT NULL,
    [SandpaperVarnish]             INT              NOT NULL,
    [Stock2PressGrouping]          VARCHAR (255)    NULL,
    [LinearLength_Calc]            FLOAT (53)       NULL,
    [ShipTime]                     DATETIME         NULL,
    [MainToolGearTeeth]            INT              NULL,
    [MainToolSize]                 FLOAT (53)       NULL,
    [MainToolNotes]                NVARCHAR (1024)  NULL,
    [minToolSize]                  FLOAT (53)       NULL,
    [maxToolSize]                  FLOAT (53)       NULL,
    [numberofTools]                INT              NULL,
    [Silkscreen]                   INT              NULL,
    [HotFoil]                      INT              NOT NULL,
    [Embossing]                    INT              NULL,
    [LockTooling]                  INT              NULL,
    [EvoTooling]                   INT              NOT NULL,
    [MultiLayer]                   INT              NOT NULL,
    [ColdFoil]                     INT              NOT NULL,
    [Inlinesheeter]                INT              NOT NULL,
    [PharmaStock]                  INT              NOT NULL,
    [PETLiner]                     INT              NOT NULL,
    [FruitTagStock]                INT              NOT NULL,
    [BacksidePrinting]             INT              NOT NULL,
    [Remaining Quantity]           INT              NULL,
    [NumberofRemainingCores]       DECIMAL (15, 2)  NULL,
    [CoreWidth]                    FLOAT (53)       NULL,
    [SubstrateLocation]            NVARCHAR (4000)  NULL,
    [numberOfStops]                DECIMAL (32, 16) NULL,
    [DoublePass_ReinsertionFlag]   INT              NOT NULL,
    [FinishedRollLength]           FLOAT (53)       NULL,
    [OfflineRewindTask]            INT              NOT NULL,
    [DueDateBucket]                VARCHAR (11)     NOT NULL,
    [FinishDueTime]                DATETIME         NULL,
    [Equip4DueTime]                DATETIME         NULL,
    [Equip3DueTime]                DATETIME         NULL,
    [EquipDueTime]                 DATETIME         NULL,
    [PressDueTime]                 DATETIME         NULL,
    [daysLate]                     INT              NULL,
    [customerRank]                 VARCHAR (1)      NOT NULL,
    [revenuePercentile]            NUMERIC (33, 12) NULL,
    [customerRankingPoints]        INT              NOT NULL,
    [dueDatePoints]                NUMERIC (12, 2)  NULL,
    [orderSizePoints]              NUMERIC (34, 12) NULL,
    [priorityPoints]               INT              NOT NULL,
    [ticketPoints]                 NUMERIC (38, 6)  NULL,
    [ScheduledPress]               VARCHAR (255)    NULL,
    [StartTime]                    DATETIME         NULL,
    [EndTime]                      DATETIME         NULL,
    [Locked]                       FLOAT (53)       NULL,
    [DaysSinceOrdered]             INT              NULL,
    [StockInText]                  NVARCHAR (255)   NULL,
    [Stock1InText]                 VARCHAR (255)    NOT NULL,
    [Stock3InText]                 VARCHAR (255)    NOT NULL,
    [StockInStatus]                INT              NOT NULL,
    [TicketScheduleStatus]         VARCHAR (11)     NOT NULL,
    [TicketStatusValue]            INT              NOT NULL,
    [HoldStatusValue]              INT              NOT NULL,
    [ArtStatText]                  VARCHAR (3)      NOT NULL,
    [ProofStatText]                VARCHAR (3)      NOT NULL,
    [PlateStatText]                VARCHAR (3)      NOT NULL,
    [ToolStatText]                 VARCHAR (255)    NOT NULL,
    [InkStatText]                  VARCHAR (3)      NOT NULL,
    [TaskStatusValue]              INT              NOT NULL,
    [TaskStatusText]               VARCHAR (11)     NOT NULL,
    [TaskMinutes]                  FLOAT (53)       NULL,
    [changeoverMinutes]            FLOAT (53)       NULL,
    [ScheduledRewinder]            VARCHAR (255)    NULL,
    [LastScheduledMachine]         INT              NOT NULL,
    [ScheduledDigicon]             VARCHAR (255)    NULL,
    [ScheduledDate]                DATE             NULL,
    [ScheduledEndDate]             DATE             NULL,
    [Updated Due Date]             DATE             NULL,
    [Planning Press]               NVARCHAR (255)   NULL,
    [Digicon Job Type]             VARCHAR (13)     NOT NULL,
    [Unfinished Prior Steps Flag]  INT              NOT NULL,
    [PriorScheduledPress]          VARCHAR (255)    NULL,
    [runDate]                      DATETIME         NULL,
    [PriorityFlag]                 INT              NOT NULL,
    [masterRollNumber]             VARCHAR (255)    NULL,
    [MasterRollFlag]               INT              NOT NULL,
    [MasterRollRank]               BIGINT           NULL,
    [EvenOdd]                      INT              NULL,
    [FeasibilityCheck]             VARCHAR (16)     NOT NULL,
    [FeasibilityCheckValue]        INT              NOT NULL,
    [Last Refresh Time]            DATETIME         NOT NULL
);

