CREATE TABLE [dbo].[OpenTickets_Table] (
    [Number]                    NVARCHAR (255) NOT NULL,
    [CustomerName]              NVARCHAR (255) NULL,
    [CustomerNum]               NVARCHAR (255) NULL,
    [ArtDone]                   BIT            NULL,
    [ProofDone]                 BIT            NULL,
    [PlateDone]                 BIT            NULL,
    [ToolsIn]                   BIT            NULL,
    [StockIn]                   NVARCHAR (255) NULL,
    [Is_Ink_In]                 BIT            NULL,
    [DateShipped]               DATE           NULL,
    [OTSName]                   NVARCHAR (255) NULL,
    [ITSName]                   NVARCHAR (255) NULL,
    [GeneralDescr]              NVARCHAR (255) NULL,
    [Press]                     NVARCHAR (255) NULL,
    [StockNum2]                 NVARCHAR (255) NULL,
    [Stockwidth2]               FLOAT (53)     NULL,
    [Priority]                  NVARCHAR (255) NULL,
    [TicketType]                INT            NULL,
    [TicQuantity]               INT            NULL,
    [TicketStatus]              NVARCHAR (255) NULL,
    [RewindEquipNum]            NVARCHAR (255) NULL,
    [MainTool]                  NVARCHAR (255) NULL,
    [Equip_ID]                  NVARCHAR (255) NULL,
    [Equip3_ID]                 NVARCHAR (255) NULL,
    [Equip4_ID]                 NVARCHAR (255) NULL,
    [FinishType]                NVARCHAR (255) NULL,
    [PressDone]                 BIT            NULL,
    [Equip_Status]              NVARCHAR (255) NULL,
    [Equip_Done]                BIT            NULL,
    [Due_on_Site_Date]          DATE           NULL,
    [Equip3_Status]             NVARCHAR (255) NULL,
    [Equip3_Done]               BIT            NULL,
    [Equip4_Status]             NVARCHAR (255) NULL,
    [Equip4_Done]               BIT            NULL,
    [FinishDone]                BIT            NULL,
    [Use_TurretRewinder]        BIT            NULL,
    [CustPONum]                 NVARCHAR (255) NULL,
    [Ship_by_Date]              DATE           NULL,
    [ShipVia]                   NVARCHAR (255) NULL,
    [ShipAttn]                  NVARCHAR (255) NULL,
    [ShipLocation]              NVARCHAR (255) NULL,
    [ShipAddr1]                 NVARCHAR (255) NULL,
    [ShipAddr2]                 NVARCHAR (255) NULL,
    [ShipCity]                  NVARCHAR (255) NULL,
    [ShipSt]                    NVARCHAR (255) NULL,
    [ShipZip]                   NVARCHAR (255) NULL,
    [ShipCountry]               NVARCHAR (255) NULL,
    [Ship_Address_ID]           NVARCHAR (255) NULL,
    [ShippingInstruc]           NVARCHAR (255) NULL,
    [ShippingStatus]            NVARCHAR (255) NULL,
    [InlineSheeter]             INT            NULL,
    [ShipTime]                  DATETIME       NULL,
    [LatestTaskTime]            DATETIME       NULL,
    [MissedStageGates]          INT            NULL,
    [Updated Due Date]          DATE           NULL,
    [PressStatus]               VARCHAR (11)   NULL,
    [EquipStatus]               VARCHAR (11)   NULL,
    [Equip3Status]              VARCHAR (11)   NULL,
    [Equip4Status]              VARCHAR (11)   NULL,
    [RewindStatus]              VARCHAR (11)   NULL,
    [RemainingTasks]            INT            NOT NULL,
    [TicketStatusText]          VARCHAR (8)    NOT NULL,
    [PressStatusValue]          INT            NOT NULL,
    [EquipStatusValue]          INT            NOT NULL,
    [Equip3StatusValue]         INT            NOT NULL,
    [Equip4StatusValue]         INT            NOT NULL,
    [RewindStatusValue]         INT            NOT NULL,
    [Estimated Completion Date] DATE           NULL,
    [Estimated Completion Time] DATETIME       NULL,
    [SameDayTickets]            INT            NOT NULL,
    [Last Refresh Time]         DATETIME       NOT NULL
);

