CREATE TABLE [dbo].[openFeasibleTicketRoutes] (
    [CustomerNum]                NVARCHAR (255)  NULL,
    [routeFeasible]              INT             NOT NULL,
    [TaskDueTime]                DATETIME        NULL,
    [TaskDone]                   INT             NULL,
    [TaskStarted]                INT             NOT NULL,
    [Task]                       VARCHAR (8)     NOT NULL,
    [Number]                     NVARCHAR (255)  NOT NULL,
    [Equip3_ID]                  NVARCHAR (255)  NULL,
    [PressDone]                  BIT             NULL,
    [Equip_Done]                 BIT             NULL,
    [Equip3_Done]                BIT             NULL,
    [DoublePass_ReinsertionFlag] INT             NOT NULL,
    [TaskEstimatedHours]         FLOAT (53)      NULL,
    [Press]                      NVARCHAR (255)  NULL,
    [Pass]                       INT             NULL,
    [Priority]                   NVARCHAR (255)  NULL,
    [TaskWorkCenter]             VARCHAR (255)   NULL,
    [StockNum2]                  NVARCHAR (255)  NULL,
    [StockNum1]                  NVARCHAR (255)  NULL,
    [Stock2PressGrouping]        VARCHAR (255)   NULL,
    [Stockwidth2]                FLOAT (53)      NULL,
    [Varnish]                    VARCHAR (103)   NOT NULL,
    [MainTool]                   NVARCHAR (255)  NULL,
    [HotFoil]                    INT             NOT NULL,
    [Embossing]                  INT             NULL,
    [CoreSize]                   FLOAT (53)      NULL,
    [Use_TurretRewinder]         BIT             NULL,
    [InlineSheeter]              INT             NOT NULL,
    [Turnbar]                    BIT             NULL,
    [NoAcross]                   INT             NULL,
    [lastScan]                   DATETIME        NULL,
    [ShipTime]                   DATETIME        NULL,
    [ticketPoints]               NUMERIC (38, 6) NULL,
    [LinearLength_Calc]          FLOAT (53)      NULL,
    [DoublePassJob]              INT             NULL,
    [DueDateBucket]              VARCHAR (11)    NOT NULL,
    [SandpaperVarnish]           INT             NOT NULL,
    [ColdFoil]                   INT             NOT NULL,
    [PeelandReveal]              INT             NOT NULL,
    [masterRollNumber]           VARCHAR (255)   NULL,
    [taskDueTimeReference]       BIGINT          NULL,
    [taskEstimatedMinutes]       FLOAT (53)      NULL,
    [taskIndex]                  BIGINT          NULL,
    [PressNumber]                VARCHAR (20)    NULL,
    [HighPriority]               INT             NOT NULL
);

