CREATE TABLE [dbo].[OpenTicketRoutesRaw] (
    [routeFeasible]              INT              NOT NULL,
    [CustomerNum]                NVARCHAR (255)   NULL,
    [PressNumber]                VARCHAR (20)     NULL,
    [PressDescription]           VARCHAR (255)    NULL,
    [AvailableForScheduling]     VARCHAR (255)    NULL,
    [lastScan]                   DATETIME         NULL,
    [totalElapsed]               NUMERIC (38, 6)  NULL,
    [TaskDueTime]                DATETIME         NULL,
    [TaskDone]                   INT              NULL,
    [firstWorkCenterScan]        DATETIME         NULL,
    [TaskStarted]                INT              NOT NULL,
    [TaskEstimatedHours]         FLOAT (53)       NULL,
    [TaskEstimatedMeters]        FLOAT (53)       NULL,
    [Pass]                       INT              NULL,
    [DoublePassJob]              INT              NULL,
    [Labels_Act_Net_Timecard]    FLOAT (53)       NULL,
    [TicketPressNumber]          NVARCHAR (255)   NULL,
    [Task]                       VARCHAR (8)      NOT NULL,
    [TaskWorkCenter]             VARCHAR (255)    NULL,
    [Sequence]                   INT              NOT NULL,
    [pressWorkCenter]            VARCHAR (255)    NULL,
    [equipWorkCenter]            VARCHAR (255)    NULL,
    [equip3WorkCenter]           VARCHAR (255)    NULL,
    [equip4WorkCenter]           VARCHAR (255)    NULL,
    [rewinderWorkCenter]         VARCHAR (255)    NULL,
    [press]                      NVARCHAR (255)   NULL,
    [equip_id]                   NVARCHAR (255)   NULL,
    [equip3_id]                  NVARCHAR (255)   NULL,
    [equip4_id]                  NVARCHAR (255)   NULL,
    [rewindequipnum]             NVARCHAR (255)   NULL,
    [PressDone]                  BIT              NULL,
    [Equip_Done]                 BIT              NULL,
    [Equip3_Done]                BIT              NULL,
    [Equip4_Done]                BIT              NULL,
    [FinishDone]                 BIT              NULL,
    [Number]                     NVARCHAR (255)   NOT NULL,
    [LabelsPer_]                 INT              NULL,
    [CoreSize]                   FLOAT (53)       NULL,
    [SizeAround]                 FLOAT (53)       NULL,
    [StockNum1]                  NVARCHAR (255)   NULL,
    [StockNum2]                  NVARCHAR (255)   NULL,
    [Stockwidth2]                FLOAT (53)       NULL,
    [Priority]                   NVARCHAR (255)   NULL,
    [StockNum3]                  NVARCHAR (255)   NULL,
    [TicketType]                 INT              NULL,
    [CSA]                        BIT              NULL,
    [UL]                         BIT              NULL,
    [ConsecNo]                   BIT              NULL,
    [MainTool]                   NVARCHAR (255)   NULL,
    [Shape]                      NVARCHAR (255)   NULL,
    [NoArounPlate]               INT              NULL,
    [ColSpace]                   FLOAT (53)       NULL,
    [EstFootage]                 INT              NULL,
    [Est_SetupFootage]           INT              NULL,
    [Est_SpoilFootage]           INT              NULL,
    [OverRun]                    FLOAT (53)       NULL,
    [LabelRepeat]                FLOAT (53)       NULL,
    [OutsideDiameter]            FLOAT (53)       NULL,
    [FinishType]                 NVARCHAR (255)   NULL,
    [Tab]                        FLOAT (53)       NULL,
    [BackStage_ColorStrategy]    NVARCHAR (255)   NULL,
    [StockDesc1]                 NVARCHAR (255)   NULL,
    [Roto_Quote_Number]          NVARCHAR (255)   NULL,
    [ShrinkSleeve_LayFlat]       FLOAT (53)       NULL,
    [ShrinkSleeve_CutHeight]     FLOAT (53)       NULL,
    [ShrinkSleeve_OverLap]       FLOAT (53)       NULL,
    [BackStage_SmartMarkSet]     NVARCHAR (255)   NULL,
    [SizeAcross]                 FLOAT (53)       NULL,
    [FinalUnwind]                NVARCHAR (255)   NULL,
    [Use_TurretRewinder]         BIT              NULL,
    [numberOfFinishedRolls]      DECIMAL (10, 5)  NULL,
    [numberOfLeftoverRolls]      DECIMAL (38, 5)  NULL,
    [NoColors]                   INT              NULL,
    [NoItems]                    INT              NULL,
    [NumberofPlateChanges]       INT              NULL,
    [Stock2_LinerCaliper]        INT              NULL,
    [Varnish]                    VARCHAR (103)    NOT NULL,
    [SpotVarnish]                INT              NOT NULL,
    [PeelandReveal]              INT              NOT NULL,
    [PantoneGreen]               INT              NOT NULL,
    [PantoneOrange]              INT              NOT NULL,
    [PantoneSilver]              INT              NOT NULL,
    [SpecialSilverGold]          INT              NOT NULL,
    [SandpaperVarnish]           INT              NOT NULL,
    [Stock2PressGrouping]        VARCHAR (255)    NULL,
    [LinearLength_Calc]          FLOAT (53)       NULL,
    [ShipTime]                   DATETIME         NULL,
    [MainToolGearTeeth]          INT              NULL,
    [Silkscreen]                 INT              NULL,
    [HotFoil]                    INT              NOT NULL,
    [Embossing]                  INT              NULL,
    [MultiLayer]                 INT              NOT NULL,
    [ColdFoil]                   INT              NOT NULL,
    [Inlinesheeter]              INT              NOT NULL,
    [LockTooling]                INT              NULL,
    [Turnbar]                    BIT              NULL,
    [NoAcross]                   INT              NULL,
    [Remaining Quantity]         INT              NULL,
    [NumberofRemainingCores]     DECIMAL (15, 2)  NULL,
    [CoreWidth]                  FLOAT (53)       NULL,
    [numberOfStops]              DECIMAL (32, 16) NULL,
    [DoublePass_ReinsertionFlag] INT              NOT NULL,
    [FinishedRollLength]         FLOAT (53)       NULL,
    [DueDateBucket]              VARCHAR (11)     NOT NULL,
    [daysLate]                   INT              NULL,
    [customerRank]               VARCHAR (1)      NOT NULL,
    [revenuePercentile]          NUMERIC (33, 12) NULL,
    [customerRankingPoints]      INT              NOT NULL,
    [dueDatePoints]              NUMERIC (12, 2)  NULL,
    [orderSizePoints]            NUMERIC (34, 12) NULL,
    [priorityPoints]             INT              NOT NULL,
    [ticketPoints]               NUMERIC (38, 6)  NULL
);

