CREATE TABLE [dbo].[ProductMaster]
(
	Id					varchar (36),	
	TenantId			varchar (36)		NOT NULL,
	Source				varchar (36)		NOT NULL,
	SourceProductId		nvarchar (4000),
	ColorDesc			nvarchar (4000),
	SourceProductGroup	nvarchar (4000),
	ToolingNotes		nvarchar (4000),
	SlitOnRewind		bit					NOT NULL,
	NumColors			smallint			NULL,
	NumFloods           smallint			NULL,
	ProductNum          NVARCHAR (4000)		NULL,
    PlateId				NVARCHAR (4000)		NULL,
	CustomField1		NVARCHAR (4000)		NULL,
	CriticalQuality 	NVARCHAR (4000)		NULL,
	ProdDescr           NVARCHAR (4000)		NULL,
	MaterialTrac        bit					NULL,
	SourceCreatedOn		Datetime			NULL,
	SourceModifiedOn	Datetime			NULL,
	IsEnabled			bit					NOT NULL,
	ColumnPerf          REAL				NULL,
    RowPerf             REAL				NULL,
	CreatedOn			Datetime			NOT NULL,
	ModifiedOn			Datetime			NOT NULL,
	ProductGroupId      nvarchar (4000),
	ProductPopup1       NVARCHAR (4000)		NULL,
	ProductPopup2       NVARCHAR (4000)		NULL,
	ProductPopup3       NVARCHAR (4000)		NULL,
	ProductPopup4       NVARCHAR (4000)		NULL,
	ProductPopup5       NVARCHAR (4000)		NULL,
	ProductPopup6       NVARCHAR (4000)		NULL,    
	JobType				nvarchar(4000)		NULL,
	ProductType			NVARCHAR(4000)		NULL,
	SheetPackType		nvarchar(4000)		NULL,
	CoreWidth			REAL				NULL,
	Notes				NVARCHAR(4000)		NULL,
	FinishedWidth		DECIMAL(18, 0)		NULL,
	FinishedLength		DECIMAL(18, 0)		NULL,
	EquipNoColors		SMALLINT			NULL,
	EquipNoFloods		SMALLINT			NULL,
	RevisionNumber	    NVARCHAR(100)       NULL,
	CONSTRAINT [PK_ProductMasterID] PRIMARY KEY NONCLUSTERED ([Id])
)
