CREATE TABLE ShiftCalendarDatesV2
(
Id VARCHAR(36) PRIMARY KEY,
ShiftCalendarId VARCHAR(36) FOREIGN KEY REFERENCES ShiftCalendarV2(ID) NOT NULL,
StartDate DATETIME NOT NULL,
EndDate DATETIME NOT NULL,
CreatedOnUTC DATETIME,
ModifiedOnUTC DATETIME
)
