CREATE TABLE ShiftCalendarPatternV2(
Id VARCHAR(36) PRIMARY KEY,
ShiftCalendarId VARCHAR(36) FOREIGN KEY REFERENCES ShiftCalendarV2(Id) NOT NULL,
DayOfWeek VARCHAR(16) NOT NULL,
StartTime TIME(7) NOT NULL,
EndTime TIME(7) NOT NULL,
CreatedOnUTC DATETIME,
ModifiedOnUTC DATETIME
);
