CREATE TABLE [dbo].[TicketDataCache_temp]
(
		[ID] INT PRIMARY KEY IDENTITY(1,1),
		[TicketId] VARCHAR(36), 
		[TicketNumber] NVARCHAR(255),
		[TaskName] NVARCHAR(255),
		[IsComplete] BIT NULL,
		[TaskEstimatedMeters] REAL NULL,
		[CustomerName] NVARCHAR(255), 
		[GeneralDescription] NVARCHAR(4000), 
		[TicketPoints] NUMERIC, 
		[ShipByDate] DATETIME, 
		[OrderDate] DATETIME, 
		[SourceCustomerId] NVARCHAR(36), 
		[CustomerPO] NVARCHAR(255), 
		[TicketPriority] NVARCHAR(255), 
		[FinishType] NVARCHAR(255), 
		[IsBackSidePrinted] BIT, 
		[IsSlitOnRewind] BIT, 
		[UseTurretRewinder] BIT,
		[EstTotalRevenue] REAL, 
		[TicketType] SMALLINT, 
		[PriceMode] NVARCHAR(4000), 
		[FinalUnwind] NVARCHAR(4000), 
		[TicketStatus] NVARCHAR(4000), 
		[BackStageColorStrategy] NVARCHAR(4000), 
		[Pinfeed] BIT, 
		[IsPrintReversed] BIT, 
		[TicketNotes] NVARCHAR(4000), 
		[EndUserNum] NVARCHAR(4000), 
		[EndUserName] NVARCHAR(4000), 
		[CreatedOn] DATETIME, 
		[ModifiedOn] DATETIME, 
		[Tab] REAL,
    [SizeAround] REAL, 
		[ShrinkSleeveLayFlat] REAL, 
		[Shape] NVARCHAR(4000), 
		[StockTicketType] SMALLINT, 
		[ArtWorkComplete] BIT, 
		[InkReceived] BIT, 
		[ProofComplete] BIT, 
		[PlateComplete] BIT,
		[ToolsReceived] BIT, 
		[StockReceived] INT, 
		[ITSName] NVARCHAR(1000), 
		[OTSName] NVARCHAR(1000), 
		[ConsecutiveNumber] BIT, 
		[Quantity] INT, 
		[ActualQuantity] INT, 
		[SizeAcross] REAL, 
		[ColumnSpace] REAL, 
		[RowSpace] REAL, 
		[NumAcross] SMALLINT, 
		[NumAroundPlate] SMALLINT, 
		[LabelRepeat] REAL, 
		[FinishedNumAcross] REAL, 
		[FinishedNumLabels] INT, 
		[Coresize] REAL, 
		[OutsideDiameter] REAL, 
		[EstimatedLength] INT, 
		[OverRunLength] REAL, 
		[NoOfPlateChanges] INT, 
		[ShippedOnDate] DATETIME, 
		[ShipVia] NVARCHAR(4000), 
		[DueOnsiteDate] DATETIME, 
		[ShippingStatus] NVARCHAR(4000),
		[ShippingAddress] NVARCHAR(4000), 
		[Shippingcity] NVARCHAR(1000), 
		[TicketCategory] INT, 
		[ITSAssocNum] NVARCHAR(1000), 
		[OTSAssocNum] NVARCHAR(1000), 
		[ShippingInstruc] NVARCHAR(4000), 
		[DateDone] DATETIME, 
		[ShipAttnEmailAddress] NVARCHAR(1000), 
		[ShipLocation] NVARCHAR(1000), 
		[ShipZip] NVARCHAR(255), 
		[BillAddr1] NVARCHAR(1000), 
		[BillAddr2] NVARCHAR(1000), 
		[BillCity] NVARCHAR(255),
		[BillZip] NVARCHAR(255),
		[BillCountry] NVARCHAR(255), 
		[IsStockAllocated] BIT, 
		[EndUserPO] NVARCHAR(1000), 
		[Tool1Descr] NVARCHAR(4000), 
		[Tool2Descr] NVARCHAR(4000), 
		[Tool3Descr] NVARCHAR(4000), 
		[Tool4Descr] NVARCHAR(4000), 
		[Tool5Descr] NVARCHAR(4000), 
		[ActFootage] INT, 
		[EstPackHrs] REAL, 
		[ActPackHrs] REAL,
		[InkStatus] NVARCHAR(4000), 
		[BillState] NVARCHAR(255), 
		[CustContact] NVARCHAR(1000), 
		[CoreType] NVARCHAR(255), 
		[RollUnit] NVARCHAR(255),
		[RollLength] INT,
		[FinishNotes] NVARCHAR(4000), 
		[ShipCounty] NVARCHAR(255), 
		[StockNotes] NVARCHAR(4000),
		[CreditHoldOverride] BIT, 
		[ShrinkSleeveOverLap] BIT,
		[ShrinkSleeveCutHeight] BIT, 
		[StockDesc1] NVARCHAR(4000), 
		[StockDesc2] NVARCHAR(4000),
		[StockDesc3] NVARCHAR(4000), 
		[StockStatus] VARCHAR(64),
		[WorkcenterMaterialTicketCategory] INT, 
		[IsCompletingOnTime] INT,
		[Highlight] BIT,
		[HasPreviousTaskPartiallyRan] BIT,
		[isTicketGeneralNotePresent] INT,
		[StagingStatus] VARCHAR(36),
		[IsFirstDay] BIT,
		[OriginalEquipmentId] VARCHAR(36) NULL,
		[OriginalEquipmentName] NVARCHAR(256) NULL,
		[WorkcenterTypeId] VARCHAR(36) NULL,
		[WorkCenterName] NVARCHAR(64) NULL,
		[FacilityId] VARCHAR(36) NULL,
		[FacilityName] NVARCHAR(256) NULL,
		[ActualEstTotalHours] REAL NULL,
		[EstMaxDueDateTime] DATETIME NULL,
		[Colors] VARCHAR(4000) NULL,
		[Plates] VARCHAR(4000) NULL,
		[ColumnPerf] VARCHAR(256) NULL,
		[RowPerf] VARCHAR(256) NULL,
		[IsDependentProdReady] BIT NULL,
		[DependentTicketId] VARCHAR(256) NULL
);