CREATE TABLE TicketMaster
(	
	ID VARCHAR(36) PRIMARY KEY NOT NULL,
	Source NVARCHAR(64) NOT NULL,
	SourceTicketId NVARCHAR(255),
	TenantId NVARCHAR(36)  NOT NULL,
	OrderDate datetime  NULL,
	SourceCustomerId NVARCHAR(36)  NULL,
	CustomerName  NVARCHAR(255)   NULL,
	CustomerPO NVARCHAR(255) NULL,
	SourcePriority NVARCHAR(255) NULL,
	SourceFinishType NVARCHAR(255) NULL,
	isBackSidePrinted BIT NULL,
	IsSlitOnRewind BIT NULL,
	UseTurretRewinder BIT NULL,
	EstTotalRevenue REAL NOT NULL,
	SourceTicketType SMALLINT NOT NULL,
	SourceStockTicketType SMALLINT NOT NULL,
	PriceMode NVARCHAR(4000) NULL,
	FinalUnwind NVARCHAR(4000) NULL,
	IsOpen BIT NOT NULL,
	SourceStatus NVARCHAR(4000) NOT NULL,
	IsOnHold BIT NOT NULL,
	BackStageColorStrategy NVARCHAR(4000),
	GeneralDescription NVARCHAR (4000) NULL,
	Pinfeed		BIT   NULL,
    [IsPrintReversed] BIT NULL,
	SourceTicketNotes nvarchar(4000) NULL,
	EndUserNum      nvarchar(4000) NULL,
	EndUserName     nvarchar (4000) NULL,
	Tab             REAL  NULL,
	SizeAround		REAL	NULL,
	ShrinkSleeveLayFlat	REAL NULL,
	Shape				nvarchar(4000) NULL,
	InkStatus		nvarchar(4000) NULL,
	SourceCreatedOn DATETIME NOT NULL,
	SourceModifiedOn DATETIME  NULL,
	CreatedOn DATETIME NOT NULL,
	ModifiedOn DATETIME NOT NULL,
	Press nvarchar(255) Null,
	EquipId nvarchar(255) Null,
	Equip3Id nvarchar(255) Null,
	Equip4Id nvarchar(255) Null,
	RewindEquipNum nvarchar(255) Null,
	ITSName nvarchar(1000) Null,
	OTSName nvarchar(1000) Null,
	ITSAssocNum nvarchar(1000) Null,
	OTSAssocNum nvarchar(1000) Null,
	DateDone datetime Null,
	EndUserPO nvarchar(1000) Null,
	IsStockAllocated bit Null,
	EstPackHrs real Null,
	ActPackHrs real Null,
	CustContact nvarchar(1000) Null,
	FinishNotes nvarchar(4000) Null,
	StockNotes nvarchar(4000) Null,
	CreditHoldOverride bit Null,
	ShrinkSleeveOverLap bit Null,
	ShrinkSleeveCutHeight bit Null,
	PressDone bit Null,
	EquipDone bit Null,
	Equip3Done bit Null,
	Equip4Done bit Null,
	FinishDone bit Null,
	EstRunHrs real Null,
	EstMRHrs real Null,
	Terms nvarchar(4000) Null,
	EstTime real Null,
	EquipEstTime real Null,
	Equip3EstTime real Null,
	Equip4EstTime real Null,
	EstFinHrs real Null,
	EquipEstRunHrs real Null,
	Equip3EstRunHrs real Null,
	Equip4EstRunHrs real Null,
	EstWuHrs real Null,
	EquipWashUpHours real Null,
	Equip3WashUpHours real Null,
	Equip4WashUpHours real Null,
	EquipMakeReadyHours real Null,
	Equip3MakeReadyHours real Null,
	Equip4MakeReadyHours real Null,
	RotoQuoteNumber nvarchar (4000) NULL,
	PlateStatus nvarchar (4000) NULL,
	FlexPackGusset	REAL  NULL,
	FlexPackHeight	REAL  NULL,
	EstPostPressHours nvarchar (4000) Null,
	CoreType nvarchar (4000) Null,
	Equip2Id nvarchar(510) NULL,
	Equip5Id nvarchar(510) NULL,
	Equip6Id nvarchar(510) NULL,
	Equip7Id nvarchar(510) NULL,
	Equip2Done bit NULL,
	Equip5Done bit NULL,
	Equip6Done bit NULL,
	Equip7Done bit NULL,
	Equip5EstRunHrs real NULL,
	Equip6EstRunHrs real NULL,
	Equip7EstRunHrs real NULL,
	Equip6WashUpHours real NULL,
	Equip5WashUpHours real NULL,
	Equip7WashUpHours real NULL,
	Equip2MakeReadyHours real NULL,
	Equip5MakeReadyHours real NULL,
	Equip6MakeReadyHours real NULL,
	Equip7MakeReadyHours real NULL,
	Equip1TaskName varchar(510) NULL,
	Equip2TaskName varchar(510) NULL,
	Equip3TaskName varchar(510) NULL,
	Equip4TaskName varchar(510) NULL,
	Equip5TaskName varchar(510) NULL,
	Equip6TaskName varchar(510) NULL,
	Equip7TaskName varchar(510) NULL,
	Equip5EstTime real NULL,
	Equip6EstTime real NULL,
	Equip7EstTime real NULL,
	DependentSourceTicketId NVARCHAR(255) NULL,
	TicketCategory int DEFAULT 0, -- 0 -> Regular Ticket (No Relation), 1 -> Parent Ticket, 2 -> Sub Job Ticket
	ShipStatus varchar(255) NULL,
	Press_Status varchar(255) NULL,
	InternetSubmission bit NULL,
	SourceCompanyId NVARCHAR(255),
	SourceFacilityId NVARCHAR(255),
	TicketRowspace REAL NULL,
	FinishStatus NVARCHAR(4000) NULL,
	StockStatus VARCHAR(64) NULL,
	EnteredBy NVARCHAR(100) NULL,
	PreviousTicketNumber VARCHAR(36) NULL,
	[FacilityId] VARCHAR(36) NULL,
	[EstimatedPressSpeed] SMALLINT NULL
)