CREATE TABLE [dbo].[TicketAll] (
    [Number]                       NVARCHAR (255)  NOT NULL,
    [ID]                           INT             NULL,
    [CustomerNum]                  NVARCHAR (255)  NULL,
    [CustomerName]                 NVARCHAR (255)  NULL,
    [ShipVia]                      NVARCHAR (255)  NULL,
    [OrderDate]                    DATE            NULL,
    [ArtStat]                      NVARCHAR (255)  NULL,
    [ProofStat]                    NVARCHAR (255)  NULL,
    [PlateStat]                    NVARCHAR (255)  NULL,
    [ToolStat]                     NVARCHAR (255)  NULL,
    [PressStat]                    NVARCHAR (255)  NULL,
    [ArtDone]                      BIT             NULL,
    [ProofDone]                    BIT             NULL,
    [PlateDone]                    BIT             NULL,
    [ToolsIn]                      BIT             NULL,
    [StockIn]                      NVARCHAR (255)  NULL,
    [EstPackHrs]                   FLOAT (53)      NULL,
    [ActQuantity]                  INT             NULL,
    [Is_Ink_In]                    BIT             NULL,
    [Ink_Status]                   NVARCHAR (255)  NULL,
    [ActualBillings_NetOfSalesTax] FLOAT (53)      NULL,
    [ActualRewindingHours]         FLOAT (53)      NULL,
    [ActualTotalHours]             FLOAT (53)      NULL,
    [ActualTotalLaborCosts]        FLOAT (53)      NULL,
    [ActStockCost]                 FLOAT (53)      NULL,
    [ActualTotalPOCosts]           FLOAT (53)      NULL,
    [ActualTotalMatAndFreightCost] FLOAT (53)      NULL,
    [ActTotalCost]                 FLOAT (53)      NULL,
    [EstStockCost]                 FLOAT (53)      NULL,
    [DateShipped]                  DATE            NULL,
    [OTSName]                      NVARCHAR (255)  NULL,
    [ITSName]                      NVARCHAR (255)  NULL,
    [EntryDate]                    DATE            NULL,
    [GeneralDescr]                 NVARCHAR (255)  NULL,
    [Notes]                        NVARCHAR (4000) NULL,
    [FinishStat]                   NVARCHAR (255)  NULL,
    [MiscCharge]                   FLOAT (53)      NULL,
    [NoAcross]                     INT             NULL,
    [POTotal]                      FLOAT (53)      NULL,
    [NoLabAcrossFin]               INT             NULL,
    [Press]                        NVARCHAR (255)  NULL,
    [RowSpace]                     FLOAT (53)      NULL,
    [Ship_by_Date]                 DATE            NULL,
    [LabelsPer_]                   INT             NULL,
    [CoreSize]                     FLOAT (53)      NULL,
    [SizeAround]                   FLOAT (53)      NULL,
    [StockNum1]                    NVARCHAR (255)  NULL,
    [StockNum2]                    NVARCHAR (255)  NULL,
    [Stockwidth2]                  FLOAT (53)      NULL,
    [Priority]                     NVARCHAR (255)  NULL,
    [StockNum3]                    NVARCHAR (255)  NULL,
    [TicketType]                   INT             NULL,
    [TicQuantity]                  INT             NULL,
    [StockDesc2]                   NVARCHAR (255)  NULL,
    [StockDesc3]                   NVARCHAR (255)  NULL,
    [TicketStatus]                 NVARCHAR (255)  NULL,
    [ActFootage]                   INT             NULL,
    [EstMRHrs]                     FLOAT (53)      NULL,
    [EstWuHrs]                     FLOAT (53)      NULL,
    [EstRunHrs]                    FLOAT (53)      NULL,
    [EstPressTime]                 FLOAT (53)      NULL,
    [EstFinHrs]                    FLOAT (53)      NULL,
    [EstPostPressHours]            FLOAT (53)      NULL,
    [EstTotal]                     FLOAT (53)      NULL,
    [RewindEquipNum]               NVARCHAR (255)  NULL,
    [CSA]                          BIT             NULL,
    [UL]                           BIT             NULL,
    [ConsecNo]                     BIT             NULL,
    [MainTool]                     NVARCHAR (255)  NULL,
    [Shape]                        NVARCHAR (255)  NULL,
    [NoArounPlate]                 INT             NULL,
    [ColSpace]                     FLOAT (53)      NULL,
    [EstFootage]                   INT             NULL,
    [Est_SetupFootage]             INT             NULL,
    [Est_SpoilFootage]             INT             NULL,
    [OverRun]                      FLOAT (53)      NULL,
    [LabelRepeat]                  FLOAT (53)      NULL,
    [OutsideDiameter]              FLOAT (53)      NULL,
    [Equip_ID]                     NVARCHAR (255)  NULL,
    [Equip_MakeReadyHours]         FLOAT (53)      NULL,
    [Equip_WashUpHours]            FLOAT (53)      NULL,
    [Equip_EstRunHrs]              FLOAT (53)      NULL,
    [Equip_EstTime]                FLOAT (53)      NULL,
    [Equip3_ID]                    NVARCHAR (255)  NULL,
    [Equip3_MakeReadyHours]        FLOAT (53)      NULL,
    [Equip3_WashUpHours]           FLOAT (53)      NULL,
    [Equip3_EstRunHrs]             FLOAT (53)      NULL,
    [Equip3_EstTime]               FLOAT (53)      NULL,
    [Equip4_ID]                    NVARCHAR (255)  NULL,
    [Equip4_MakeReadyHours]        FLOAT (53)      NULL,
    [Equip4_WashUpHours]           FLOAT (53)      NULL,
    [Equip4_EstRunHrs]             FLOAT (53)      NULL,
    [Equip4_EstTime]               FLOAT (53)      NULL,
    [FinishType]                   NVARCHAR (255)  NULL,
    [Tool2Descr]                   NVARCHAR (255)  NULL,
    [Tool3Descr]                   NVARCHAR (255)  NULL,
    [Tool4Descr]                   NVARCHAR (255)  NULL,
    [Tool5Descr]                   NVARCHAR (255)  NULL,
    [Tab]                          FLOAT (53)      NULL,
    [ColorStrategy]                VARCHAR (255)   NULL,
    [StockDesc1]                   NVARCHAR (255)  NULL,
    [Roto_Quote_Number]            NVARCHAR (255)  NULL,
    [ShrinkSleeve_LayFlat]         FLOAT (53)      NULL,
    [ShrinkSleeve_CutHeight]       FLOAT (53)      NULL,
    [ShrinkSleeve_OverLap]         FLOAT (53)      NULL,
    [PressDone]                    BIT             NULL,
    [Equip_Status]                 NVARCHAR (255)  NULL,
    [Equip_Done]                   BIT             NULL,
    [Due_on_Site_Date]             DATE            NULL,
    [Equip3_Status]                NVARCHAR (255)  NULL,
    [Equip3_Done]                  BIT             NULL,
    [Equip4_Status]                NVARCHAR (255)  NULL,
    [Equip4_Done]                  BIT             NULL,
    [FinishDone]                   BIT             NULL,
    [SmartMarkSet]                 VARCHAR (255)   NULL,
    [SizeAcross]                   FLOAT (53)      NULL,
    [FinalUnwind]                  NVARCHAR (255)  NULL,
    [Use_TurretRewinder]           BIT             NULL,
    [StockTicketType]              INT             NULL,
    [PriceMode]                    NVARCHAR (255)  NULL,
    [CustPONum]                    NVARCHAR (255)  NULL,
    [ShipAttn]                     NVARCHAR (255)  NULL,
    [ShipLocation]                 NVARCHAR (255)  NULL,
    [ShipAddr1]                    NVARCHAR (255)  NULL,
    [ShipAddr2]                    NVARCHAR (255)  NULL,
    [ShipCity]                     NVARCHAR (255)  NULL,
    [ShipSt]                       NVARCHAR (255)  NULL,
    [ShipZip]                      NVARCHAR (255)  NULL,
    [ShipCountry]                  NVARCHAR (255)  NULL,
    [Ship_Address_ID]              NVARCHAR (255)  NULL,
    [ShippingInstruc]              NVARCHAR (255)  NULL,
    [ShippingStatus]               NVARCHAR (255)  NULL,
    [ToolNo2]                      NVARCHAR (255)  NULL,
    [ToolNo3]                      NVARCHAR (255)  NULL,
    [ToolNo4]                      NVARCHAR (255)  NULL,
    [ToolNo5]                      NVARCHAR (255)  NULL,
    [Turnbar]                      BIT             NULL,
    [EntryTime]                    INT             NULL,
    [ModifyDate]                   DATE            NULL,
    [ModifyTime]                   INT             NULL
);

