CREATE TABLE [dbo].[TicketTask] --to be deprecated
	(
		Id					VARCHAR(36)		NOT NULL,
		TicketId			VARCHAR(36)		NOT NULL CONSTRAINT [FK_TicketTask_TicketMasterId] FOREIGN KEY REFERENCES TicketMaster(Id),
		TaskName			NVARCHAR(255)    NOT NULL,
		[Sequence]			SMALLINT		NOT NULL,
		OriginalEquipmentId	VARCHAR(36)	    NOT NULL CONSTRAINT [FK_TicketTask_Original_EquipmentMasterId] FOREIGN KEY REFERENCES EquipmentMaster(Id),
		ActualEquipmentId	VARCHAR(36)	    NULL CONSTRAINT [FK_TicketTask_Actual_EquipmentMasterId] FOREIGN KEY REFERENCES EquipmentMaster(Id),
		WorkcenterId		VARCHAR(36)		NULL,
		IsComplete			bit				NOT  NULL,
		EstMakeReadyHours	real			NULL,
		EstWashupHours		real			NULL,
		EstRunHours		    real			NULL,
		EstTotalHours		real			NULL,
		EstMaxDueDateTime   DATETIME		NULL,
		CreatedOn			DATETIME		NOT NULL,
		ModifiedOn			DATETIME		NOT NULL,
		Pass                int             null,
		DoublePassJob		int				null,
		DoublePass_ReInsertionFlag int		null,
		EstMeters			real			null,
		IsProductionReady   bit             NOT NULL,
		[Lag]				real				null,
		[Delay]				real             null,
		[DependentSourceTicketId] NVARCHAR(255) NULL,
		[EnforceTaskDependency] [bit] NOT NULL DEFAULT 0,
		[TaskStockStatus]	varchar(64) NULL,
		[MasterRollNumber] [varchar](255) NULL,
		[TaskClassification] [nvarchar](1090) NULL,
		[MasterRollClassification] [nvarchar](1701) NULL,
		[ActualEstTotalHours] real NULL,
		CONSTRAINT [PK_TicketTaskId] PRIMARY KEY NONCLUSTERED ([Id] ASC)
	);