CREATE TABLE [dbo].[TicketDimensions]
(
	Id						VARCHAR(36)		PRIMARY KEY DEFAULT NEWID(),
	TicketId				VARCHAR(36)		NOT NULL CONSTRAINT [FK_TicketDimensions_TicketMasterId] FOREIGN KEY REFERENCES TicketMaster(Id),
	ConsecutiveNumber		BIT				NOT NULL,
	Quantity				INT				NOT NULL,
	ActualQuantity			INT				NOT NULL,
	SizeAcross				REAL			NOT NULL,
	SizeAround				REAL			NOT NULL,
	Shape					NVARCHAR(4000)	NULL,
	ColumnSpace				REAL			NOT NULL,
	RowSpace				REAL			NOT NULL,
	NumAcross				SMALLINT 		NOT NULL,
	NumAroundPlate			SMALLINT 		NOT NULL,
	LabelRepeat				REAL			NOT NULL,
	FinishedNumAcross		REAL			NOT NULL,
	FinishedNumLabels		INT				NOT NULL,
	CoreSize				REAL			NOT NULL,
	OutsideDiameter			REAL			NOT NULL,
	EsitmatedLength			INT				NOT NULL,
	OverRunLength			REAL			NOT NULL,
	CalcLinearLength		REAL			NULL,
	CalcNumLeftoverRolls	REAL			NULL,
	CalcFinishedRollLength	REAL			NULL,
	CalcCoreWidth			REAL			NULL,
	CalcNumStops			REAL			NULL,
	NoPlateChanges			INT             NULL,
	CreatedOn				DATETIME		NOT NULL,
	ModifiedOn				DATETIME		NOT NULL,
	ActFootage				INT				NULL,
	CoreType				NVARCHAR(255)	NULL,
	RollLength				INT				NULL,
	RollUnit				NVARCHAR(255)	NULL,
	EstimatedLength			INT				NOT NULL,
	PrintRepeat				DECIMAL (18, 4)  NULL,
	FlatSizeWidth			DECIMAL (18, 4)  NULL,
	FlatSizeLength			DECIMAL(18, 4)  NULL,
	PackQuantity			DECIMAL(18, 4)  NULL,
	NumberUp				DECIMAL(18,4) NULL,
	CONSTRAINT [AK_TicketDimensions_TicketId] UNIQUE NONCLUSTERED ([TicketId] ASC)
)