CREATE TABLE [dbo].[TicketTask_temp](
	[Id] [varchar](36) NOT NULL,
	[TicketId] [varchar](36) NOT NULL,
	[TaskName] [nvarchar](255) NOT NULL,
	[Sequence] [smallint] NOT NULL,
	[OriginalEquipmentId] [varchar](36) NOT NULL,
	[ActualEquipmentId] [varchar](36) NULL,
	[WorkcenterId] [varchar](36) NOT NULL,
	[IsComplete] [bit] NOT NULL,
	[EstMakeReadyHours] [real] NULL,
	[EstWashupHours] [real] NULL,
	[EstRunHours] [real] NULL,
	[EstTotalHours] [real] NULL,
	[EstMaxDueDateTime] [datetime] NULL,
	[CreatedOn] [datetime] NOT NULL,
	[ModifiedOn] [datetime] NOT NULL,
	[Pass] [int] NULL,
	[DoublePassJob] [int] NULL,
	[DoublePass_ReInsertionFlag] [int] NULL,
	[EstMeters] [real] NULL,
	IsProductionReady   bit   NOT NULL,
	[Lag]				real				null,
	[Delay]				real             null,
	[DependentSourceTicketId] NVARCHAR(255) NULL,
	[EnforceTaskDependency] [bit] NOT NULL DEFAULT 0,
	[TaskStockStatus]	varchar(64) NULL,
	[MasterRollNumber] [varchar](255) NULL,
	[TaskClassification] [nvarchar](1090) NULL,
	[MasterRollClassification] [nvarchar](1701) NULL,
	[ActualEstTotalHours] real NULL,
	CONSTRAINT [PK_TicketTask_temp] PRIMARY KEY NONCLUSTERED([ID] ASC)
	)
