CREATE TABLE ToolingInventoryBreakdown
(
	Id					VARCHAR(36)		NOT NULL,
	ToolingNumber		VARCHAR(36)		NOT NULL, --Generated by concatenating source tooling number with its order of quantity available
	FacilityId			VARCHAR(36)				, --Foreign key to Facility ID 
	ToolingId			VARCHAR(36)		NOT NULL, --Foreign key to ToolingInventory.Id
	CreatedOnUTC		DATETIME		NOT NULL,
	ModifiedOnUTC		DATETIME		NOT NULL,
    CONSTRAINT [PK_ToolingInventoryBreakdownID] PRIMARY KEY NONCLUSTERED ([Id])
);
