CREATE TABLE [dbo].[UnassignedJobs](
	[ID] [varchar](36) PRIMARY KEY NOT NULL,
	[RouteFeasible] [bit] NOT NULL,
	[CustomerNum] [nvarchar](255) NULL,
	[TaskName] [nvarchar](255) NULL,
	[TaskDueTime] [datetime] NULL,
	[Number] [nvarchar](255) NULL,
	[DoublePass_ReinsertionFlag] [bit] NOT NULL,
	[TaskEstimatedHours] [float] NULL,
	[Press] [nvarchar](255) NULL,
	[Pass] [int] NULL,
	[Priority] [nvarchar](255) NULL,
	[WorkcenterName] [nvarchar](255) NULL,
	[LastScan] [datetime] NULL,
	[ShipTime] [datetime] NULL,
	[TicketPoints] [numeric](38, 6) NULL,
	[LinearLengthCalc] [float] NULL,
	[DoublePassJob] [int] NULL,
	[DueDateBucket] [varchar](11) NULL,
	[MasterRollNumber] [varchar](255) NULL,
	[TaskDueTimeReference] [bigint] NULL,
	[TaskEstimatedMinutes] [float] NULL,
	[TaskIndex] [bigint] NULL,
	[PressNumber] [varchar](20) NULL,
	[HighPriority] [int] NULL,
	[TaskClassification] [nvarchar](1090) NULL,
	[MasterRollClassification] [nvarchar](1701) NULL,
	[JobFirstAvailable] [int] NOT NULL,
	[CreatedOn] [datetime] NULL,
	[ModifiedOn] [datetime] NULL,
	IsProductionReady bit NULL ,
	[Lag]				int				null,
	[Delay]				int             null,
	[DependentSourceTicketId] NVARCHAR(255) NULL,
	[TicketTaskDataId] NVARCHAR(255) NULL,
	[EnforceTaskDependency] [bit] NOT NULL DEFAULT 0
)