{{- if and .Values.podDisruptionBudget.enabled}}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "helm-chart.fullname" . }}-pdb
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
{{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
{{- end }}
{{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
{{- end }}
  selector:
    matchLabels:
      {{- include "helm-chart.selectorLabels" . | nindent 6 }}
{{- end }}