{{- if .Values.secretProviderClass.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "helm-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "{{ .Values.secretProviderClass.parameterStore.name }}"
        objectType: "ssmparameter"
        objectAlias: "{{ .Values.secretProviderClass.parameterStore.fileName }}"
    region: "{{ .Values.secretProviderClass.parameterStore.region }}"
    pollingInterval: "{{ .Values.secretProviderClass.parameterStore.pollInterval }}"
  secretObjects:
    - secretName: "{{ .Values.secretProviderClass.parameterStore.fileName }}-secret"
      type: Opaque
      data:
        - objectName: "{{ .Values.secretProviderClass.parameterStore.fileName }}"
          key: appsettings.json
{{- end }}