CREATE TABLE TenantUser(
  ID			VARCHAR(36) CONSTRAINT [PK_TenantUserID] PRIMARY KEY NOT NULL,
  TenantId		VARCHAR(36) CONSTRAINT [FK_TenantUser_TenantId] FOREIGN KEY REFERENCES Tenant(Id),
  UserId		VARCHAR(36) CONSTRAINT [FK_TenantUser_UserAccountsId] FOREIGN KEY REFERENCES UserAccounts(Id),
  CreatedOn		DATETIME,
  ModifiedOn	DATETIME
  CONSTRAINT USP_TSUSR UNIQUE (UserId)
)