CREATE TABLE [dbo].[PM_Item]
(
	[Adhesive] int NULL,
	[AutoActual] int NULL,
	[AutoRequisition] int NULL,
	[AutoReserve] int NULL,
	[caliper] decimal(18, 0) NULL,
	[ClassId] int NULL,
	[CoatingGroupCode] nvarchar(4000) NULL,
	[CoatingStatus] int NULL,
	[ColourCode] nvarchar(4000) NULL,
	[CompNum] int NULL,
	[createDate] datetime NULL,
	[CustCode] nvarchar(4000) NULL,
	[CustItem2Desc] nvarchar(4000) NULL,
	[CustItemDesc] nvarchar(4000) NULL,
	[CustItemRef] nvarchar(4000) NULL,
	[CustItemRef2] nvarchar(4000) NULL,
	[Density] decimal(18, 0) NULL,
	[Depth] decimal(18, 0) NULL,
	[DimA] decimal(18, 0) NULL,
	[DimB] decimal(18, 0) NULL,
	[DimC] decimal(18, 0) NULL,
	[DimFormat] nvarchar(4000) NULL,
	[EndUseCode] int NULL,
	[est-kitemkey] int NULL,
	[EstimateUse] int NULL,
	[FinishingGroupCode] nvarchar(4000) NULL,
	[FixedCost] int NULL,
	[FoldoverDim] decimal(18, 0) NULL,
	[FromFreeStock] bit NULL,
	[InActive] int NULL,
	[Issued] bit NULL,
	[IssueToJob] bit NULL,
	[ItemCode] nvarchar(4000) NULL,
	[ItemDesc] nvarchar(4000) NULL,
	[ItemGroupCode] nvarchar(4000) NULL,
	[ItemShortDesc] nvarchar(4000) NULL,
	[ItemStatusCode] nvarchar(4000) NULL,
	[ItemTypeCode] nvarchar(4000) NULL,
	[JDFColourCode] nvarchar(4000) NULL,
	[Jobroundqty] decimal(18, 0) NULL,
	[LastUpdatedDateTime] nvarchar(4000) NULL,
	[LastUserCode] nvarchar(4000) NULL,
	[LeadTime] int NULL,
	[Length] decimal(18, 0) NULL,
	[MinimumChargeQty] decimal(18, 0) NULL,
	[MinimumChargeUnit] nvarchar(4000) NULL,
	[MinimumInvQty] decimal(18, 0) NULL,
	[MinorProductGroup] nvarchar(4000) NULL,
	[MRPDemandPeriod] int NULL,
	[MRPIncrementQty] decimal(18, 0) NULL,
	[MRPItem] bit NULL,
	[MRPMaxInvQty] decimal(18, 0) NULL,
	[MRPMaxProdQty] decimal(18, 0) NULL,
	[MRPMinProdQty] decimal(18, 0) NULL,
	[MRPProcessLevel] int NULL,
	[MRPReplenishType] int NULL,
	[OutsideDiam] decimal(18, 0) NULL,
	[PerLayer] int NULL,
	[PerPack] int NULL,
	[PrimaryEstimateCode] nvarchar(4000) NULL,
	[ProdGroupCode] nvarchar(4000) NULL,
	[Produced] bit NULL,
	[Purchased] bit NULL,
	[PurchasePriceCode] nvarchar(4000) NULL,
	[ReOrderQty] decimal(18, 0) NULL,
	[ReqGroupCode] nvarchar(4000) NULL,
	[RollType] int NULL,
	[StandardSizes] int NULL,
	[StdRollLength] decimal(18, 0) NULL,
	[StyleCode] nvarchar(4000) NULL,
	[TableRecId] bigint NULL,
	[UnitCode] nvarchar(4000) NULL,
	[UnitStandard] int NULL,
	[Width] decimal(18, 0) NULL
) 