CREATE TABLE [dbo].[PV_ItemPacking]
(
	[CompNum] int NULL,
	[ItemCode] nvarchar(4000) NULL,
	[PackType] int NULL,
	[Pallets] bit NULL,
	[PalletMethod] int NULL,
	[PalletUnitQty] decimal(18, 0) NULL,
	[PalletVar] int NULL,
	[Outers] bit NULL,
	[OuterMethod] int NULL,
	[OuterUnitQty] decimal(18, 0) NULL,
	[OuterVar] int NULL,
	[Wickets] bit NULL,
	[WicketMethod] int NULL,
	[WicketUnitQty] int NULL,
	[WicketVar] int NULL,
	[WicketHoleDiam] decimal(18, 0) NULL,
	[WicketPosition] decimal(18, 0) NULL,
	[MaxRollDiam] decimal(18, 0) NULL,
	[RollCalcMethod] int NULL,
	[RollRepeats] int NULL,
	[NumOnRepeat] int NULL,
	[RollProducts] int NULL,
	[RollLenght] decimal(18, 0) NULL,
	[RollArea] decimal(18, 0) NULL,
	[RollWeight] decimal(18, 0) NULL,
	[WindCodeFront] int NULL,
	[WindCodeBack] int NULL,
	[Splice] nvarchar(4000) NULL,
	[MaxSplice] int NULL,
	[NumAcross] int NULL,
	[NumDown] int NULL,
	[StackSheets] int NULL,
	[PerLayer] int NULL,
	[TableRecId] bigint NULL,
	[LastUserCode] nvarchar(4000) NULL,
	[DefaultQty] decimal(18, 0) NULL,
	[SetNumberBy] int NULL,
	[UnitDimA] decimal(18, 0) NULL,
	[UnitDimB] decimal(18, 0) NULL,
	[UnitDimC] decimal(18, 0) NULL,
	[UnitMaxStack] int NULL,
	[Weight] decimal(18, 0) NULL
)