CREATE TABLE [dbo].[PV_Inventory]
(
	[PlantCode] nvarchar(4000) NULL,
	[ItemCode] nvarchar(4000) NULL,
	[ReceiptId] bigint NULL,
	[InventoryQty] decimal(18, 0) NULL,
	[ReservedQty] decimal(18, 0) NULL,
	[WhouseCode] nvarchar(4000) NULL,
	[TableRecId] bigint NULL,
	[LastUserCode] nvarchar(4000) NULL,
	[RackCode] nvarchar(4000) NULL,
	[RowCode] nvarchar(4000) NULL,
	[BinCode] nvarchar(4000) NULL,
	[POrderNum] int NULL,
	[POrderLineNum] int NULL,
	[InventoryDate] datetime NULL,
	[DimA] decimal(18, 0) NULL,
	[DimB] decimal(18, 0) NULL,
	[InventoryValue] decimal(18, 0) NULL,
	[ReservedValue] decimal(18, 0) NULL,
	[PriceUnitCode] nvarchar(4000) NULL,
	[UnitPrice] decimal(18, 0) NULL,
	[PriceUnitConv] decimal(18, 0) NULL,
	[Quarantined] bit NULL,
	[InvStatus] int NULL,
	[CompNum] int NULL,
	[JobCode] nvarchar(4000) NULL,
	[JobLineNum] int NULL,
	[FreeQty] decimal(18, 0) NULL,
	[FreeValue] decimal(18, 0) NULL,
	[DimC] decimal(18, 0) NULL,
	[SourcePlantCode] nvarchar(4000) NULL,
	[LastUpdatedDateTime] nvarchar(4000) NULL,
	[InventoryRef] nvarchar(4000) NULL
)