CREATE TABLE [dbo].[PV_JobStep]
(
	[CompNum] int NULL,
	[PlantCode] nvarchar(4000) NULL,
	[JobCode] nvarchar(4000) NULL,
	[StepNum] int NULL,
	[StepType] int NULL,
	[TableRecId] bigint NULL,
	[StepDescrip] nvarchar(4000) NULL,
	[WorkcCode] nvarchar(4000) NULL,
	[ItemCode] nvarchar(4000) NULL,
	[DimA] decimal(18, 0) NULL,
	[DimB] decimal(18, 0) NULL,
	[est-cmp-no] int NULL,
	[est-route-seq] int NULL,
	[UnitCost] decimal(18, 0) NULL,
	[StepStatus] int NULL,
	[DimC] decimal(18, 0) NULL,
	[CmpType] int NULL,
	[EstCompDesc] nvarchar(4000) NULL,
	[PlanStartDate] datetime NULL,
	[PlanStartTime] int NULL,
	[WorkcTypeCode] nvarchar(4000) NULL,
	[NumberUp] int NULL,
	[InputQty] decimal(18, 0) NULL,
	[VRType] int NULL,
	[JobLineNum] int NULL,
	[ScrapQty] decimal(18, 0) NULL,
	[OutputQty] decimal(18, 0) NULL,
	[ProdUnit] int NULL,
	[NumPrintChanges] int NULL,
	[JobCmpNum] int NULL,
	[LabourSecs] int NULL,
	[LabTime] decimal(18, 0) NULL,
	[PlanWorkcCode] nvarchar(4000) NULL,
	[RollLength] int NULL,
	[PlanEndDate] datetime NULL,
	[PlanEndTime] int NULL,
	[LastUpdatedDateTime] nvarchar(4000) NULL,
	[ProdStartStatus] int NULL,
	[LabStepNum] int NULL
) 