CREATE TABLE [dbo].[PV_Job]
(
	[PlantCode] nvarchar(4000) NULL,
	[JobCode] nvarchar(4000) NULL,
	[JobName] nvarchar(4000) NULL,
	[TableRecId] bigint NULL,
	[LastUserCode] nvarchar(4000) NULL,
	[JobStatus] int NULL,
	[StatusCode] nvarchar(4000) NULL,
	[CompNum] int NULL,
	[EstTotalCost] decimal(18, 0) NULL,
	[ActTotalCost] decimal(18, 0) NULL,
	[EstTotalRev] decimal(18, 0) NULL,
	[ActTotalRev] decimal(18, 0) NULL,
	[est-k-seq] int NULL,
	[EstCode] nvarchar(4000) NULL,
	[PlannedAvailDate] datetime NULL,
	[ProductionStatus] int NULL,
	[ToolChange] bit NULL,
	[CylindersAvail] bit NULL,
	[EmbossCutAvail] bit NULL,
	[EmbossCutDue] datetime NULL,
	[CylindersDue] datetime NULL,
	[PlannedStartDate] datetime NULL,
	[ProdGroupCode] nvarchar(4000) NULL,
	[CustCode] nvarchar(4000) NULL,
	[JobType] int NULL,
	[ProdCompDate] datetime NULL,
	[ProdComplete] bit NULL,
	[PreviousJobCode] nvarchar(4000) NULL,
	[CompletedDate] datetime NULL,
	[MinorProductGroup] nvarchar(4000) NULL,
	[PrePress] bit NULL,
	[SOHandlingCharges] int NULL,
	[PromisedDate] datetime NULL,
	[PlannedFinishDate] datetime NULL,
	[ReqHaveReadyDate] datetime NULL,
	[ToolIssue] int NULL,
	[ActMaterialCost] decimal(18, 0) NULL,
	[ActLabourCost] decimal(18, 0) NULL,
	[ActOtherCost] decimal(18, 0) NULL,
	[ActOutworkCost] decimal(18, 0) NULL,
	[DeliveredQty] int NULL,
	[JobText] nvarchar(4000) NULL,
	[JobCreateDate] datetime NULL,
	[MRPWhouseCode] nvarchar(4000) NULL,
	[WhouseCode] nvarchar(4000) NULL,
	[LastUpdatedDateTime] nvarchar(4000) NULL,
	[PFExported] bit NULL,
	[ProdStartStatus] int NULL,
	[PFExportMode] int NULL,
	[ClosedDate] datetime NULL,
	[CustomerPO] nvarchar(4000) NULL,
	[ShipExact] bit NULL
)