CREATE TABLE [dbo].[PV_JobLine]
(
	[PlantCode] nvarchar(4000) NULL,
	[JobCode] nvarchar(4000) NULL,
	[TableRecId] bigint NULL,
	[LastUserCode] nvarchar(4000) NULL,
	[JobLineNum] int NULL,
	[ItemCode] nvarchar(4000) NULL,
	[OrderedQty] decimal(18, 0) NULL,
	[JobLineText] nvarchar(4000) NULL,
	[PlannedAvailDate] datetime NULL,
	[CompNum] int NULL,
	[DimB] decimal(18, 0) NULL,
	[DimA] decimal(18, 0) NULL,
	[ReceivedQty] decimal(18, 0) NULL,
	[ReservedQty] decimal(18, 0) NULL,
	[ReturnQty] decimal(18, 0) NULL,
	[UnitPrice] decimal(18, 0) NULL,
	[PriceUnitCode] nvarchar(4000) NULL,
	[PriceUnitConv] decimal(18, 0) NULL,
	[OrderedValue] decimal(18, 0) NULL,
	[ReceivedValue] decimal(18, 0) NULL,
	[ReservedValue] decimal(18, 0) NULL,
	[ReturnValue] decimal(18, 0) NULL,
	[InvQty] decimal(18, 0) NULL,
	[InvResQty] decimal(18, 0) NULL,
	[InvValue] decimal(18, 0) NULL,
	[InvResValue] decimal(18, 0) NULL,
	[ShortfallQty] decimal(18, 0) NULL,
	[ShortfallValue] decimal(18, 0) NULL,
	[FreeQty] decimal(18, 0) NULL,
	[FreeValue] decimal(18, 0) NULL,
	[QuarantineQty] decimal(18, 0) NULL,
	[QuarantineValue] decimal(18, 0) NULL,
	[InvFreeQty] decimal(18, 0) NULL,
	[InvFreeValue] decimal(18, 0) NULL,
	[OutstandingQty] decimal(18, 0) NULL,
	[OutstandingValue] decimal(18, 0) NULL,
	[SOPlantCode] nvarchar(4000) NULL,
	[SOrderNum] int NULL,
	[SOrderLineNum] int NULL,
	[PreShipBillQty] decimal(18, 0) NULL,
	[PreShipBillValue] decimal(18, 0) NULL,
	[DimC] decimal(18, 0) NULL,
	[JobLineStatus] int NULL,
	[PackType] int NULL,
	[ProfileCompNum] int NULL,
	[LastUpdatedDateTime] nvarchar(4000) NULL
) 