CREATE TABLE [dbo].[PV_POrderLine]
(
	[PlantCode] nvarchar(4000) NULL,
	[POrderNum] int NULL,
	[POrderLineNum] int NULL,
	[ItemCode] nvarchar(4000) NULL,
	[ReqDate] datetime NULL,
	[WhouseCode] nvarchar(4000) NULL,
	[POrderLineText] nvarchar(4000) NULL,
	[OrderedQty] decimal(18, 0) NULL,
	[Suppcode] nvarchar(4000) NULL,
	[TableRecId] bigint NULL,
	[LastUserCode] nvarchar(4000) NULL,
	[ReceivedQty] decimal(18, 0) NULL,
	[ReservedQty] decimal(18, 0) NULL,
	[PriceUnitCode] nvarchar(4000) NULL,
	[UnitPrice] decimal(18, 0) NULL,
	[FreightCost] decimal(18, 0) NULL,
	[DimA] decimal(18, 0) NULL,
	[DimB] decimal(18, 0) NULL,
	[OrderedValue] decimal(18, 0) NULL,
	[ReceivedValue] decimal(18, 0) NULL,
	[ReservedValue] decimal(18, 0) NULL,
	[PriceGroupNo] int NULL,
	[PriceUnitConv] decimal(18, 0) NULL,
	[ShortfallQty] decimal(18, 0) NULL,
	[ShortfallValue] decimal(18, 0) NULL,
	[ReturnQty] decimal(18, 0) NULL,
	[ReturnValue] decimal(18, 0) NULL,
	[OutstandingQty] decimal(18, 0) NULL,
	[OutstandingValue] decimal(18, 0) NULL,
	[InvQty] decimal(18, 0) NULL,
	[InvResQty] decimal(18, 0) NULL,
	[InvValue] decimal(18, 0) NULL,
	[InvResValue] decimal(18, 0) NULL,
	[SuppItemRef] nvarchar(4000) NULL,
	[CompNum] int NULL,
	[FreeQty] decimal(18, 0) NULL,
	[QuarantineQty] decimal(18, 0) NULL,
	[QuarantineValue] decimal(18, 0) NULL,
	[InvFreeQty] decimal(18, 0) NULL,
	[InvFreeValue] decimal(18, 0) NULL,
	[FreeValue] decimal(18, 0) NULL,
	[DimC] decimal(18, 0) NULL,
	[ConfDelivDate] datetime NULL,
	[AvailShipDate] datetime NULL,
	[POLineStatus] int NULL,
	[LastUpdatedDateTime] nvarchar(4000) NULL
)