CREATE TABLE [dbo].[PV_Req]
(
	[TableRecId] bigint NULL,
	[LastUserCode] nvarchar(4000) NULL,
	[ItemCode] nvarchar(4000) NULL,
	[PlantCode] nvarchar(4000) NULL,
	[RequiredQty] decimal(18, 0) NULL,
	[JobCode] nvarchar(4000) NULL,
	[RequirementId] bigint NULL,
	[InvResQty] decimal(18, 0) NULL,
	[IssuedQty] decimal(18, 0) NULL,
	[POResQty] decimal(18, 0) NULL,
	[RequiredDate] datetime NULL,
	[IssReturnQty] decimal(18, 0) NULL,
	[DimA] decimal(18, 0) NULL,
	[DimB] decimal(18, 0) NULL,
	[ReqStatus] int NULL,
	[ItemGroupCode] nvarchar(4000) NULL,
	[ReqGroupCode] nvarchar(4000) NULL,
	[SOPlantCode] nvarchar(4000) NULL,
	[SOrderNum] int NULL,
	[SOrderLineNum] int NULL,
	[ReqType] int NULL,
	[ShippedQty] decimal(18, 0) NULL,
	[InProdResQty] decimal(18, 0) NULL,
	[ShipReturnQty] decimal(18, 0) NULL,
	[DimC] decimal(18, 0) NULL,
	[HaveReadyDate] datetime NULL,
	[CompNum] int NULL,
	[UnplannedQty] decimal(18, 0) NULL,
	[StepNum] int NULL,
	[FreeStockAvailDate] datetime NULL,
	[ReqDescrip] nvarchar(4000) NULL,
	[FromFreeStock] bit NULL,
	[FreeStockCalcDate] datetime NULL,
	[PlannedStartDate] datetime NULL,
	[WhouseCode] nvarchar(4000) NULL,
	[PlannedStartTime] int NULL,
	[QtyWaitingPick] decimal(18, 0) NULL,
	[QtyWaitingIssue] decimal(18, 0) NULL,
	[LastUpdatedDateTime] nvarchar(4000) NULL,
	[POTBCOQty] decimal(18, 0) NULL,
	[POCOQty] decimal(18, 0) NULL,
	[NonCOQty] decimal(18, 0) NULL,
	[FreeStockProcessed] int NULL,
	[CustCode] nvarchar(4000) NULL,
	[CustomerPO] nvarchar(4000) NULL,
	[EndUserPO] nvarchar(4000) NULL,
	[ReqText] nvarchar(4000) NULL
) 