CREATE TABLE [dbo].[PV_ShipReq]
(
	[CompNum] int NULL,
	[PlantCode] nvarchar(4000) NULL,
	[ShipReqNum] int NULL,
	[CustCode] nvarchar(4000) NULL,
	[ShipDate] datetime NULL,
	[ShipTimeSecs] int NULL,
	[ShipReqStat] int NULL,
	[TableRecId] bigint NULL,
	[LastUserCode] nvarchar(4000) NULL,
	[ShipReqText] nvarchar(4000) NULL,
	[PickStatus] int NULL,
	[ShipTime] nvarchar(4000) NULL,
	[BOLNum] int NULL,
	[BillAddrNum] int NULL,
	[ShipAddrNum] int NULL,
	[ActualShipDate] datetime NULL,
	[ActualShipTime] nvarchar(4000) NULL,
	[ActualShipTimeSecs] int NULL,
	[BillDisplayAddress] nvarchar(4000) NULL,
	[ShipDisplayAddress] nvarchar(4000) NULL,
	[PrintStatus] int NULL,
	[DeliveryTerms] nvarchar(4000) NULL,
	[EstArrivalTime] nvarchar(4000) NULL,
	[EstArrivalTimeSecs] int NULL,
	[EstArrivalDate] datetime NULL,
	[CarrierCode] nvarchar(4000) NULL,
	[Priority] int NULL,
	[CustContactCode] nvarchar(4000) NULL,
	[EstArrivalDaysPrior] int NULL,
	[ShipDaysPrior] int NULL,
	[GrossQty] decimal(18, 0) NULL,
	[NettQty] decimal(18, 0) NULL,
	[CreationDate] datetime NULL,
	[CreationTimeSecs] int NULL,
	[CreationTime] nvarchar(4000) NULL,
	[CreatedByUserCode] nvarchar(4000) NULL,
	[ActualDelDate] datetime NULL,
	[LastUpdatedDateTime] nvarchar(4000) NULL
) 