CREATE TABLE [dbo].[PV_ShipReqLine]
(
	[CompNum] int NULL,
	[PlantCode] nvarchar(4000) NULL,
	[ShipReqNum] int NULL,
	[ShipReqLineNum] int NULL,
	[SOPlantCode] nvarchar(4000) NULL,
	[SOrderNum] int NULL,
	[SOrderLineNum] int NULL,
	[ItemCode] nvarchar(4000) NULL,
	[ShipReqLineText] nvarchar(4000) NULL,
	[ShipQty] decimal(18, 0) NULL,
	[DimA] decimal(18, 0) NULL,
	[DimB] decimal(18, 0) NULL,
	[TableRecId] bigint NULL,
	[RequirementId] bigint NULL,
	[PickedQty] decimal(18, 0) NULL,
	[DimC] decimal(18, 0) NULL,
	[ReturnQty] decimal(18, 0) NULL,
	[ReturnableQty] decimal(18, 0) NULL,
	[BillNum] int NULL,
	[BillLineNum] int NULL,
	[ShippingRef] nvarchar(4000) NULL,
	[ContactCode] nvarchar(4000) NULL,
	[PostCode] nvarchar(4000) NULL,
	[GrossQty] decimal(18, 0) NULL,
	[NettQty] decimal(18, 0) NULL,
	[OnTimeDate] datetime NULL,
	[LastUpdatedDateTime] nvarchar(4000) NULL
)