CREATE TABLE [dbo].[PV_SOrderLine]
(
	[PlantCode] nvarchar(4000) NULL,
	[SOrderNum] int NULL,
	[SOrderLineNum] int NULL,
	[ItemCode] nvarchar(4000) NULL,
	[ReqDate] datetime NULL,
	[CustItemRef] nvarchar(4000) NULL,
	[SOrderLineText] nvarchar(4000) NULL,
	[OrderedQty] decimal(18, 0) NULL,
	[ShippedQty] decimal(18, 0) NULL,
	[ReturnQty] decimal(18, 0) NULL,
	[OutstandingQty] decimal(18, 0) NULL,
	[OrderUnitCode] nvarchar(4000) NULL,
	[TableRecId] bigint NULL,
	[LastUserCode] nvarchar(4000) NULL,
	[DimA] decimal(18, 0) NULL,
	[DimB] decimal(18, 0) NULL,
	[CompNum] int NULL,
	[PriceUnitCode] nvarchar(4000) NULL,
	[InvResQty] decimal(18, 0) NULL,
	[ShipQty] decimal(18, 0) NULL,
	[DimC] decimal(18, 0) NULL,
	[BillQty] decimal(18, 0) NULL,
	[BillValue] decimal(18, 0) NULL,
	[ShipValue] decimal(18, 0) NULL,
	[ShippedValue] decimal(18, 0) NULL,
	[ReturnValue] decimal(18, 0) NULL,
	[OutstandingValue] decimal(18, 0) NULL,
	[InvResValue] decimal(18, 0) NULL,
	[OrderedValue] decimal(18, 0) NULL,
	[UnitPrice] decimal(18, 0) NULL,
	[OtherIncome] bit NULL,
	[ShortfallValue] decimal(18, 0) NULL,
	[ShortfallQty] decimal(18, 0) NULL,
	[HaveReadyDate] datetime NULL,
	[OversPercent] decimal(18, 0) NULL,
	[SOItemTypeCode] nvarchar(4000) NULL,
	[UndersPercent] decimal(18, 0) NULL,
	[UnitCostPrice] decimal(18, 0) NULL,
	[CustPOLineNum] int NULL,
	[SalesPriceCode] nvarchar(4000) NULL,
	[SalesPriceQuantity] decimal(18, 0) NULL,
	[SalesPriceType] int NULL,
	[Completed] int NULL,
	[CustPOLineRef] nvarchar(4000) NULL,
	[StandardPrice] decimal(18, 0) NULL,
	[StandardPriceIndex] decimal(18, 0) NULL,
	[BasePrice] decimal(18, 0) NULL,
	[LastUpdatedDateTime] nvarchar(4000) NULL
) 