CREATE TABLE [dbo].[PV_ToolSpec]
(
	[CompNum] int NULL,
	[TableRecId] bigint NULL,
	[LastUserCode] nvarchar(4000) NULL,
	[SpecCode] nvarchar(4000) NULL,
	[SpecName] nvarchar(4000) NULL,
	[ToolTypeCode] nvarchar(4000) NULL,
	[DieType] int NULL,
	[PressType] nvarchar(4000) NULL,
	[GearCode] nvarchar(4000) NULL,
	[Teeth] int NULL,
	[SizeAcross] decimal(18, 0) NULL,
	[SizeDown] decimal(18, 0) NULL,
	[GapAcross] decimal(18, 0) NULL,
	[GapDown] decimal(18, 0) NULL,
	[RepeatGap] decimal(18, 0) NULL,
	[MinWidth] decimal(18, 0) NULL,
	[MinDepth] decimal(18, 0) NULL,
	[Layout] nvarchar(4000) NULL,
	[Drawing] nvarchar(4000) NULL,
	[ApprovalStatus] int NULL,
	[ApprovedBy] nvarchar(4000) NULL,
	[ApprovedDate] datetime NULL,
	[CustCode] nvarchar(4000) NULL,
	[StreamsNoAcross] int NULL,
	[Streams] int NULL,
	[CutSheet] int NULL,
	[CutsheetDimA] decimal(18, 0) NULL,
	[CutsheetDimB] decimal(18, 0) NULL,
	[Geometry] decimal(18, 0) NULL,
	[CutLength] decimal(18, 0) NULL,
	[PressSize] decimal(18, 0) NULL,
	[NumberUp] int NULL,
	[LinerWeight] nvarchar(4000) NULL,
	[CutterType] nvarchar(4000) NULL,
	[Shape] nvarchar(4000) NULL,
	[SteelTypeCode] nvarchar(4000) NULL,
	[CornerRadius] decimal(18, 0) NULL,
	[CornerNumber] int NULL,
	[NumberAcross] decimal(18, 0) NULL,
	[NumberDown] decimal(18, 0) NULL,
	[caliper] decimal(18, 0) NULL,
	[GearType] int NULL,
	[GearLocation] int NULL,
	[NumberofBearers] int NULL,
	[NumberofGears] int NULL,
	[CylinderType] int NULL,
	[CaliperMin] decimal(18, 0) NULL,
	[CaliperMax] decimal(18, 0) NULL,
	[NumberDownPrint] int NULL,
	[MarginRight] decimal(18, 0) NULL,
	[MarginLeft] decimal(18, 0) NULL,
	[VarnishType] nvarchar(4000) NULL,
	[CorDimB] decimal(18, 0) NULL,
	[CorDimC] decimal(18, 0) NULL,
	[CorBlankDimA] decimal(18, 0) NULL,
	[CorBlankDimB] decimal(18, 0) NULL,
	[PlantList] nvarchar(4000) NULL,
	[LastUpdatedDateTime] nvarchar(4000) NULL,
	[PFRequired] int NULL
)