CREATE TABLE [dbo].[PV_WorkcConfigOption](
	[CompNum] [int] NULL,
	[TableRecId] [int] NULL,
	[LastUserCode] [nvarchar](4000) NULL,
	[WorkcCode] [nvarchar](4000) NULL,
	[ConfigNum] [int] NULL,
	[OptionNum] [int] NULL,
	[OptionName] [nvarchar](4000) NULL,
	[autoInclude] [bit] NULL,
	[MRRun] [int] NULL,
	[OptionTime] [int] NULL,
	[OptionPer] [int] NULL,
	[OptionProRated] [bit] NULL,
	[OptionTimeVar] [int] NULL,
	[MRWasteType] [bit] NULL,
	[MRWasteQty] [int] NULL,
	[MRWasteVar] [int] NULL,
	[RunWasteType] [bit] NULL,
	[RunWastePerc] [decimal](18, 4) NULL,
	[RunWasteVar] [int] NULL,
	[SpeedType] [bit] NULL,
	[SpeedReductionPerc] [decimal](18, 4) NULL,
	[MultiplyType] [bit] NULL,
	[SpeedReductionVar] [int] NULL,
	[MultipleVar] [int] NULL,
	[DefaultValue] [int] NULL,
	[MinMultipleValue] [int] NULL,
	[MaxMultipleValue] [int] NULL,
	[ClickCharge] [decimal](18, 4) NULL,
	[PFIncludeMRTime] [bit] NULL
) ON [PRIMARY]

