CREATE TABLE [dbo].[sfeventcds]
(
	[kco] int NULL,
	[kjobcode] nvarchar(4000) NULL,
	[kcompno] int NULL,
	[seq-code] int NULL,
	[mach-id] nvarchar(4000) NULL,
	[stat-code] nvarchar(4000) NULL,
	[op-code] nvarchar(4000) NULL,
	[start-time] int NULL,
	[elapse-time] int NULL,
	[shift-code] int NULL,
	[extract-flag] int NULL,
	[non-prod-flag] nvarchar(4000) NULL,
	[seq-code2] int NULL,
	[overtime-flag] int NULL,
	[kprocno] int NULL,
	[history-flag] int NULL,
	[formno] int NULL,
	[event-type] nvarchar(4000) NULL,
	[substat-init] nvarchar(4000) NULL,
	[substat-final] nvarchar(4000) NULL,
	[end-time] int NULL,
	[amended] int NULL,
	[ass-no] int NULL,
	[group-code] nvarchar(4000) NULL,
	[seq-num] int NULL,
	[sub-type] nvarchar(4000) NULL,
	[comment-flag] int NULL,
	[group-ind] int NULL,
	[PlantCode] nvarchar(4000) NULL,
	[event-qty] decimal(18, 0) NULL,
	[misc-qty] decimal(18, 0) NULL,
	[sundry-qty] decimal(18, 0) NULL,
	[JobPositionID] int NULL,
	[DroolWasteWeight] decimal(18, 0) NULL,
	[MixNumber] int NULL,
	[ResinIssued] int NULL,
	[DataOrigin] int NULL,
	[EventID] nvarchar(4000) NULL,
	[scrap-qty] decimal(18, 0) NULL,
	[clickchargeqty] decimal(18, 0) NULL,
	[LastUpdatedDateTime] nvarchar(4000) NULL
) 