CREATE TABLE [wi-options] (
	[kco] int DEFAULT 0 NOT NULL,
	[wiopt-amend-prod-narr] bit DEFAULT 1,
	[wiopt-amend-var-narr] bit DEFAULT 1,
	[wiopt-amend-cmp-narr] bit DEFAULT 1,
	[wiopt-amend-item] bit DEFAULT 1,
	[wiopt-prod-narr-use] int DEFAULT 0,
	[wiopt-cmp-narr-use] int DEFAULT 0,
	[wiopt-item-coat] bit DEFAULT 1,
	[wiopt-sundry] bit DEFAULT 1,
	[wiopt-amend-pack-narr] bit DEFAULT 1,
	[wiopt-amend-wc-narr] bit DEFAULT 1,
	[wiopt-cust-contacts] bit DEFAULT 0,
	[wiopt-contact-home-phone] bit DEFAULT 0,
	[wiopt-int-contact-lab] varchar(30),
	[wiopt-labour] bit DEFAULT 1,
	[wiopt-pack-last-dept] bit DEFAULT 1,
	[wiopt-reserved-mat] bit DEFAULT 1,
	[wiopt-film-ref] bit DEFAULT 1,
	[wiopt-alloc-cyl] bit DEFAULT 1,
	[wiopt-amend-coating] bit DEFAULT 0,
	[wiopt-tools]bit DEFAULT 0,
	[wiopt-view-print] bit DEFAULT 1
);