CREATE TABLE [dbo].[wi-profile]
(
	[wi-p-qty] int NULL,
	[k-profile] nvarchar(4000) NULL,
	[wi-p-ref] nvarchar(4000) NULL,
	[wi-p-style] nvarchar(4000) NULL,
	[wi-p-dima] decimal(18, 0) NULL,
	[wi-p-dimb] decimal(18, 0) NULL,
	[wi-p-dimc] decimal(18, 0) NULL,
	[wi-p-Outer] decimal(18, 0) NULL,
	[wi-p-Inner] decimal(18, 0) NULL,
	[wi-p-blank-w] decimal(18, 0) NULL,
	[wi-p-blank-l] decimal(18, 0) NULL,
	[k-est-code] nvarchar(4000) NULL,
	[kco] int NULL,
	[wi-p-laminated] bit NULL,
	[wi-p-embossed] bit NULL,
	[k-cmp-no] int NULL,
	[wi-p-trim-left] decimal(18, 0) NULL,
	[wi-p-trim-right] decimal(18, 0) NULL,
	[wi-p-folds-down] int NULL,
	[wi-p-folds-across] int NULL,
	[wi-p-style-desc] nvarchar(4000) NULL,
	[wi-p-packing] bit NULL,
	[wi-p-trim-top] decimal(18, 0) NULL,
	[wi-p-trim-bottom] decimal(18, 0) NULL,
	[wi-p-label-shape] nvarchar(4000) NULL,
	[wi-master-profile] nvarchar(4000) NULL,
	[wi-p-flex-lip] decimal(18, 0) NULL,
	[wi-p-flex-gusset] decimal(18, 0) NULL,
	[wi-p-flex-glue] decimal(18, 0) NULL,
	[wi-p-guttera] decimal(18, 0) NULL,
	[wi-p-gutterb] decimal(18, 0) NULL,
	[wi-p-coating-face] bit NULL,
	[wi-p-coating-reverse] bit NULL,
	[wi-p-reverse-print] bit NULL,
	[wi-p-metric] bit NULL,
	[wi-p-number-up] int NULL,
	[korder] nvarchar(4000) NULL,
	[wi-p-sub-component] bit NULL,
	[wi-p-pinfeed] bit NULL,
	[wi-p-pinfeed-dim] decimal(18, 0) NULL,
	[wi-p-no-kinds] int NULL,
	[wi-p-layer-pallet] int NULL,
	[wi-p-Inner2] decimal(18, 0) NULL,
	[wi-p-lock-on-tuck2] decimal(18, 0) NULL,
	[wi-p-Outer2] decimal(18, 0) NULL,
	[wi-p-outers-layer] int NULL,
	[wi-p-profile-seq] int NULL,
	[wi-p-lining-l] decimal(18, 0) NULL,
	[wi-p-lining-w] decimal(18, 0) NULL,
	[wi-p-comp-type] int NULL,
	[wi-p-folds] int NULL,
	[FinishAs] int NULL,
	[RollType] int NULL,
	[SALFinishAS] int NULL,
	[SALProductType] int NULL,
	[SALDeliveredWidth] decimal(18, 0) NULL,
	[SALNumAcrossStream] int NULL,
	[SALNumOnSheet] int NULL,
	[SALSheetAcross] decimal(18, 0) NULL,
	[SALSheetDown] decimal(18, 0) NULL,
	[SALMarginLeft] decimal(18, 0) NULL,
	[SALMarginRight] decimal(18, 0) NULL,
	[SALLinerWidth] decimal(18, 0) NULL,
	[SALNumDownFold] int NULL,
	[CornerNumber] int NULL,
	[CornerRadius] decimal(18, 0) NULL,
	[LengthTrim] decimal(18, 0) NULL,
	[WidthTrim] decimal(18, 0) NULL,
	[TableRecId] bigint NULL
)