CREATE TABLE [dbo].[wi-pack](
	[kco] integer NULL,
	[k-wi-pack-rec-no] integer NULL,
	[k-cmp-no] integer NULL,
	[item-code] nvarchar(4000) NULL,
	[k-edition] integer NULL,
	[wi-pack-type] integer NULL,
	[wi-pack-pallets] bit NULL,
	[wi-pack-pallet-method] integer NULL,
	[wi-pack-pallet-qty] integer NULL,
	[wi-pack-pallet-var] integer NULL,
	[wi-pack-outers] bit NULL,
	[wi-pack-outer-method] integer NULL,
	[wi-pack-outer-qty] integer NULL,
	[wi-pack-outer-var] integer NULL,
	[wi-pack-maxdiam] decimal(18, 0) NULL,
	[wi-pack-calc-method] nvarchar(4000) NULL,
	[wi-pack-diameter] decimal(18, 0) NULL,
	[wi-pack-repeat] integer NULL,
	[wi-pack-length] decimal(18, 0) NULL,
	[wi-pack-area] decimal(18, 0) NULL,
	[wi-pack-weight] decimal(18, 0) NULL,
	[wi-pack-no-across] integer NULL,
	[wi-pack-items-roll] decimal(18, 0) NULL,
	[korder] nvarchar(4000) NULL,
	[wi-pack-rolls-layer] integer NULL,
	[wi-pack-layers-pallet] integer NULL
)

