CREATE TABLE [dbo].[AssociateTemp] (
   	[PK_UUID] NVARCHAR(4000),
	[NUMBER] NVARCHAR(4000) NULL,
	[FIRSTNAME] NVARCHAR(4000) NULL,
	[LASTNAME] NVARCHAR(4000) NULL,
	[E_MAIL_ADDRESS] NVARCHAR(4000) NULL,
	[PHONE] NVARCHAR(4000) NULL,
	[INACTIVE] BIT NULL,
	[PURCHASEBTN] INT NULL,
	[HashValue] VARBINARY(32) NULL
);