CREATE TABLE [dbo].[Customer] (
    [Number]                        NVARCHAR (4000) NULL,
    [Company]                       NVARCHAR (4000) NULL,
    [Source]                        NVARCHAR (4000) NULL,
    [OrderReq]                      NVARCHAR (4000) NULL,
    [CreditStatus]                  BIT             NULL,
    [DistributorNum]                NVARCHAR (4000) NULL,
    [MFGRepNum]                     NVARCHAR (4000) NULL,
    [Notes]                         NVARCHAR (4000) NULL,
    [Phone]                         NVARCHAR (4000) NULL,
    [Fax]                           NVARCHAR (4000) NULL,
    [NextCallDate]                  DATETIME        NULL,
    [Sales_Rep_No]                  NVARCHAR (4000) NULL,
    [Cust_Serv_No]                  NVARCHAR (4000) NULL,
    [SICNum]                        NVARCHAR (4000) NULL,
    [Customer]                      BIT             NULL,
    [Distributor]                   BIT             NULL,
    [Receptionist]                  NVARCHAR (4000) NULL,
    [LastEstimateDat]               DATETIME        NULL,
    [TotalEstimates]                INT             NULL,
    [LastTicketDate]                DATETIME        NULL,
    [TotalTickets]                  INT             NULL,
    [TotalSales]                    REAL            NULL,
    [TotalYTDSales]                 REAL            NULL,
    [Web_Password]                  NVARCHAR (4000) NULL,
    [Web_Enable_Login]              BIT             NULL,
    [Days90]                        REAL            NULL,
    [TaxExempt_SalesTax]            BIT             NULL,
    [TaxRate]                       REAL            NULL,
    [DateOpened]                    DATETIME        NULL,
    [AveDaysPaid]                   SMALLINT        NULL,
    [CurrentBalance]                REAL            NULL,
    [Terms]                         NVARCHAR (4000) NULL,
    [TotalLYSales]                  REAL            NULL,
    [OTSName]                       NVARCHAR (4000) NULL,
    [ITSName]                       NVARCHAR (4000) NULL,
    [Prosp_Customer]                BIT             NULL,
    [MFGRepComm]                    REAL            NULL,
    [DistribName]                   NVARCHAR (4000) NULL,
    [ZipCode]                       NVARCHAR (4000) NULL,
    [Territory]                     NVARCHAR (4000) NULL,
    [Area]                          NVARCHAR (4000) NULL,
    [StockProdDiscnt]               REAL            NULL,
    [StockPrdPriceGp]               NVARCHAR (4000) NULL,
    [TaxRate2]                      REAL            NULL,
    [Patched]                       DATETIME        NULL,
    [EntryDate]                     DATETIME        NULL,
    [EntryBy]                       NVARCHAR (4000) NULL,
    [ModifyDate]                    DATETIME        NULL,
    [ModifyBy]                      NVARCHAR (4000) NULL,
    [A4LinkDate]                    DATETIME        NULL,
    [SendToA4]                      NVARCHAR (4000) NULL,
    [Inactive]                      BIT             NULL,
    [URL]                           NVARCHAR (4000) NULL,
    [Converted_to_Customer]         DATETIME        NULL,
    [ProfitAdjLabel]                NVARCHAR (4000) NULL,
    [SendStatement]                 BIT             NULL,
    [TaxExemptCertificate]          NVARCHAR (4000) NULL,
    [Credit_Limit]                  REAL            NULL,
    [BudgetingNotes]                NVARCHAR (4000) NULL,
    [Internal_Customer]             BIT             NULL,
    [SoldToEndUser]                 BIT             NULL,
    [Web_Edit_Password]             NVARCHAR (4000) NULL,
    [DontPrintTermsOnPS]            BIT             NULL,
    [Overrun_YesNo]                 SMALLINT        NULL,
    [Overrun_Amt]                   REAL            NULL,
    [AutoOrder_StockProduct]        INT             NULL,
    [TexExemptCertExpire]           DATETIME        NULL,
    [TaxExemptCert_Resale]          BIT             NULL,
    [TaxExemptCert_PrintOnInv]      BIT             NULL,
    [eTraxxPrefs_x]                 VARBINARY (1)   NULL,
    [EntryTime]                     TIME (7)        NULL,
    [ModifyTime]                    TIME (7)        NULL,
    [Type_of_Customer]              NVARCHAR (4000) NULL,
    [Name1]                         NVARCHAR (4000) NULL,
    [Name2]                         NVARCHAR (4000) NULL,
    [Name3]                         NVARCHAR (4000) NULL,
    [Name4]                         NVARCHAR (4000) NULL,
    [PopUpName1]                    NVARCHAR (4000) NULL,
    [PopUpName2]                    NVARCHAR (4000) NULL,
    [CheckBoxName1]                 BIT             NULL,
    [CheckBoxName2]                 BIT             NULL,
    [MarketingNotes]                NVARCHAR (4000) NULL,
    [TraxxLink_PackSlip_Processing] INT             NULL,
    [Currency_ID]                   INT             NULL,
    [StatementAddressID]            NVARCHAR (4000) NULL,
    [Web_AllowContactLogIn]         BIT             NULL,
    [CommissionPercent]             REAL            NULL,
    [UseEmployeeCommRate]           BIT             NULL,
    [BackStage_ColorStrategy]       NVARCHAR (4000) NULL,
    [BackStage_DefaultReportForm]   NVARCHAR (4000) NULL,
    [eTraxx_Tik_StartDate]          DATETIME        NULL,
    [eTraxx_Tik_StopDate]           DATETIME        NULL,
    [eTraxx_Tik_DateStore]          INT             NULL,
    [Prefers_email_Invoice]         BIT             NULL,
    [RFC]                           NVARCHAR (4000) NULL,
    [Method_of_Payment]             NVARCHAR (4000) NULL,
    [PK_UUID]                       NVARCHAR (4000) NULL,
    [Serialnumber]                  NVARCHAR (4000) NULL,
    [AE_PrefAppMethod]              NVARCHAR (4000) NULL,
    [On_hold]                       BIT             NULL,
    [UpdateTimeDateStamp]     DATETIME        NULL
);

