CREATE TABLE [dbo].[Equipment] (
    [Number]                         NVARCHAR (450)  NOT NULL,
    [PType]                          NVARCHAR (4000) NULL,
    [MaxStockWidth]                  REAL            NULL,
    [MinStockWidth]                  REAL            NULL,
    [MaxColors]                      SMALLINT        NULL,
    [MaxTools]                       SMALLINT        NULL,
    [MaxPrintRepeat]                 REAL            NULL,
    [MinPrintRepeat]                 REAL            NULL,
    [MaxDieRepeat]                   REAL            NULL,
    [MinDieRepeat]                   REAL            NULL,
    [MaxPrintWidth]                  REAL            NULL,
    [UVCoat]                         REAL            NULL,
    [ConsecutiveNo]                  REAL            NULL,
    [Turnbar]                        REAL            NULL,
    [Sheeter]                        REAL            NULL,
    [WIP_Rate]                       REAL            NULL,
    [EstimateRate]                   REAL            NULL,
    [PrintInkCost]                   REAL            NULL,
    [FloodInkCost]                   REAL            NULL,
    [Description]                    NVARCHAR (4000) NULL,
    [Notes]                          NVARCHAR (4000) NULL,
    [MRFirstDie]                     REAL            NULL,
    [MRAdditonalDie]                 REAL            NULL,
    [MRFirstColor]                   REAL            NULL,
    [MRAdditionalCol]                REAL            NULL,
    [MRFlood]                        REAL            NULL,
    [SetupFeet]                      REAL            NULL,
    [MRStock]                        REAL            NULL,
    [WUFirstColor]                   REAL            NULL,
    [WUFloods]                       REAL            NULL,
    [WUDie]                          REAL            NULL,
    [PressSpeed1]                    SMALLINT        NULL,
    [PressSpeed2]                    SMALLINT        NULL,
    [PressSpeed3]                    SMALLINT        NULL,
    [MinPrintInk]                    REAL            NULL,
    [MinFloodInk]                    REAL            NULL,
    [PinfeedPunch]                   REAL            NULL,
    [StockSpoilL1]                   INT             NULL,
    [StockSpoilH1]                   INT             NULL,
    [StockSpoilPerc1]                REAL            NULL,
    [StockSpoilL2]                   INT             NULL,
    [StockSpoilH2]                   INT             NULL,
    [StockSpoilPerc2]                REAL            NULL,
    [StockSpoilL3]                   INT             NULL,
    [StockSpoilH3]                   INT             NULL,
    [StockSpoilPerc3]                REAL            NULL,
    [StockSpoilL4]                   INT             NULL,
    [StockSpoilH4]                   INT             NULL,
    [StockSpoilPerc4]                REAL            NULL,
    [StockSpoilL5]                   INT             NULL,
    [StockSpoilH5]                   INT             NULL,
    [StockSpoilPerc5]                REAL            NULL,
    [PressSpeed4]                    SMALLINT        NULL,
    [PressSpeed5]                    SMALLINT        NULL,
    [Inactive]                       BIT             NULL,
    [HSPlateCost]                    REAL            NULL,
    [HSStockSpoil]                   REAL            NULL,
    [HSToolCost]                     REAL            NULL,
    [ConsecutLimit]                  SMALLINT        NULL,
    [CylinderSize]                   NVARCHAR (4000) NULL,
    [CommercialJC]                   REAL            NULL,
    [DistributorJC]                  REAL            NULL,
    [PlateChangeCharge]              REAL            NULL,
    [ColorChangeCharge]              REAL            NULL,
    [ModifiedDate]                   DATETIME        NULL,
    [Pitch]                          NVARCHAR (4000) NULL,
    [PressureAngle]                  REAL            NULL,
    [StockSpoilL6]                   INT             NULL,
    [StockSpoilL7]                   INT             NULL,
    [StockSpoilL8]                   INT             NULL,
    [StockSpoilL9]                   INT             NULL,
    [StockSpoilL10]                  INT             NULL,
    [StockSpoilL11]                  INT             NULL,
    [StockSpoilL12]                  INT             NULL,
    [StockSpoilL13]                  INT             NULL,
    [StockSpoilL14]                  INT             NULL,
    [StockSpoilL15]                  INT             NULL,
    [StockSpoilL16]                  INT             NULL,
    [StockSpoilL17]                  INT             NULL,
    [StockSpoilL18]                  INT             NULL,
    [StockSpoilL19]                  INT             NULL,
    [StockSpoilL20]                  INT             NULL,
    [StockSpoilH6]                   INT             NULL,
    [StockSpoilH7]                   INT             NULL,
    [StockSpoilH8]                   INT             NULL,
    [StockSpoilH9]                   INT             NULL,
    [StockSpoilH10]                  INT             NULL,
    [StockSpoilH11]                  INT             NULL,
    [StockSpoilH12]                  INT             NULL,
    [StockSpoilH13]                  INT             NULL,
    [StockSpoilH14]                  INT             NULL,
    [StockSpoilH15]                  INT             NULL,
    [StockSpoilH16]                  INT             NULL,
    [StockSpoilH17]                  INT             NULL,
    [StockSpoilH18]                  INT             NULL,
    [StockSpoilH19]                  INT             NULL,
    [StockSpoilH20]                  INT             NULL,
    [StockSpoilPerc6]                REAL            NULL,
    [StockSpoilPerc7]                REAL            NULL,
    [StockSpoilPerc8]                REAL            NULL,
    [StockSpoilPerc9]                REAL            NULL,
    [StockSpoilPer10]                REAL            NULL,
    [StockSpoilPer11]                REAL            NULL,
    [StockSpoilPer12]                REAL            NULL,
    [StockSpoilPer13]                REAL            NULL,
    [StockSpoilPer14]                REAL            NULL,
    [StockSpoilPer15]                REAL            NULL,
    [StockSpoilPer16]                REAL            NULL,
    [StockSpoilPer17]                REAL            NULL,
    [StockSpoilPer18]                REAL            NULL,
    [StockSpoilPer19]                REAL            NULL,
    [StockSpoilPer20]                REAL            NULL,
    [PressSpeed6]                    SMALLINT        NULL,
    [PressSpeed7]                    SMALLINT        NULL,
    [PressSpeed8]                    SMALLINT        NULL,
    [PressSpeed9]                    SMALLINT        NULL,
    [PressSpeed10]                   SMALLINT        NULL,
    [PressSpeed11]                   SMALLINT        NULL,
    [PressSpeed12]                   SMALLINT        NULL,
    [PressSpeed13]                   SMALLINT        NULL,
    [PressSpeed14]                   SMALLINT        NULL,
    [PressSpeed15]                   SMALLINT        NULL,
    [PressSpeed16]                   SMALLINT        NULL,
    [PressSpeed17]                   SMALLINT        NULL,
    [PressSpeed18]                   SMALLINT        NULL,
    [PressSpeed19]                   SMALLINT        NULL,
    [PressSpeed20]                   SMALLINT        NULL,
    [ModifiedTime]                   TIME (7)        NULL,
    [PlateChgHr]                     REAL            NULL,
    [ColorChgHr]                     REAL            NULL,
    [MachineCount]                   REAL            NULL,
    [UserDef_MR_1Lbl]                NVARCHAR (4000) NULL,
    [UserDef_MR_1Hrs]                REAL            NULL,
    [UserDef_MR_2Lbl]                NVARCHAR (4000) NULL,
    [UserDef_MR_2Hrs]                REAL            NULL,
    [AvailSchedHours]                REAL            NULL,
    [OmitFromSched]                  NVARCHAR (4000) NULL,
    [DefaultRewinder]                BIT             NULL,
    [MinimumPressSpeed]              INT             NULL,
    [MaximumPressSpeed]              INT             NULL,
    [MinimumStockSpoilage]           REAL            NULL,
    [MaximumStockSpoilage]           REAL            NULL,
    [ConsecutiveNum_SpeedChange]     REAL            NULL,
    [ConsecutiveNum_SpoilageChange]  REAL            NULL,
    [Turnbar_SpeedChange]            REAL            NULL,
    [Turnbar_SpoilageChange]         REAL            NULL,
    [Sheeter_SpeedChange]            REAL            NULL,
    [Sheeter_SpoilageChange]         REAL            NULL,
    [Pinfeed_SpeedChange]            REAL            NULL,
    [Pinfeed_SpoilageChange]         REAL            NULL,
    [UserDef_MR_1_SpeedChange]       REAL            NULL,
    [UserDef_MR_1_SpoilageChange]    REAL            NULL,
    [UserDef_MR_2_SpeedChange]       REAL            NULL,
    [UserDef_MR_2_SpoilageChange]    REAL            NULL,
    [MRFirstDie_SpeedChange]         REAL            NULL,
    [MRFirstDie_SpoilageChange]      REAL            NULL,
    [MRAdd_Dies_SpeedChange]         REAL            NULL,
    [MRAdd_Dies_SpoilageChange]      REAL            NULL,
    [MRFirstColor_SpeedChange]       REAL            NULL,
    [MRFirstColor_SpoilageChange]    REAL            NULL,
    [MRAdd_Colors_SpeedChange]       REAL            NULL,
    [MRAdd_Colors_SpoilageChange]    REAL            NULL,
    [MRFlood_SpeedChange]            REAL            NULL,
    [MRFlood_SpoilageChange]         REAL            NULL,
    [MRStock_SpeedChange]            REAL            NULL,
    [MRStock_SpoilageChange]         REAL            NULL,
    [PlateChange_SpeedChange]        REAL            NULL,
    [PlateChange_SetUpFootChange]    INT             NULL,
    [ColorChange_SpeedChange]        REAL            NULL,
    [ColorChange_SetUpFootChange]    INT             NULL,
    [MR_Max1]                        INT             NULL,
    [MR_Max2]                        INT             NULL,
    [MR_Max3]                        INT             NULL,
    [MR_Max4]                        INT             NULL,
    [MR_Max5]                        INT             NULL,
    [MR_Max6]                        INT             NULL,
    [MR_Desc1]                       NVARCHAR (4000) NULL,
    [MR_Desc2]                       NVARCHAR (4000) NULL,
    [MR_Desc3]                       NVARCHAR (4000) NULL,
    [MR_Desc4]                       NVARCHAR (4000) NULL,
    [MR_Desc5]                       NVARCHAR (4000) NULL,
    [MR_Desc6]                       NVARCHAR (4000) NULL,
    [MR_Hours1]                      REAL            NULL,
    [MR_Hours2]                      REAL            NULL,
    [MR_Hours3]                      REAL            NULL,
    [MR_Hours4]                      REAL            NULL,
    [MR_Hours5]                      REAL            NULL,
    [MR_Hours6]                      REAL            NULL,
    [PhotoPolymerThickness]          REAL            NULL,
    [PolyesterBackingThickness]      REAL            NULL,
    [Impression_Charge]              REAL            NULL,
    [ModifiedBy]                     NVARCHAR (4000) NULL,
    [EnteredBy]                      NVARCHAR (4000) NULL,
    [EnteredDate]                    DATETIME        NULL,
    [EnteredTime]                    TIME (7)        NULL,
    [ImpressionCharge_1_color]       REAL            NULL,
    [ImpressionCharge_2_color]       REAL            NULL,
    [HP_Indigo_Model]                NVARCHAR (4000) NULL,
    [Has_TurretRewinder]             BIT             NULL,
    [InternetQuery]                  BIT             NULL,
    [Rewind_MR_per_FInished_Roll]    REAL            NULL,
    [Rewind_Add_Roll_SpeedChange]    REAL            NULL,
    [Is_Est_Max_up_on]               BIT             NULL,
    [Lineal_Length_Rate]             REAL            NULL,
    [Is_ShrinkSleeve_Capable]        BIT             NULL,
    [Is_DigitalCoating_Required]     BIT             NULL,
    [Is_Print_Roll_Alert_Omitted]    BIT             NULL,
    [BackStage_SmartMarkSet_Default] NVARCHAR (4000) NULL,
    [Est_Are_Tools_for_Equip]        BIT             NULL,
    [Is_Allowed_Rotary_Die]          BIT             NULL,
    [Is_Allowed_SemiRotary_Die]      BIT             NULL,
    [Is_Allowed_Flatbed_Die]         BIT             NULL,
    [Omit_MakeReady_Cycle]           BIT             NULL,
    [Omit_WashUp_Cycle]              BIT             NULL,
    [HP_Indigo_EPM_Markup]           REAL            NULL,
    [ID]                             INT             NULL,
    [Rotometrics_NeedsID]            BIT             NULL,
    [aLC_Is_aLaCarte_Pricing]        BIT             NULL,
    [aLC_White_Charge]               REAL            NULL,
    [aLC_Color_Charge]               REAL            NULL,
    [HP_Indigo_PriceMethod]          INT             NULL,
    [HP_Indigo_PriceChart_Limit_1]   INT             NULL,
    [HP_Indigo_PriceChart_Limit_2]   INT             NULL,
    [HP_Indigo_PriceChart_Limit_3]   INT             NULL,
    [HP_Indigo_PriceChart_Limit_4]   INT             NULL,
    [HP_Indigo_PriceChart_Limit_5]   INT             NULL,
    [HP_Indigo_PriceChart_Limit_6]   INT             NULL,
    [HP_Indigo_PriceChart_Limit_7]   INT             NULL,
    [HP_Indigo_PriceChart_Limit_8]   INT             NULL,
    [HP_Indigo_PriceChart_InkCost_1] REAL            NULL,
    [HP_Indigo_PriceChart_InkCost_2] REAL            NULL,
    [HP_Indigo_PriceChart_InkCost_3] REAL            NULL,
    [HP_Indigo_PriceChart_InkCost_4] REAL            NULL,
    [HP_Indigo_PriceChart_InkCost_5] REAL            NULL,
    [HP_Indigo_PriceChart_InkCost_6] REAL            NULL,
    [HP_Indigo_PriceChart_InkCost_7] REAL            NULL,
    [HP_Indigo_PriceChart_InkCost_8] REAL            NULL,
    [JMF_Device_ID]                  NVARCHAR (4000) NULL,
    [Pitch_Local]                    NVARCHAR (4000) NULL,
    [PType_Local]                    NVARCHAR (4000) NULL,
    [Trim_width]                     REAL            NULL,
    [VS_Events_Auto_Generate]        BIT             NULL,
    [VS_Start]                       TIME (7)        NULL,
    [VS_End]                         TIME (7)        NULL,
    [VS_Mon]                         BIT             NULL,
    [VS_Tue]                         BIT             NULL,
    [VS_Wed]                         BIT             NULL,
    [VS_Thu]                         BIT             NULL,
    [VS_Fri]                         BIT             NULL,
    [VS_Sat]                         BIT             NULL,
    [VS_Sun]                         BIT             NULL,
    [CMYOVG_ClickCharge]             REAL            NULL,
    [CMYOVG_InkCost]                 REAL            NULL,
    [CMYOVG_InkCoverage]             REAL            NULL,
    [White_ClickCharge]              REAL            NULL,
    [White_InkCost]                  REAL            NULL,
    [White_InkCoverage]              REAL            NULL,
    [Black_ClickCharge]              REAL            NULL,
    [Black_InkCost]                  REAL            NULL,
    [Black_InkCoverage]              REAL            NULL,
    [Silver_ClickCharge]             REAL            NULL,
    [Silver_InkCost]                 REAL            NULL,
    [Silver_InkCoverage]             REAL            NULL,
    [Other_ClickCharge]              REAL            NULL,
    [Other_InkCost]                  REAL            NULL,
    [Other_InkCoverage]              REAL            NULL,
    [MaterialPrimer_AreaRate]        REAL            NULL,
    [PK_UUID]                        NVARCHAR (4000) NULL,
    [Toner_Inventory_ID]             NVARCHAR (4000) NULL,
    [SC_Downtimes]                   SMALLINT        NULL,
    [CMYOVG_WeightPerArea]           REAL            NULL,
    [White_WeightPerArea]            REAL            NULL,
    [Black_WeightPerArea]            REAL            NULL,
    [Silver_WeightPerArea]           REAL            NULL,
    [Other_WeightPerArea]            REAL            NULL,
    [SemiRotary_CylinderSize]        REAL            NULL,
    [PressMfg]                       NVARCHAR (4000) NULL,
    [UpdateTimeDateStamp]     DATETIME        NULL
);

