CREATE TABLE [dbo].[Invoice] (
    [Number]                      NVARCHAR (255)  NOT NULL,
    [TicketNum]                   NVARCHAR (4000) NULL,
    [CustomerName]                NVARCHAR (4000) NULL,
    [CustomerNumber]              NVARCHAR (4000) NULL,
    [Terms]                       NVARCHAR (4000) NULL,
    [TaxRate]                     REAL            NULL,
    [STotal]                      REAL            NULL,
    [Tax]                         REAL            NULL,
    [Freight]                     REAL            NULL,
    [MiscText]                    NVARCHAR (4000) NULL,
    [Misc]                        REAL            NULL,
    [Total]                       REAL            NULL,
    [Notes]                       NVARCHAR (4000) NULL,
    [SalesCommissionPercent]      REAL            NULL,
    [County]                      NVARCHAR (4000) NULL,
    [TotalPaid]                   REAL            NULL,
    [iDate]                       DATETIME        NULL,
    [iType]                       NVARCHAR (4000) NULL,
    [PurchItems]                  REAL            NULL,
    [Balance]                     REAL            NULL,
    [Taxed]                       BIT             NULL,
    [Discount]                    REAL            NULL,
    [Closed]                      BIT             NULL,
    [PlateCharge]                 REAL            NULL,
    [ColorCharge]                 REAL            NULL,
    [RInvoice]                    NVARCHAR (4000) NULL,
    [SalesRepNo]                  NVARCHAR (4000) NULL,
    [ZipCode]                     NVARCHAR (4000) NULL,
    [Territory]                   NVARCHAR (4000) NULL,
    [Area]                        NVARCHAR (4000) NULL,
    [PO_Art]                      REAL            NULL,
    [PO_Plate]                    REAL            NULL,
    [PO_Tool]                     REAL            NULL,
    [PO_Generic]                  REAL            NULL,
    [MFGRepCommPercent]           REAL            NULL,
    [MFG_ID]                      NVARCHAR (4000) NULL,
    [MFG_Name]                    NVARCHAR (4000) NULL,
    [IsLocked]                    NVARCHAR (4000) NULL,
    [Tax_STotal]                  BIT             NULL,
    [Tax_Plate]                   BIT             NULL,
    [Tax_Color]                   BIT             NULL,
    [Tax_PO]                      BIT             NULL,
    [Tax_Misc]                    BIT             NULL,
    [Tax_Freight]                 BIT             NULL,
    [StockProdDiscnt]             REAL            NULL,
    [STotalDiscount]              REAL            NULL,
    [TaxRate2]                    REAL            NULL,
    [Tax2]                        REAL            NULL,
    [State_Province]              NVARCHAR (4000) NULL,
    [TaxCredit]                   REAL            NULL,
    [A4_UniqueID]                 INT             NULL,
    [EntryDate]                   DATETIME        NULL,
    [EntryBy]                     NVARCHAR (4000) NULL,
    [ModifyDate]                  DATETIME        NULL,
    [ModifyBy]                    NVARCHAR (4000) NULL,
    [A4LinkDate]                  DATETIME        NULL,
    [SendToA4]                    NVARCHAR (4000) NULL,
    [A4LinkBatchID]               INT             NULL,
    [A4DueDate]                   DATETIME        NULL,
    [A4ClientID]                  INT             NULL,
    [EDIExportDate]               DATETIME        NULL,
    [AR_Transaction_ID]           INT             NULL,
    [PrePay_AR_Bal_ID]            INT             NULL,
    [PrePay_AR_Trans_ID]          INT             NULL,
    [PrePay_ARMaint_ID]           INT             NULL,
    [AR_PostingStatus]            NVARCHAR (4000) NULL,
    [Distributed_Amount]          REAL            NULL,
    [Undistributed_Amount]        REAL            NULL,
    [GL_PostingStatus]            NVARCHAR (4000) NULL,
    [GL_Detail_ID]                INT             NULL,
    [SalesCommissionAmount]       REAL            NULL,
    [BilledOnMasterInvoiceNum]    NVARCHAR (4000) NULL,
    [MasterInvoicePO_Num]         NVARCHAR (4000) NULL,
    [TaxCertificatePrintText]     NVARCHAR (4000) NULL,
    [TaxCB_Plate_i]               INT             NULL,
    [TaxCB_Color_i]               INT             NULL,
    [TaxCB_AllPOs_i]              INT             NULL,
    [TaxCB_Misc_i]                INT             NULL,
    [TaxCB_Freight_i]             INT             NULL,
    [TaxCB_Discount_i]            INT             NULL,
    [Tax_TotalSaleAmount]         REAL            NULL,
    [Tax_ExemptSaleAmount]        REAL            NULL,
    [Tax_ResaleAmount]            REAL            NULL,
    [Tax_NonTaxableSalesAmount]   REAL            NULL,
    [Tax_TotalAmountSubjectToTax] REAL            NULL,
    [Tax_SalesTaxAmount]          REAL            NULL,
    [TaxCB_STotal_i]              INT             NULL,
    [TaxAmount_Total]             REAL            NULL,
    [InvTax_UsesNewTaxSystem]     BIT             NULL,
    [InvTax_ConvertToNewSys]      BIT             NULL,
    [RST_ReversingInvoiceType]    NVARCHAR (4000) NULL,
    [RST_SourceInvoiceNum]        NVARCHAR (4000) NULL,
    [RST_ReversingInvoiceNum]     NVARCHAR (4000) NULL,
    [RST_DuplicateInvoiceNum]     NVARCHAR (4000) NULL,
    [EntryTime]                   TIME (7)        NULL,
    [ModifyTime]                  TIME (7)        NULL,
    [Currency_ExchangeRate]       REAL            NULL,
    [Currency_ID]                 INT             NULL,
    [FCT_TotalPaid]               REAL            NULL,
    [FCT_Balance]                 REAL            NULL,
    [FCT_Total]                   REAL            NULL,
    [MFGRepCommAmount]            REAL            NULL,
    [Enduser_ID]                  NVARCHAR (4000) NULL,
    [Mex_UUID]                    NVARCHAR (4000) NULL,
    [Currency_Rate_ID]            INT             NULL,
    [FC_STotal]                   REAL            NULL,
    [FC_STotalDiscount]           REAL            NULL,
    [FC_TaxAmount_Total]          REAL            NULL,
    [FC_PlateCharge]              REAL            NULL,
    [FC_ColorCharge]              REAL            NULL,
    [FC_PurchItems]               REAL            NULL,
    [FC_Misc]                     REAL            NULL,
    [FC_Freight]                  REAL            NULL,
    [FC_PO_Art]                   REAL            NULL,
    [FC_PO_Plate]                 REAL            NULL,
    [FC_PO_Tool]                  REAL            NULL,
    [FC_PO_Generic]               REAL            NULL,
    [Method_of_Payment]           NVARCHAR (4000) NULL,
    [MiscChargeDesc1]             NVARCHAR (4000) NULL,
    [MiscChargeDesc2]             NVARCHAR (4000) NULL,
    [MiscChargeDesc3]             NVARCHAR (4000) NULL,
    [MiscChargeDesc4]             NVARCHAR (4000) NULL,
    [MiscCharge1]                 REAL            NULL,
    [MiscCharge2]                 REAL            NULL,
    [MiscCharge3]                 REAL            NULL,
    [MiscCharge4]                 REAL            NULL,
    [FC_MiscCharge1]              REAL            NULL,
    [FC_MiscCharge2]              REAL            NULL,
    [FC_MiscCharge3]              REAL            NULL,
    [FC_MiscCharge4]              REAL            NULL,
    [PK_UUID]                     NVARCHAR (4000) NULL,
    [UpdateTimeDateStamp]     DATETIME        NULL
);

