CREATE TABLE [dbo].[Product] (
    [UniqueProdID]            NVARCHAR (255)  NOT NULL,
    [PRODNUM]                 NVARCHAR (4000) NULL,
    [CUSTNUM]                 NVARCHAR (4000) NULL,
    [PRODNUM_CUSTNUM]         NVARCHAR (4000) NULL,
    [DESCRIPTION]             NVARCHAR (4000) NULL,
    [PRODDATE]                DATETIME        NULL,
    [COLORDESCR]              NVARCHAR (4000) NULL,
    [JOBTYPE]                 NVARCHAR (4000) NULL,
    [MATERIALTRAC]            BIT             NULL,
    [AUTOAPPL]                BIT             NULL,
    [PRODGROUP]               NVARCHAR (4000) NULL,
    [SIZEACROSS]              REAL            NULL,
    [SIZEAROUND]              REAL            NULL,
    [COLSPACE]                REAL            NULL,
    [ROWSPACE]                REAL            NULL,
    [LABELREPEAT]             REAL            NULL,
    [NOACROSS]                SMALLINT        NULL,
    [NOAROUND]                SMALLINT        NULL,
    [CSA]                     BIT             NULL,
    [FINISHTYPE]              NVARCHAR (4000) NULL,
    [PINFEED]                 BIT             NULL,
    [LABELSPER_]              INT             NULL,
    [NOLABACROSSFIN]          SMALLINT        NULL,
    [COREDIAMETER]            REAL            NULL,
    [FINALUNWIND]             NVARCHAR (4000) NULL,
    [LABELSPERFOLD]           SMALLINT        NULL,
    [NOTES]                   NVARCHAR (4000) NULL,
    [TAB]                     REAL            NULL,
    [PRESS]                   NVARCHAR (4000) NULL,
    [TOTALTICKETS]            SMALLINT        NULL,
    [CORNERRADIUS]            REAL            NULL,
    [TURNBAR]                 BIT             NULL,
    [INKTYPE]                 NVARCHAR (4000) NULL,
    [NOOFCOLORS]              SMALLINT        NULL,
    [COLUMNPERF]              REAL            NULL,
    [ROWPERF]                 REAL            NULL,
    [PLATE_ID]                NVARCHAR (4000) NULL,
    [ESTIMATENUM]             NVARCHAR (4000) NULL,
    [QUANTITY1]               INT             NULL,
    [PRICEPERM1]              REAL            NULL,
    [QUANTITY2]               INT             NULL,
    [PRICEPERM2]              REAL            NULL,
    [QUANTITY3]               INT             NULL,
    [PRICEPERM3]              REAL            NULL,
    [QUANTITY4]               INT             NULL,
    [PRICEPERM4]              REAL            NULL,
    [QUANTITY5]               INT             NULL,
    [PRICEPERM5]              REAL            NULL,
    [QUANTITY6]               INT             NULL,
    [PRICEPERM6]              REAL            NULL,
    [ENDUSERNUM]              NVARCHAR (4000) NULL,
    [STOCKNUM1]               NVARCHAR (4000) NULL,
    [STOCKWIDTH1]             REAL            NULL,
    [STOCKNUM2]               NVARCHAR (4000) NULL,
    [STOCKWIDTH2]             REAL            NULL,
    [STOCKNUM3]               NVARCHAR (4000) NULL,
    [STOCKWIDTH3]             REAL            NULL,
    [SHEETPACKTYPE]           NVARCHAR (4000) NULL,
    [NOTICKETS]               INT             NULL,
    [NOFLOODS]                SMALLINT        NULL,
    [TOOLNO1]                 NVARCHAR (4000) NULL,
    [TOOLNO2]                 NVARCHAR (4000) NULL,
    [TOOL2DESCR]              NVARCHAR (4000) NULL,
    [TOOLNO3]                 NVARCHAR (4000) NULL,
    [TOOL3DESCR]              NVARCHAR (4000) NULL,
    [TOOLNO4]                 NVARCHAR (4000) NULL,
    [TOOL4DESCR]              NVARCHAR (4000) NULL,
    [TOOLNO5]                 NVARCHAR (4000) NULL,
    [TOOL5DESCR]              NVARCHAR (4000) NULL,
    [CONSECNO]                NVARCHAR (4000) NULL,
    [SHAPE]                   NVARCHAR (4000) NULL,
    [CUSTNAME]                NVARCHAR (4000) NULL,
    [ENDUSERNAME]             NVARCHAR (4000) NULL,
    [STOCKDESCR1]             NVARCHAR (4000) NULL,
    [STOCKDESCR2]             NVARCHAR (4000) NULL,
    [STOCKDESCR3]             NVARCHAR (4000) NULL,
    [CARRIERWIDTH]            REAL            NULL,
    [INVENTORY]               INT             NULL,
    [OVERRUN]                 INT             NULL,
    [HIDDEN_NOTES]            NVARCHAR (4000) NULL,
    [PROJORDER]               DATETIME        NULL,
    [PROJECTPROD]             BIT             NULL,
    [TABPOSITION]             BIT             NULL,
    [CUSTISDISTRIB]           BIT             NULL,
    [UL]                      BIT             NULL,
    [PRICEMODE]               NVARCHAR (4000) NULL,
    [MISCCHARGEDESC]          NVARCHAR (4000) NULL,
    [MISCCHARGE]              REAL            NULL,
    [CORETYPE]                NVARCHAR (4000) NULL,
    [ROLLLENGTH]              INT             NULL,
    [ROLLUNIT]                NVARCHAR (4000) NULL,
    [TAPE]                    BIT             NULL,
    [COMMISSION]              REAL            NULL,
    [SPECIALPRICE]            BIT             NULL,
    [BC_SYMBOL]               NVARCHAR (4000) NULL,
    [BC_HEIGHT]               REAL            NULL,
    [BC_WIDTH]                REAL            NULL,
    [BC_XDIM]                 REAL            NULL,
    [BC_DATAORIGIN]           NVARCHAR (4000) NULL,
    [BC_RATIO]                NVARCHAR (4000) NULL,
    [BC_PREFIX]               BIT             NULL,
    [BC_CHECKDIGIT]           BIT             NULL,
    [BC_START]                NVARCHAR (4000) NULL,
    [BC_END]                  NVARCHAR (4000) NULL,
    [BC_HRSTART]              NVARCHAR (4000) NULL,
    [BC_HREND]                NVARCHAR (4000) NULL,
    [BC_POSITION]             NVARCHAR (4000) NULL,
    [COSTFIELD]               REAL            NULL,
    [USERDEF_MR_1]            BIT             NULL,
    [USERDEF_MR_2]            BIT             NULL,
    [USERDEF_MR_1_LB]         NVARCHAR (4000) NULL,
    [USERDEF_MR_2_LB]         NVARCHAR (4000) NULL,
    [OUTSIDEDIAMETER]         REAL            NULL,
    [CALIPER_LAMINAT]         REAL            NULL,
    [CALIPER_FACESTK]         REAL            NULL,
    [CALIPER_ADHESIV]         REAL            NULL,
    [FINISHNOTES]             NVARCHAR (4000) NULL,
    [NAME1]                   NVARCHAR (4000) NULL,
    [NAME2]                   NVARCHAR (4000) NULL,
    [NAME3]                   NVARCHAR (4000) NULL,
    [NAME4]                   NVARCHAR (4000) NULL,
    [POPUPNAME1]              NVARCHAR (4000) NULL,
    [POPUPNAME2]              NVARCHAR (4000) NULL,
    [REVISIONNO]              NVARCHAR (4000) NULL,
    [TOOLINGNOTES]            NVARCHAR (4000) NULL,
    [CERTIFICATNOTES]         NVARCHAR (4000) NULL,
    [CRITICALQUALITY]         NVARCHAR (4000) NULL,
    [COREWIDTH]               REAL            NULL,
    [CARTONSIZE]              NVARCHAR (4000) NULL,
    [NUMPERCARTON]            NVARCHAR (4000) NULL,
    [PALLETSIZE]              NVARCHAR (4000) NULL,
    [REWINDEQUIPNUM]          NVARCHAR (4000) NULL,
    [REWINDEQUIPNAM]          NVARCHAR (4000) NULL,
    [SUBPRODUCT]              BIT             NULL,
    [AMORTIZEPLATECHANGES]    BIT             NULL,
    [AMORTIZECOLORCHANGES]    BIT             NULL,
    [STOCKNOTES]              NVARCHAR (4000) NULL,
    [SHEET_WIDTH]             REAL            NULL,
    [SHEET_HEIGHT]            REAL            NULL,
    [INACTIVE]                BIT             NULL,
    [SLITONREWIND]            BIT             NULL,
    [IMAGE_SOURCEAPPLICATION] NVARCHAR (4000) NULL,
    [IMAGE_FILENAME]          NVARCHAR (4000) NULL,
    [ENTEREDBY]               NVARCHAR (4000) NULL,
    [MODIFIEDBY]              NVARCHAR (4000) NULL,
    [ENTEREDDATE]             DATETIME        NULL,
    [MODIFIEDDATE]            DATETIME        NULL,
    [ENTEREDTIME]             TIME (7)        NULL,
    [MODIFIEDTIME]            TIME (7)        NULL,
    [EQUIP_ID]                NVARCHAR (4000) NULL,
    [ARE_TOOLS_FOR_EQUIP]     BIT             NULL,
    [EQUIP_NOCOLORS]          SMALLINT        NULL,
    [EQUIP_NOFLOODS]          SMALLINT        NULL,
    [GROUP_ID]                NVARCHAR (4000) NULL,
    [PRESS_NULL_CYCLES]       INT             NULL,
    [EQUIP_NULL_CYCLES]       INT             NULL,
    [USE_TURRETREWINDER]      BIT             NULL,
    [CURRENCY_ID]             INT             NULL,
    [CURRENCY_EXCHANGERATE]   REAL            NULL,
    [IMAGE_FORMAT]            INT             NULL,
    [SHRINKSLEEVE_OVERLAP]    REAL            NULL,
    [SHRINKSLEEVE_LAYFLAT]    REAL            NULL,
    [SHRINKSLEEVE_CUTHEIGHT]  REAL            NULL,
    [COMMISSIONSOURCE]        NVARCHAR (4000) NULL,
    [PROFITADJLABEL]          NVARCHAR (4000) NULL,
    [SALESREPNUMBER]          NVARCHAR (4000) NULL,
    [SALESREPNAME]            NVARCHAR (4000) NULL,
    [INTERNETQUERY]           BIT             NULL,
    [ETRAXX_BACKSTAGEPDF]     NVARCHAR (4000) NULL,
    [IMAGE_SIZE]              REAL            NULL,
    [BACKSTAGE_COLORSTRATEGY] NVARCHAR (4000) NULL,
    [BACKSTAGE_SMARTMARKSET]  NVARCHAR (4000) NULL,
    [EQUIP3_ID]               NVARCHAR (4000) NULL,
    [EQUIP3_NOCOLORS]         SMALLINT        NULL,
    [EQUIP3_NOFLOODS]         SMALLINT        NULL,
    [EQUIP3_NULL_CYCLES]      INT             NULL,
    [EQUIP4_ID]               NVARCHAR (4000) NULL,
    [EQUIP4_NOCOLORS]         SMALLINT        NULL,
    [EQUIP4_NOFLOODS]         SMALLINT        NULL,
    [EQUIP4_NULL_CYCLES]      INT             NULL,
    [EQUIP_NOACROSS]          INT             NULL,
    [EQUIP_NOAROUND]          INT             NULL,
    [EQUIP_NUMUP_MULTIPLIER]  INT             NULL,
    [EQUIP3_NOACROSS]         INT             NULL,
    [EQUIP3_NOAROUND]         INT             NULL,
    [EQUIP3_NUMUP_MULTIPLIER] INT             NULL,
    [EQUIP4_NOACROSS]         INT             NULL,
    [EQUIP4_NOAROUND]         INT             NULL,
    [EQUIP4_NUMUP_MULTIPLIER] INT             NULL,
    [JDF_SENT_ON]             NVARCHAR (4000) NULL,
    [JDF_NOT_ALLOWED]         BIT             NULL,
    [TOOL_NUMBERAROUND]       SMALLINT        NULL,
    [ROTO_QUOTE_NUMBER]       NVARCHAR (4000) NULL,
    [ROTO_QUOTE_LINE_ID]      NVARCHAR (4000) NULL,
    [SCREEN_RATIO]            NVARCHAR (4000) NULL,
    [ROTO_CEL_PRODUCT_ID]     NVARCHAR (4000) NULL,
    [FX_PRICEPERM_1]          REAL            NULL,
    [FX_PRICEPERM_2]          REAL            NULL,
    [FX_PRICEPERM_3]          REAL            NULL,
    [FX_PRICEPERM_4]          REAL            NULL,
    [FX_PRICEPERM_5]          REAL            NULL,
    [FX_PRICEPERM_6]          REAL            NULL,
    [FX_MISCCHARGE]           REAL            NULL,
    [CURRENCY_RATE_ID]        INT             NULL,
    [ROLLUNIT_LOCAL]          NVARCHAR (4000) NULL,
    [FX_PLATECHANGE_CHARGE]   REAL            NULL,
    [FX_COLORCHANGE_CHARGE]   REAL            NULL,
    [PRICEMODE_LOCAL]         NVARCHAR (4000) NULL,
    [COMMISSIONSOURCE_LOCAL]  NVARCHAR (4000) NULL,
    [HP_INDIGO_PRESS_IS_EPM]  BIT             NULL,
    [HP_INDIGO_EQUIP_IS_EPM]  BIT             NULL,
    [HP_INDIGO_EQUIP3_IS_EPM] BIT             NULL,
    [HP_INDIGO_EQUIP4_IS_EPM] BIT             NULL,
    [MISCCHARGEDESC1]         NVARCHAR (4000) NULL,
    [MISCCHARGEDESC2]         NVARCHAR (4000) NULL,
    [MISCCHARGEDESC3]         NVARCHAR (4000) NULL,
    [MISCCHARGEDESC4]         NVARCHAR (4000) NULL,
    [MISCCHARGE1]             REAL            NULL,
    [MISCCHARGE2]             REAL            NULL,
    [MISCCHARGE3]             REAL            NULL,
    [MISCCHARGE4]             REAL            NULL,
    [FX_MISCCHARGE1]          REAL            NULL,
    [FX_MISCCHARGE2]          REAL            NULL,
    [FX_MISCCHARGE3]          REAL            NULL,
    [FX_MISCCHARGE4]          REAL            NULL,
    [FRAMES_LEAD_IN]          INT             NULL,
    [FRAMES_LEAD_OUT]         INT             NULL,
    [JOBTYPE_LOCAL]           NVARCHAR (4000) NULL,
    [PK_UUID]                 NVARCHAR (4000) NULL,
    [NOACROSS_OVERRIDE]       BIT             NULL,
    [NOAROUND_OVERRIDE]       BIT             NULL,
    [FPUD_POPUP1]             NVARCHAR (4000) NULL,
    [FPUD_POPUP2]             NVARCHAR (4000) NULL,
    [FPUD_POPUP3]             NVARCHAR (4000) NULL,
    [FPUD_POPUP4]             NVARCHAR (4000) NULL,
    [FPUD_POPUP5]             NVARCHAR (4000) NULL,
    [FPUD_POPUP6]             NVARCHAR (4000) NULL,
    [UpdateTimeDateStamp]     DATETIME        NULL,
    CONSTRAINT [PK_ProductUniqueProdID] PRIMARY KEY CLUSTERED ([UniqueProdID] ASC)
);

