CREATE TABLE [dbo].[Product_PostPress] (
    [PK_UUID]         NVARCHAR (450)  NOT NULL,
    [ID]              INT             NULL,
    [UNIQUEPRODID]    NVARCHAR (4000) NULL,
    [EQUIP_NUMBER]    NVARCHAR (4000) NULL,
    [EQUIP_DESC]      NVARCHAR (4000) NULL,
    [U1]              NVARCHAR (4000) NULL,
    [OPERATIONS_DESC] NVARCHAR (4000) NULL,
    [PIECESOPERATION] INT             NULL,
    [OPERATIONS_HOUR] INT             NULL,
    [MATERIALS_DESC]  NVARCHAR (4000) NULL,
    [MATERIALS_RATE]  REAL            NULL,
    [MATERIALS_UNIT]  NVARCHAR (4000) NULL,
    [NOTES]           NVARCHAR (4000) NULL,
    [OPTION_DESC1]    NVARCHAR (4000) NULL,
    [OPTION_DESC2]    NVARCHAR (4000) NULL,
    [OPTION_DESC3]    NVARCHAR (4000) NULL,
    [OPTION_DESC4]    NVARCHAR (4000) NULL,
    [OPTION_DESC5]    NVARCHAR (4000) NULL,
    [OPTION_DESC6]    NVARCHAR (4000) NULL,
    [OPTION_HOURS1]   REAL            NULL,
    [OPTION_HOURS2]   REAL            NULL,
    [OPTION_HOURS3]   REAL            NULL,
    [OPTION_HOURS4]   REAL            NULL,
    [OPTION_HOURS5]   REAL            NULL,
    [OPTION_HOURS6]   REAL            NULL,
    [OPTION_QTY1]     INT             NULL,
    [OPTION_QTY2]     INT             NULL,
    [OPTION_QTY3]     INT             NULL,
    [OPTION_QTY4]     INT             NULL,
    [OPTION_QTY5]     INT             NULL,
    [OPTION_QTY6]     INT             NULL,
    [OPTION_MAX1]     INT             NULL,
    [OPTION_MAX2]     INT             NULL,
    [OPTION_MAX3]     INT             NULL,
    [OPTION_MAX4]     INT             NULL,
    [OPTION_MAX5]     INT             NULL,
    [OPTION_MAX6]     INT             NULL,
    [U3]              NVARCHAR (4000) NULL,
    [U4]              NVARCHAR (4000) NULL,
    [U5]              NVARCHAR (4000) NULL,
    [U6]              NVARCHAR (4000) NULL,
    [U7]              NVARCHAR (4000) NULL,
    [U8]              NVARCHAR (4000) NULL,
    [WEIGHT_PIECE]    REAL            NULL
);

