CREATE TABLE [dbo].[PurchaseOrder] (
    [PONumber]                     NVARCHAR (255)  NOT NULL,
    [TicketNum]                    NVARCHAR (4000) NULL,
    [PODate]                       DATETIME        NULL,
    [DateReq]                      DATETIME        NULL,
    [Received]                     DATETIME        NULL,
    [Description]                  NVARCHAR (4000) NULL,
    [SizeAcross]                   REAL            NULL,
    [SizeAround]                   REAL            NULL,
    [ColSpace]                     REAL            NULL,
    [RowSpace]                     REAL            NULL,
    [LabelRepeat]                  REAL            NULL,
    [NumAcross]                    SMALLINT        NULL,
    [NumArounPlate]                SMALLINT        NULL,
    [NumberArounDie]               SMALLINT        NULL,
    [SupplierNum]                  NVARCHAR (4000) NULL,
    [Signer_AssocNum]              NVARCHAR (4000) NULL,
    [Shape]                        NVARCHAR (4000) NULL,
    [Patched_ShipToAddress]        DATETIME        NULL,
    [DieCut]                       SMALLINT        NULL,
    [OrderStockNum]                NVARCHAR (4000) NULL,
    [MFGSpec]                      NVARCHAR (4000) NULL,
    [Steel]                        NVARCHAR (4000) NULL,
    [CornerRadius]                 REAL            NULL,
    [ChromePlate]                  BIT             NULL,
    [Quantity]                     SMALLINT        NULL,
    [AutoAppl]                     BIT             NULL,
    [FinalUnwind]                  NVARCHAR (4000) NULL,
    [TopCoat]                      NVARCHAR (4000) NULL,
    [ThroughInk]                   BIT             NULL,
    [EquipNum]                     NVARCHAR (4000) NULL,
    [StockNo1]                     NVARCHAR (4000) NULL,
    [StockNo2]                     NVARCHAR (4000) NULL,
    [StockNo3]                     NVARCHAR (4000) NULL,
    [WebWidth]                     REAL            NULL,
    [ShipVia]                      NVARCHAR (4000) NULL,
    [QCOType]                      NVARCHAR (4000) NULL,
    [POType]                       NVARCHAR (4000) NULL,
    [MasterWidth]                  REAL            NULL,
    [ToolNum]                      NVARCHAR (4000) NULL,
    [FaceColor]                    NVARCHAR (4000) NULL,
    [FaceCaliper]                  NVARCHAR (4000) NULL,
    [Adhesive]                     NVARCHAR (4000) NULL,
    [CostMSI]                      REAL            NULL,
    [Items_subtable]               INT             NULL,
    [Notes]                        NVARCHAR (4000) NULL,
    [TotalPO]                      REAL            NULL,
    [LinerCaliper]                 NVARCHAR (4000) NULL,
    [FaceStock]                    NVARCHAR (4000) NULL,
    [SellPrice]                    REAL            NULL,
    [Supplier]                     NVARCHAR (4000) NULL,
    [Invoiced]                     BIT             NULL,
    [InvoiceNum]                   NVARCHAR (4000) NULL,
    [Closed]                       BIT             NULL,
    [Press]                        NVARCHAR (4000) NULL,
    [ToolWidth]                    REAL            NULL,
    [Signer_AssocName]             NVARCHAR (4000) NULL,
    [LamStock]                     NVARCHAR (4000) NULL,
    [ActShipDate]                  DATETIME        NULL,
    [PhoneNo]                      NVARCHAR (4000) NULL,
    [ProofNeed]                    NVARCHAR (4000) NULL,
    [EntryDate]                    DATETIME        NULL,
    [EntryBy]                      NVARCHAR (4000) NULL,
    [ModifyDate]                   DATETIME        NULL,
    [ModifyBy]                     NVARCHAR (4000) NULL,
    [A4LinkDate]                   DATETIME        NULL,
    [SendToA4]                     NVARCHAR (4000) NULL,
    [A4VoucherID]                  INT             NULL,
    [A4LinkBatchID]                INT             NULL,
    [ShipCountry]                  NVARCHAR (4000) NULL,
    [Ship_Address_ID]              NVARCHAR (4000) NULL,
    [DontVoucher]                  BIT             NULL,
    [ShipName]                     NVARCHAR (4000) NULL,
    [ShipAddr1]                    NVARCHAR (4000) NULL,
    [ShipAddr2]                    NVARCHAR (4000) NULL,
    [ShipCity]                     NVARCHAR (4000) NULL,
    [ShipState]                    NVARCHAR (4000) NULL,
    [ShipZip]                      NVARCHAR (4000) NULL,
    [ShipAttention]                NVARCHAR (4000) NULL,
    [Account_No]                   NVARCHAR (4000) NULL,
    [VndAttention]                 NVARCHAR (4000) NULL,
    [TimeDue]                      NVARCHAR (4000) NULL,
    [Status]                       NVARCHAR (4000) NULL,
    [Return_PO_ID]                 NVARCHAR (4000) NULL,
    [Terms]                        NVARCHAR (4000) NULL,
    [FOB]                          NVARCHAR (4000) NULL,
    [PO_Subtotal]                  REAL            NULL,
    [Tax]                          REAL            NULL,
    [Freight]                      REAL            NULL,
    [ToolPOSource]                 NVARCHAR (4000) NULL,
    [PushPO_ToAP_Status]           NVARCHAR (4000) NULL,
    [AP_Invoice_ID]                INT             NULL,
    [Received_Total]               REAL            NULL,
    [RequestedDeliveryDate]        DATETIME        NULL,
    [eCommerceSendPOstatus]        NVARCHAR (4000) NULL,
    [TaxCB_TaxPO_i]                INT             NULL,
    [EntryTime]                    TIME (7)        NULL,
    [ModifyTime]                   TIME (7)        NULL,
    [OverrideStockPricing]         BIT             NULL,
    [TaxRegionID]                  INT             NULL,
    [TaxRegionRate]                REAL            NULL,
    [Received_Tax]                 REAL            NULL,
    [DieBlank]                     BIT             NULL,
    [FC_Supplier_Currency_ID]      INT             NULL,
    [FC_Supplier_ExchangeRate]     REAL            NULL,
    [FC_Supplier_UnitPrice]        REAL            NULL,
    [Yield_Area_Weight]            REAL            NULL,
    [FC_Supplier_Currency_Rate_ID] INT             NULL,
    [Price_Weight]                 REAL            NULL,
    [Inventory_Location]           NVARCHAR (4000) NULL,
    [Roto_UOM_Code]                NVARCHAR (4000) NULL,
    [Roto_ProdFam_Code]            NVARCHAR (4000) NULL,
    [Roto_CavityShape_Code]        NVARCHAR (4000) NULL,
    [Roto_LayoutOpt_Code]          NVARCHAR (4000) NULL,
    [Roto_CutType_Code]            NVARCHAR (4000) NULL,
    [Roto_CutPosition_Code]        NVARCHAR (4000) NULL,
    [Roto_LabelAppl_Code]          NVARCHAR (4000) NULL,
    [Roto_Treatment_Code]          NVARCHAR (4000) NULL,
    [Roto_DrillShaft_Code]         NVARCHAR (4000) NULL,
    [Roto_BladeHeight_Code]        NVARCHAR (4000) NULL,
    [Roto_NonStickText]            NVARCHAR (4000) NULL,
    [Roto_NumHolesPerCavity]       NVARCHAR (4000) NULL,
    [Roto_PatternCentered]         NVARCHAR (4000) NULL,
    [Roto_Quote_Number]            NVARCHAR (4000) NULL,
    [Roto_Quote_Line_ID]           NVARCHAR (4000) NULL,
    [Roto_Quote_Status]            NVARCHAR (4000) NULL,
    [Roto_SpecialBladeHeight]      NVARCHAR (4000) NULL,
    [Roto_Num_Perf_Sets]           NVARCHAR (4000) NULL,
    [BillTo_AddressID]             NVARCHAR (4000) NULL,
    [BillTo_Name]                  NVARCHAR (4000) NULL,
    [BillTo_Addr1]                 NVARCHAR (4000) NULL,
    [BillTo_Addr2]                 NVARCHAR (4000) NULL,
    [BillTo_City]                  NVARCHAR (4000) NULL,
    [BillTo_State]                 NVARCHAR (4000) NULL,
    [BillTo_Zip]                   NVARCHAR (4000) NULL,
    [BillTo_Country]               NVARCHAR (4000) NULL,
    [BillTo_Attention]             NVARCHAR (4000) NULL,
    [Roto_CEL_Product_ID]          NVARCHAR (4000) NULL,
    [Tool_NumberAround]            INT             NULL,
    [ShipeCommShipToID]            NVARCHAR (4000) NULL,
    [DieCut_Local]                 NVARCHAR (4000) NULL,
    [FC_Customer_Currency_ID]      INT             NULL,
    [FC_Customer_Currency_Rate_ID] INT             NULL,
    [FC_Customer_ExchangeRate]     REAL            NULL,
    [FC_Customer_SellPrice]        REAL            NULL,
    [Roto_DieUse_Code]             NVARCHAR (4000) NULL,
    [Roto_Laser_Harden]            BIT             NULL,
    [Roto_Plate_Length]            REAL            NULL,
    [Roto_Plate_Width]             REAL            NULL,
    [Roto_SetPageAndPop]           NVARCHAR (4000) NULL,
    [Roto_Plate_Height]            REAL            NULL,
    [PK_UUID]                      NVARCHAR (4000) NULL,
    [Flexo_HotS]                   NVARCHAR (4000) NULL,
    [OnSaved_TXT]                  NVARCHAR (4000) NULL,
    [POType_Local]                 NVARCHAR (4000) NULL,
    [QCOType_Local]                NVARCHAR (4000) NULL,
    [Core_Size]                    REAL            NULL,
    [FC_PO_Subtotal]               REAL            NULL,
    [FC_Tax]                       REAL            NULL,
    [FC_Received_Total]            REAL            NULL,
    [FC_Received_Tax]              REAL            NULL,
    [FC_Price_Weight]              REAL            NULL,
    [FlexPack_Height]              REAL            NULL,
    [FlexPack_Gusset]              REAL            NULL,
    [FlexPack_LeftTrim]            REAL            NULL,
    [FlexPack_RightTrim]           REAL            NULL,
    [FC_Freight]                   REAL            NULL,
    [FC_TotalPO]                   REAL            NULL,
    [Tag]                          VARCHAR(36)     NULL,
    [UpdateTimeDateStamp]     DATETIME        NULL,
    CONSTRAINT [PK_PurchaseOrderPONumber] PRIMARY KEY CLUSTERED ([PONumber] ASC)
);

