CREATE TABLE [dbo].[Quality_Log] (
    [ID]                             INT             NULL,
    [User_Type]                      NVARCHAR (4000) NULL,
    [Invoice_ID]                     NVARCHAR (4000) NULL,
    [Ticket_ID]                      NVARCHAR (4000) NULL,
    [Customer_ID]                    NVARCHAR (4000) NULL,
    [Customer_Name]                  NVARCHAR (4000) NULL,
    [Materials_Received]             BIT             NULL,
    [Received]                       DATETIME        NULL,
    [Received_by_Employee_ID]        NVARCHAR (4000) NULL,
    [Received_by_Employee_Name]      NVARCHAR (4000) NULL,
    [User_Reviewed]                  BIT             NULL,
    [Reviewed]                       DATETIME        NULL,
    [Reviewed_by_Employee_ID]        NVARCHAR (4000) NULL,
    [Reviewed_by_Employee_Name]      NVARCHAR (4000) NULL,
    [Record_Type]                    NVARCHAR (4000) NULL,
    [Description]                    NVARCHAR (4000) NULL,
    [Modified_Date]                  DATETIME        NULL,
    [Modified_Time]                  TIME (7)        NULL,
    [Modified_by_Employee_ID]        NVARCHAR (4000) NULL,
    [Modified_by_Employee_Name]      NVARCHAR (4000) NULL,
    [Detailed_Explaination]          NVARCHAR (4000) NULL,
    [Notes]                          NVARCHAR (MAX) NULL,
    [Corrective_Action]              NVARCHAR (4000) NULL,
    [Contact_ID]                     NVARCHAR (4000) NULL,
    [Contact_Name]                   NVARCHAR (4000) NULL,
    [Contact_Phone]                  NVARCHAR (4000) NULL,
    [Contact_Extension]              NVARCHAR (4000) NULL,
    [User_Issued]                    BIT             NULL,
    [Issued]                         DATETIME        NULL,
    [Issued_by_Employee_ID]          NVARCHAR (4000) NULL,
    [Issued_by_Employee_Name]        NVARCHAR (4000) NULL,
    [Created_Date]                   DATETIME        NULL,
    [Created_Time]                   TIME (7)        NULL,
    [Created_by_Employee_ID]         NVARCHAR (4000) NULL,
    [Created_by_Employee_Name]       NVARCHAR (4000) NULL,
    [Total_Cost]                     REAL            NULL,
    [Material_Cost]                  REAL            NULL,
    [Freight_Cost]                   REAL            NULL,
    [Credit_Amount]                  REAL            NULL,
    [Check_Number]                   NVARCHAR (4000) NULL,
    [Vendor_ID]                      NVARCHAR (4000) NULL,
    [Vendor_Name]                    NVARCHAR (4000) NULL,
    [StockNumber]                    NVARCHAR (4000) NULL,
    [InventoryNumber]                NVARCHAR (4000) NULL,
    [MiscCostDescr]                  NVARCHAR (4000) NULL,
    [MiscCostAmount]                 REAL            NULL,
    [Inventory_PartNumber]           NVARCHAR (4000) NULL,
    [PO_Number]                      NVARCHAR (4000) NULL,
    [EndUser_ID]                     NVARCHAR (4000) NULL,
    [EndUser_Name]                   NVARCHAR (4000) NULL,
    [Replacement_Ticket_ID]          NVARCHAR (4000) NULL,
    [CustomProduct_PartNumber]       NVARCHAR (4000) NULL,
    [CustomProduct_Description]      NVARCHAR (4000) NULL,
    [StockProduct_PartNumber]        NVARCHAR (4000) NULL,
    [StockProduct_Description]       NVARCHAR (4000) NULL,
    [Is_Closed]                      BIT             NULL,
    [Closed_Date]                    DATETIME        NULL,
    [Closed_by_Employee_ID]          NVARCHAR (4000) NULL,
    [Closed_by_Employee_Name]        NVARCHAR (4000) NULL,
    [Is_Credit_Issued]               BIT             NULL,
    [Credit_Issued_Date]             DATETIME        NULL,
    [Credit_Issued_by_Employee_ID]   NVARCHAR (4000) NULL,
    [Credit_Issued_by_Employee_Name] NVARCHAR (4000) NULL,
    [Is_Action_Taken]                BIT             NULL,
    [Action_Date]                    DATETIME        NULL,
    [Action_Taken_by_Employee_ID]    NVARCHAR (4000) NULL,
    [Action_Taken_by_Employee_Name]  NVARCHAR (4000) NULL,
    [Severity]                       NVARCHAR (4000) NULL,
    [ActionType]                     NVARCHAR (4000) NULL,
    [Root_Cause]                     NVARCHAR (4000) NULL,
    [Verification]                   NVARCHAR (4000) NULL,
    [Due_Date]                       DATETIME        NULL,
    [Effective]                      INT             NULL,
    [PK_UUID]                        NVARCHAR (4000) NULL
);

