CREATE TABLE [dbo].[RollStock] (
    [IDNumber]               NVARCHAR (4000) NULL,
    [StockNum]               NVARCHAR (4000) NULL,
    [PONumber]               NVARCHAR (4000) NULL,
    [AllocTikNum]            NVARCHAR (4000) NULL,
    [UsedTikNum]             NVARCHAR (4000) NULL,
    [Width]                  REAL            NULL,
    [FootLength]             INT             NULL,
    [PrintFlag]              BIT             NULL,
    [Location]               NVARCHAR (4000) NULL,
    [Description]            NVARCHAR (4000) NULL,
    [Upload1]                BIT             NULL,
    [Upload2]                BIT             NULL,
    [DeleteFlag]             BIT             NULL,
    [RollNum]                SMALLINT        NULL,
    [StkDate]                DATETIME        NULL,
    [StkUsed]                BIT             NULL,
    [Slitted]                BIT             NULL,
    [SlitFootage]            INT             NULL,
    [CostMSI]                REAL            NULL,
    [CostOfRoll]             REAL            NULL,
    [DateRollUsed]           DATETIME        NULL,
    [ALT_IDNumber]           NVARCHAR (4000) NULL,
    [FassonShipID]           INT             NULL,
    [CreatedDate]            DATETIME        NULL,
    [OpStamp]                NVARCHAR (4000) NULL,
    [DateStamp]              DATETIME        NULL,
    [Used_TimeStamp]         TIME (7)        NULL,
    [Allocated_CB]           BIT             NULL,
    [Coated_By]              NVARCHAR (4000) NULL,
    [Coated_Date]            DATETIME        NULL,
    [Coated_Time]            TIME (7)        NULL,
    [Orig_RollID]            NVARCHAR (4000) NULL,
    [Press]                  NVARCHAR (4000) NULL,
    [PK_UUID]                NVARCHAR (4000) NULL,
    [Currency_ID]            INT             NULL,
    [Orig_Curr_ExchangeRate] REAL            NULL,
    [FC_CostMSI]             REAL            NULL,
    [Tag]                    VARCHAR(36)     NULL,
    [UpdateTimeDateStamp]     DATETIME        NULL
);

