CREATE TABLE [dbo].[Stock] (
    [StockNum]                  NVARCHAR (4000)  NULL,
    [Classification]            NVARCHAR (4000) NULL,
    [SupplierNum]               NVARCHAR (4000) NULL,
    [MFGSpecNum]                NVARCHAR (4000) NULL,
    [MasterWidth]               REAL            NULL,
    [CostMSI]                   REAL            NULL,
    [FaceStock]                 NVARCHAR (4000) NULL,
    [FaceColor]                 NVARCHAR (4000) NULL,
    [FaceCaliper]               NVARCHAR (4000) NULL,
    [LinerCaliper]              NVARCHAR (4000) NULL,
    [Adhesive]                  NVARCHAR (4000) NULL,
    [AdhClass]                  NVARCHAR (4000) NULL,
    [TotalInvMSI]               REAL            NULL,
    [InventoryCost]             REAL            NULL,
    [ULRecognized]              BIT             NULL,
    [CSACertified]              BIT             NULL,
    [TopCoat]                   NVARCHAR (4000) NULL,
    [FreightMSI]                REAL            NULL,
    [Notes]                     NVARCHAR (4000) NULL,
    [Inactive]                  BIT             NULL,
    [SupplierName]              NVARCHAR (4000) NULL,
    [Location]                  NVARCHAR (4000) NULL,
    [Caliper]                   REAL            NULL,
    [InternetQuery]             BIT             NULL,
    [EnteredBy]                 NVARCHAR (4000) NULL,
    [ModifiedBy]                NVARCHAR (4000) NULL,
    [EnteredDate]               DATETIME        NULL,
    [ModifiedDate]              DATETIME        NULL,
    [EnteredTime]               TIME (7)        NULL,
    [ModifiedTime]              TIME (7)        NULL,
    [InvMSI_Minimum]            REAL            NULL,
    [InvMSI_Maximum]            REAL            NULL,
    [VPB_VolumeTo_1]            INT             NULL,
    [VPB_VolumeTo_2]            INT             NULL,
    [VPB_VolumeTo_3]            INT             NULL,
    [VPB_VolumeTo_4]            INT             NULL,
    [VPB_VolumeFrom_2]          INT             NULL,
    [VPB_VolumeFrom_3]          INT             NULL,
    [VPB_VolumeFrom_4]          INT             NULL,
    [VPB_VolumeFrom_5]          INT             NULL,
    [VPB_CostMSI_2]             REAL            NULL,
    [VPB_CostMSI_3]             REAL            NULL,
    [VPB_CostMSI_4]             REAL            NULL,
    [VPB_CostMSI_5]             REAL            NULL,
    [VPB_FreightMSI_2]          REAL            NULL,
    [VPB_FreightMSI_3]          REAL            NULL,
    [VPB_FreightMSI_4]          REAL            NULL,
    [VPB_FreightMSI_5]          REAL            NULL,
    [StockSubstitute_1]         NVARCHAR (4000) NULL,
    [StockSubstitute_2]         NVARCHAR (4000) NULL,
    [StockSubstitute_3]         NVARCHAR (4000) NULL,
    [EstimatedDeliveryTime]     NVARCHAR (4000) NULL,
    [LinkToDataSheet]           NVARCHAR (4000) NULL,
    [Notes_Other]               NVARCHAR (4000) NULL,
    [StockSubstitute_Notes]     NVARCHAR (4000) NULL,
    [PriceSpecifiedForEstimate] BIT             NULL,
    [PriceChangeBy]             NVARCHAR (4000) NULL,
    [PriceChangeDate]           DATETIME        NULL,
    [PriceChangeTime]           TIME (7)        NULL,
    [AreaToWeightFactor]        REAL            NULL,
    [VPB_VolumeTo_5]            INT             NULL,
    [VPB_VolumeFrom_6]          INT             NULL,
    [VPB_CostMSI_6]             REAL            NULL,
    [VPB_FreightMSI_6]          REAL            NULL,
    [VolumePriceForEstimates]   INT             NULL,
    [Is_Used_by_eStore]         BIT             NULL,
    [eTraxx_Description]        NVARCHAR (4000) NULL,
    [Is_OverLaminate]           BIT             NULL,
    [Yield_Area_Weight]         REAL            NULL,
    [Price_Weight]              REAL            NULL,
    [IsCoated_DigitalPress]     BIT             NULL,
    [StockNum_Uncoated]         NVARCHAR (4000) NULL,
    [StockNum_Coated]           NVARCHAR (4000) NULL,
    [Indigo_Type]               NVARCHAR (4000) NULL,
    [PK_UUID]                   NVARCHAR (4000) NULL,
    [Default_CoreSize]          REAL            NULL,
    [Currency_ID]               INT             NULL,
    [FX_VPB_CostMSI_1]          REAL            NULL,
    [FX_VPB_CostMSI_2]          REAL            NULL,
    [FX_VPB_CostMSI_3]          REAL            NULL,
    [FX_VPB_CostMSI_4]          REAL            NULL,
    [FX_VPB_CostMSI_5]          REAL            NULL,
    [FX_VPB_CostMSI_6]          REAL            NULL,
    [FX_VPB_FreightMSI_1]       REAL            NULL,
    [FX_VPB_FreightMSI_2]       REAL            NULL,
    [FX_VPB_FreightMSI_3]       REAL            NULL,
    [FX_VPB_FreightMSI_4]       REAL            NULL,
    [FX_VPB_FreightMSI_5]       REAL            NULL,
    [FX_VPB_FreightMSI_6]       REAL            NULL,
    [Currency_ExchangeRate]     REAL            NULL,
    [Total_InventoryWeight]     REAL            NULL,
    [FC_Price_Weight]           REAL            NULL,
    [UpdateTimeDateStamp]     DATETIME        NULL
);

