CREATE TABLE [dbo].[StockProduct] (
    [ID]                             NVARCHAR (255) NOT NULL,
    [PRODUCTNO]                      NVARCHAR (4000) NULL,
    [PRODCLASS]                      NVARCHAR (4000) NULL,
    [PRODSUBCLASS]                   NVARCHAR (4000) NULL,
    [SUPPLIERNAME]                   NVARCHAR (4000) NULL,
    [SUPPLIERNO]                     NVARCHAR (4000) NULL,
    [DESC1]                          NVARCHAR (4000) NULL,
    [DESC2]                          NVARCHAR (4000) NULL,
    [NOTES]                          NVARCHAR (4000) NULL,
    [AVAILABLE]                      INT             NULL,
    [TOTALCOST]                      REAL            NULL,
    [MINPRODUCE]                     INT             NULL,
    [MAXPRODUCE]                     INT             NULL,
    [PHYSICALINV]                    INT             NULL,
    [ONORDER]                        INT             NULL,
    [PACKAGEQTY]                     INT             NULL,
    [LOCATION]                       NVARCHAR (4000) NULL,
    [PRICEMODE]                      NVARCHAR (4000) NULL,
    [SUPPLIERPARTNO]                 NVARCHAR (4000) NULL,
    [SUPPLIERNOTES]                  NVARCHAR (4000) NULL,
    [COST]                           REAL            NULL,
    [CASEQTY]                        NVARCHAR (4000) NULL,
    [BACKORDERED]                    INT             NULL,
    [COLOR]                          NVARCHAR (4000) NULL,
    [MATERIAL]                       NVARCHAR (4000) NULL,
    [ADHESIVE]                       NVARCHAR (4000) NULL,
    [ALTERNATE]                      NVARCHAR (4000) NULL,
    [CUSTOMER_NUM]                   NVARCHAR (4000) NULL,
    [CUSTOMERNAME]                   NVARCHAR (4000) NULL,
    [UPDATED]                        DATETIME        NULL,
    [PART_TYPE]                      NVARCHAR (4000) NULL,
    [INACTIVE]                       BIT             NULL,
    [UPC]                            NVARCHAR (4000) NULL,
    [PRODUCT_UNIQUEPRODID]           NVARCHAR (4000) NULL,
    [PRODUCTION_WASTE]               REAL            NULL,
    [ENTEREDBY]                      NVARCHAR (4000) NULL,
    [MODIFIEDBY]                     NVARCHAR (4000) NULL,
    [ENTEREDDATE]                    DATETIME        NULL,
    [MODIFIEDDATE]                   DATETIME        NULL,
    [ENTEREDTIME]                    TIME (7)        NULL,
    [MODIFIEDTIME]                   TIME (7)        NULL,
    [LINK_FACTOR]                    REAL            NULL,
    [INVENTORY_EXPIRES]              INT             NULL,
    [WEIGHT]                         REAL            NULL,
    [BOX_SIZE]                       NVARCHAR (4000) NULL,
    [INTERNETQUERY]                  BIT             NULL,
    [ETRAXX_FORECAST_RANGE]          NVARCHAR (4000) NULL,
    [ETRAXX_FORECAST_QUANTITY]       INT             NULL,
    [RELEASES_ALLOWED_DEFAULT]       INT             NULL,
    [COMMISSION]                     REAL            NULL,
    [IS_LOCATION_USEDBY_CONSIGNMENT] BIT             NULL,
    [IS_LINKEDCUSTOMPRICESUSED]      BIT             NULL,
    [PRICEMODE_LOCAL]                NVARCHAR (4000) NULL,
    [PK_UUID]                        NVARCHAR (4000) NULL,
    [PICTDISPLAYFORMAT]              NVARCHAR (4000) NULL,
    [FILE_NAME]                      NVARCHAR (4000) NULL,
    [UpdateTimeDateStamp]     DATETIME        NULL
);

