CREATE TABLE [dbo].[Ticket] (
    [Number]                        NVARCHAR (255)  NOT NULL,
    [OrderDate]                     DATETIME        NULL,
    [Ship_by_Date]                  DATETIME        NULL,
    [ArtStat]                       NVARCHAR (4000) NULL,
    [ProofStat]                     NVARCHAR (4000) NULL,
    [PlateStat]                     NVARCHAR (4000) NULL,
    [ToolStat]                      NVARCHAR (4000) NULL,
    [HashIndex]                     NVARCHAR (4000) NULL,
    [PressStat]                     NVARCHAR (4000) NULL,
    [FinishStat]                    NVARCHAR (4000) NULL,
    [ShipStat]                      NVARCHAR (4000) NULL,
    [ArtDone]                       BIT             NULL,
    [ProofDone]                     BIT             NULL,
    [PlateDone]                     BIT             NULL,
    [ToolsIn]                       BIT             NULL,
    [StockIn]                       NVARCHAR (4000) NULL,
    [PressDone]                     BIT             NULL,
    [FinishDone]                    BIT             NULL,
    [NoPlateChanges]                INT             NULL,
    [PrevJobNum]                    NVARCHAR (4000) NULL,
    [GeneralDescr]                  NVARCHAR (4000) NULL,
    [EstTime]                       REAL            NULL,
    [CarrierWidth]                  REAL            NULL,
    [OnTime]                        BIT             NULL,
    [SizeAcross]                    REAL            NULL,
    [SizeAround]                    REAL            NULL,
    [ColSpace]                      REAL            NULL,
    [RowSpace]                      REAL            NULL,
    [LabelRepeat]                   REAL            NULL,
    [NoAcross]                      SMALLINT        NULL,
    [NoArounPlate]                  SMALLINT        NULL,
    [NoColorChanges]                INT             NULL,
    [FinishType]                    NVARCHAR (4000) NULL,
    [Pinfeed]                       BIT             NULL,
    [LabelsPer_]                    INT             NULL,
    [NoLabAcrossFin]                SMALLINT        NULL,
    [CoreSize]                      REAL            NULL,
    [FinalUnwind]                   NVARCHAR (4000) NULL,
    [LabelsPerFold]                 SMALLINT        NULL,
    [SheetPacktype]                 NVARCHAR (4000) NULL,
    [Tab]                           REAL            NULL,
    [Press]                         NVARCHAR (4000) NULL,
    [MainTool]                      NVARCHAR (4000) NULL,
    [CustPONum]                     NVARCHAR (4000) NULL,
    [TurnBar]                       BIT             NULL,
    [Image_Rotation]                NVARCHAR (4000) NULL,
    [ColumnPerf]                    REAL            NULL,
    [RowPerf]                       REAL            NULL,
    [OverRun]                       REAL            NULL,
    [AutoAppl]                      BIT             NULL,
    [CustomerNum]                   NVARCHAR (4000) NULL,
    [EndUserNum]                    NVARCHAR (4000) NULL,
    [StockNum1]                     NVARCHAR (4000) NULL,
    [StockWidth1]                   REAL            NULL,
    [EstFootage]                    INT             NULL,
    [StockNum2]                     NVARCHAR (4000) NULL,
    [StockWidth2]                   REAL            NULL,
    [ToolNo2]                       NVARCHAR (4000) NULL,
    [StockNum3]                     NVARCHAR (4000) NULL,
    [StockWidth3]                   REAL            NULL,
    [Tool2Descr]                    NVARCHAR (4000) NULL,
    [ITSAssocNum]                   NVARCHAR (4000) NULL,
    [OTSAssocNum]                   NVARCHAR (4000) NULL,
    [ShipVia]                       NVARCHAR (4000) NULL,
    [ShippingInstruc]               NVARCHAR (4000) NULL,
    [ShipAttn]                      NVARCHAR (4000) NULL,
    [MFGRepNum]                     NVARCHAR (4000) NULL,
    [MFGRepComm]                    REAL            NULL,
    [Notes]                         NVARCHAR (4000) NULL,
    [DateDone]                      DATETIME        NULL,
    [ShipAttn_EmailAddress]         NVARCHAR (4000) NULL,
    [ShipLocation]                  NVARCHAR (4000) NULL,
    [ShipAddr1]                     NVARCHAR (4000) NULL,
    [ShipAddr2]                     NVARCHAR (4000) NULL,
    [ShipCity]                      NVARCHAR (4000) NULL,
    [ShipSt]                        NVARCHAR (4000) NULL,
    [ShipZip]                       NVARCHAR (4000) NULL,
    [BillLocation]                  NVARCHAR (4000) NULL,
    [BillAddr1]                     NVARCHAR (4000) NULL,
    [BillAddr2]                     NVARCHAR (4000) NULL,
    [BillCity]                      NVARCHAR (4000) NULL,
    [BillZip]                       NVARCHAR (4000) NULL,
    [BillCountry]                   NVARCHAR (4000) NULL,
    [ShippingStatus]                NVARCHAR (4000) NULL,
    [ShipCountry]                   NVARCHAR (4000) NULL,
    [StockTicketType]               SMALLINT        NULL,
    [SalesCommission]               REAL            NULL,
    [Stock_Allocated]               BIT             NULL,
    [EndUserPO]                     NVARCHAR (4000) NULL,
    [CustomerName]                  NVARCHAR (4000) NULL,
    [ToolNo3]                       NVARCHAR (4000) NULL,
    [Tool3Descr]                    NVARCHAR (4000) NULL,
    [ToolNo4]                       NVARCHAR (4000) NULL,
    [Tool4Descr]                    NVARCHAR (4000) NULL,
    [ToolNo5]                       NVARCHAR (4000) NULL,
    [Tool5Descr]                    NVARCHAR (4000) NULL,
    [CornerRadius]                  REAL            NULL,
    [DateShipped]                   DATETIME        NULL,
    [OTSName]                       NVARCHAR (4000) NULL,
    [TicketType]                    SMALLINT        NULL,
    [TicQuantity]                   INT             NULL,
    [ITSName]                       NVARCHAR (4000) NULL,
    [ActFootage]                    INT             NULL,
    [EstMRHrs]                      REAL            NULL,
    [ActMRHrs]                      REAL            NULL,
    [EstWuHrs]                      REAL            NULL,
    [ActWuHrs]                      REAL            NULL,
    [ShipAsOne]                     BIT             NULL,
    [EarlyShipOK]                   BIT             NULL,
    [EstRunHrs]                     REAL            NULL,
    [ActRunHrs]                     REAL            NULL,
    [EstFinHrs]                     REAL            NULL,
    [ActualFanfoldHours]            REAL            NULL,
    [EstPackHrs]                    REAL            NULL,
    [ActPackHrs]                    REAL            NULL,
    [EstPressSpd]                   SMALLINT        NULL,
    [ActPressSpd]                   SMALLINT        NULL,
    [ActQuantity]                   INT             NULL,
    [Act_MakeReady_Footage]         INT             NULL,
    [Is_Ink_In]                     BIT             NULL,
    [Ink_Status]                    NVARCHAR (4000) NULL,
    [EstTotal]                      REAL            NULL,
    [ActTotalCost]                  REAL            NULL,
    [EstStockCost]                  REAL            NULL,
    [ActStockCost]                  REAL            NULL,
    [EstFinMaterial]                REAL            NULL,
    [ActFinMaterial]                REAL            NULL,
    [BillCounty]                    NVARCHAR (4000) NULL,
    [EstArtwork]                    REAL            NULL,
    [ActArtwork]                    REAL            NULL,
    [Shape]                         NVARCHAR (4000) NULL,
    [TabPosition]                   BIT             NULL,
    [LastModified]                  DATETIME        NULL,
    [StockDesc1]                    NVARCHAR (4000) NULL,
    [StockDesc2]                    NVARCHAR (4000) NULL,
    [StockDesc3]                    NVARCHAR (4000) NULL,
    [EndUserName]                   NVARCHAR (4000) NULL,
    [MFGRepName]                    NVARCHAR (4000) NULL,
    [BillState]                     NVARCHAR (4000) NULL,
    [CustContact]                   NVARCHAR (4000) NULL,
    [CSA]                           BIT             NULL,
    [UL]                            BIT             NULL,
    [ConsecNo]                      BIT             NULL,
    [POTotal]                       REAL            NULL,
    [TicketStatus]                  NVARCHAR (4000) NULL,
    [PlateChangeCost]               REAL            NULL,
    [ColorChangeCost]               REAL            NULL,
    [MiscChargeDesc]                NVARCHAR (4000) NULL,
    [MiscCharge]                    REAL            NULL,
    [CoreType]                      NVARCHAR (4000) NULL,
    [RollLength]                    INT             NULL,
    [RollUnit]                      NVARCHAR (4000) NULL,
    [Tape]                          BIT             NULL,
    [PriceMode]                     NVARCHAR (4000) NULL,
    [StockProdDiscnt]               REAL            NULL,
    [Total_LineWeight]              REAL            NULL,
    [UserDef_MR_1]                  BIT             NULL,
    [UserDef_MR_2]                  BIT             NULL,
    [UserDef_MR_1_Lb]               NVARCHAR (4000) NULL,
    [UserDef_MR_2_Lb]               NVARCHAR (4000) NULL,
    [Priority]                      NVARCHAR (4000) NULL,
    [OutsideDiameter]               REAL            NULL,
    [FinishNotes]                   NVARCHAR (4000) NULL,
    [EstPressTime]                  REAL            NULL,
    [RewindEquipNum]                NVARCHAR (4000) NULL,
    [RewindEquipNam]                NVARCHAR (4000) NULL,
    [SubTicket]                     BIT             NULL,
    [AmortizePlateChanges]          BIT             NULL,
    [AmortizeColorChanges]          BIT             NULL,
    [EntryBy]                       NVARCHAR (4000) NULL,
    [EntryDate]                     DATETIME        NULL,
    [Terms]                         NVARCHAR (4000) NULL,
    [ActualPressHours]              REAL            NULL,
    [ActualTotalHours]              REAL            NULL,
    [ActualPressRate]               REAL            NULL,
    [ActualPressCost]               REAL            NULL,
    [ActualRewindingRate]           REAL            NULL,
    [ActualRewindingCost]           REAL            NULL,
    [ActualFanfoldRate]             REAL            NULL,
    [ActualFanFoldCost]             REAL            NULL,
    [ActualPackagingRate]           REAL            NULL,
    [ActualPackingLaborCost]        REAL            NULL,
    [ActualNumOfStockRolls]         REAL            NULL,
    [ActualFootage_StockRolls]      REAL            NULL,
    [ActualMSI_StockRolls]          REAL            NULL,
    [ActualBillings_NetOfSalesTax]  REAL            NULL,
    [ActualGrossMargin_Dollars]     REAL            NULL,
    [ActualGrossMargin_Percent]     REAL            NULL,
    [ActualRewindingHours]          REAL            NULL,
    [ActualTotalFinishing]          REAL            NULL,
    [ActualTotalLaborCosts]         REAL            NULL,
    [ActualTotalPOCosts]            REAL            NULL,
    [ActualTotalMatAndFreightCost]  REAL            NULL,
    [Est_SetupFootage]              INT             NULL,
    [Est_SpoilFootage]              INT             NULL,
    [ShipCounty]                    NVARCHAR (4000) NULL,
    [Est_v_Act_Notes]               NVARCHAR (4000) NULL,
    [EstPostPressHours]             REAL            NULL,
    [ActPostPressHours]             REAL            NULL,
    [Act_OTHER_Hours]               REAL            NULL,
    [ActualPostPressLaborCost]      REAL            NULL,
    [CustContact_ID]                NVARCHAR (4000) NULL,
    [StockNotes]                    NVARCHAR (4000) NULL,
    [SoldToEndUser]                 BIT             NULL,
    [Sheet_Width]                   REAL            NULL,
    [Sheet_Height]                  REAL            NULL,
    [SlitOnRewind]                  BIT             NULL,
    [ActualOtherLaborCost]          REAL            NULL,
    [ActualCommissionsCost]         REAL            NULL,
    [Is_AutoOrder]                  BIT             NULL,
    [Ship_Address_ID]               NVARCHAR (4000) NULL,
    [Ship_TaxRegion_ID]             INT             NULL,
    [Bill_Address_ID]               NVARCHAR (4000) NULL,
    [Bill_TaxRegion_ID]             INT             NULL,
    [Internet_Submission]           BIT             NULL,
    [EntryTime]                     TIME (7)        NULL,
    [ModifyTime]                    TIME (7)        NULL,
    [ModifyBy]                      NVARCHAR (4000) NULL,
    [ModifyDate]                    DATETIME        NULL,
    [Equip_ID]                      NVARCHAR (4000) NULL,
    [Are_Tools_for_Equip]           BIT             NULL,
    [Equip_MakeReadyHours]          REAL            NULL,
    [Equip_WashUpHours]             REAL            NULL,
    [Equip_EstSpeed]                INT             NULL,
    [Equip_EstRunHrs]               REAL            NULL,
    [Equip_Actual_MR_Hours]         REAL            NULL,
    [Equip_Actual_MR_Length]        INT             NULL,
    [Equip_Actual_Length]           INT             NULL,
    [Equip_Actual_Run_Hours]        REAL            NULL,
    [Equip_Actual_WU_Hours]         REAL            NULL,
    [Equip_Actual_Speed]            INT             NULL,
    [Equip_EstTime]                 REAL            NULL,
    [Equip_Actual_Hours]            REAL            NULL,
    [Equip_Actual_Rate]             REAL            NULL,
    [Equip_Actual_Cost]             REAL            NULL,
    [Equip_Status]                  NVARCHAR (4000) NULL,
    [Equip_Done]                    BIT             NULL,
    [Due_on_Site_Date]              DATETIME        NULL,
    [CreditHoldOverride]            BIT             NULL,
    [Calculation_TimeStamp]         INT             NULL,
    [Use_TurretRewinder]            BIT             NULL,
    [Is_ActBillNetTax_UserModified] BIT             NULL,
    [Currency_ID]                   INT             NULL,
    [Currency_ExchangeRate]         REAL            NULL,
    [ESC_Art]                       BIT             NULL,
    [ESC_Proof]                     BIT             NULL,
    [ESC_Plate]                     BIT             NULL,
    [ESC_Tool]                      BIT             NULL,
    [ESC_Ink]                       BIT             NULL,
    [ESC_Stock]                     BIT             NULL,
    [ESC_Press]                     BIT             NULL,
    [ESC_Equip]                     BIT             NULL,
    [ESC_Finish]                    BIT             NULL,
    [ESC_Ship]                      BIT             NULL,
    [ESC_TickStat]                  BIT             NULL,
    [ESS_Ship]                      BIT             NULL,
    [ESS_TickStat]                  BIT             NULL,
    [ES_CSR]                        BIT             NULL,
    [ES_SalesRep]                   BIT             NULL,
    [ShrinkSleeve_OverLap]          REAL            NULL,
    [ShrinkSleeve_LayFlat]          REAL            NULL,
    [ShrinkSleeve_CutHeight]        REAL            NULL,
    [Freight_AcctNo]                NVARCHAR (4000) NULL,
    [BackStage_ColorStrategy]       NVARCHAR (4000) NULL,
    [BackStage_SmartMarkSet]        NVARCHAR (4000) NULL,
    [Equip3_ID]                     NVARCHAR (4000) NULL,
    [Equip3_MakeReadyHours]         REAL            NULL,
    [Equip3_WashUpHours]            REAL            NULL,
    [Equip3_EstSpeed]               INT             NULL,
    [Equip3_EstRunHrs]              REAL            NULL,
    [Equip3_EstTime]                REAL            NULL,
    [Equip3_Actual_Length]          INT             NULL,
    [Equip3_Actual_MR_Length]       INT             NULL,
    [Equip3_Actual_Speed]           INT             NULL,
    [Equip3_Actual_MR_Hours]        REAL            NULL,
    [Equip3_Actual_Run_Hours]       REAL            NULL,
    [Equip3_Actual_WU_Hours]        REAL            NULL,
    [Equip3_Actual_Hours]           REAL            NULL,
    [Equip3_Actual_Rate]            REAL            NULL,
    [Equip3_Actual_Cost]            REAL            NULL,
    [Equip3_Status]                 NVARCHAR (4000) NULL,
    [Equip3_Done]                   BIT             NULL,
    [Equip4_ID]                     NVARCHAR (4000) NULL,
    [Equip4_MakeReadyHours]         REAL            NULL,
    [Equip4_WashUpHours]            REAL            NULL,
    [Equip4_EstSpeed]               INT             NULL,
    [Equip4_EstRunHrs]              REAL            NULL,
    [Equip4_EstTime]                REAL            NULL,
    [Equip4_Actual_Length]          INT             NULL,
    [Equip4_Actual_MR_Length]       INT             NULL,
    [Equip4_Actual_Speed]           INT             NULL,
    [Equip4_Actual_MR_Hours]        REAL            NULL,
    [Equip4_Actual_Run_Hours]       REAL            NULL,
    [Equip4_Actual_WU_Hours]        REAL            NULL,
    [Equip4_Actual_Hours]           REAL            NULL,
    [Equip4_Actual_Rate]            REAL            NULL,
    [Equip4_Actual_Cost]            REAL            NULL,
    [Equip4_Status]                 NVARCHAR (4000) NULL,
    [Equip4_Done]                   BIT             NULL,
    [BackStage_DefaultReportForm]   NVARCHAR (4000) NULL,
    [ESC_Equip3]                    BIT             NULL,
    [ESC_Equip4]                    BIT             NULL,
    [Equip_NoAcross]                INT             NULL,
    [Equip_NoAround]                INT             NULL,
    [Equip_NumUp_Multiplier]        INT             NULL,
    [Equip3_NoAcross]               INT             NULL,
    [Equip3_NoAround]               INT             NULL,
    [Equip3_NumUp_Multiplier]       INT             NULL,
    [Equip4_NoAcross]               INT             NULL,
    [Equip4_NoAround]               INT             NULL,
    [Equip4_NumUp_Multiplier]       INT             NULL,
    [JDF_Sent_On]                   NVARCHAR (4000) NULL,
    [Tool_NumberAround]             SMALLINT        NULL,
    [Roto_Quote_Number]             NVARCHAR (4000) NULL,
    [Roto_Quote_Line_ID]            NVARCHAR (4000) NULL,
    [ID]                            INT             NULL,
    [Screen_Ratio]                  NVARCHAR (4000) NULL,
    [Schedule_Status]               NVARCHAR (4000) NULL,
    [Roto_CEL_Product_ID]           NVARCHAR (4000) NULL,
    [JDF_Note_to_DFE]               NVARCHAR (4000) NULL,
    [TicketStatus_Local]            NVARCHAR (4000) NULL,
    [TicketType_Local]              NVARCHAR (4000) NULL,
    [Currency_Rate_ID]              INT             NULL,
    [StockIn_Local]                 NVARCHAR (4000) NULL,
    [FC_PlateChangeCost]            REAL            NULL,
    [FC_ColorChangeCost]            REAL            NULL,
    [FC_MiscCharge]                 REAL            NULL,
    [FC_EstTotal]                   REAL            NULL,
    [FC_POTotal]                    REAL            NULL,
    [PlateChangeCost_Extended]      REAL            NULL,
    [FC_PlateChangeCost_Extended]   REAL            NULL,
    [ColorChangeCost_Extended]      REAL            NULL,
    [FC_ColorChangeCost_Extended]   REAL            NULL,
    [Customer_Total]                REAL            NULL,
    [FC_Customer_Total]             REAL            NULL,
    [JDF_Send_Msg]                  NVARCHAR (4000) NULL,
    [ESC_Art_Sales]                 BIT             NULL,
    [ESC_Equip_Sales]               BIT             NULL,
    [ESC_Equip3_Sales]              BIT             NULL,
    [ESC_Equip4_Sales]              BIT             NULL,
    [ESC_Finish_Sales]              BIT             NULL,
    [ESC_Ink_Sales]                 BIT             NULL,
    [ESC_Plate_Sales]               BIT             NULL,
    [ESC_Press_Sales]               BIT             NULL,
    [ESC_Ship_Sales]                BIT             NULL,
    [ESC_Stock_Sales]               BIT             NULL,
    [ESC_TickStat_Sales]            BIT             NULL,
    [ESC_Tool_Sales]                BIT             NULL,
    [ESC_Proof_sales]               BIT             NULL,
    [ESS_Ship_Sales]                BIT             NULL,
    [ESS_TickStat_Sales]            BIT             NULL,
    [MiscChargeDesc1]               NVARCHAR (4000) NULL,
    [MiscChargeDesc2]               NVARCHAR (4000) NULL,
    [MiscChargeDesc3]               NVARCHAR (4000) NULL,
    [MiscChargeDesc4]               NVARCHAR (4000) NULL,
    [MiscCharge1]                   REAL            NULL,
    [MiscCharge2]                   REAL            NULL,
    [MiscCharge3]                   REAL            NULL,
    [MiscCharge4]                   REAL            NULL,
    [FC_MiscCharge1]                REAL            NULL,
    [FC_MiscCharge2]                REAL            NULL,
    [FC_MiscCharge3]                REAL            NULL,
    [FC_MiscCharge4]                REAL            NULL,
    [Frames_Lead_In]                INT             NULL,
    [Frames_Lead_Out]               INT             NULL,
    [PK_UUID]                       NVARCHAR (4000) NULL,
    [IsPrintReversed]               BIT             NULL,
    [FlexPack_Type]                 INT             NULL,
    [TotalOrderWeight]              REAL            NULL,
    [TotalShipWeight]               REAL            NULL,
    [FlexPack_Height]               REAL            NULL,
    [FlexPack_Gusset]               REAL            NULL,
    [FlexPack_LeftTrim]             REAL            NULL,
    [FlexPack_RightTrim]            REAL            NULL,
    [UpdateTimeDateStamp]           DATETIME        NULL,
    [Equip5_ID]                     NVARCHAR (4000) NULL,
    [Equip5_Done]                   BIT             NULL,
    [Equip5_EstTime]                REAL            NULL,
    [Equip5_EstRunHrs]              REAL            NULL,
    [Equip5_WashUpHours]            REAL            NULL,
    [Equip5_MakeReadyHours]         REAL            NULL,
    [Equip6_ID]                     NVARCHAR (4000) NULL,
    [Equip6_Done]                   BIT             NULL,
    [Equip6_EstTime]                REAL            NULL,
    [Equip6_EstRunHrs]              REAL            NULL,
    [Equip6_WashUpHours]            REAL            NULL,
    [Equip6_MakeReadyHours]         REAL            NULL,
    [Tag]                           NVARCHAR (4000) NULL,
    CONSTRAINT [PK_TicketNumber] PRIMARY KEY CLUSTERED ([Number] ASC)
);


GO
CREATE NONCLUSTERED INDEX [_dta_index_Ticket_8_1683693246__K145_K100_1]
    ON [dbo].[Ticket]([TicketStatus] ASC, [TicketType] ASC)
    INCLUDE([Number]);


GO
CREATE NONCLUSTERED INDEX [NCI_Ticket_NumStatMainTool]
    ON [dbo].[Ticket]([Number] ASC, [TicketStatus] ASC, [MainTool] ASC);


GO
CREATE NONCLUSTERED INDEX [NCI_Ticket_NumStatTool2]
    ON [dbo].[Ticket]([Number] ASC, [TicketStatus] ASC, [ToolNo2] ASC);


GO
CREATE NONCLUSTERED INDEX [NCI_Ticket_NumStatTool3]
    ON [dbo].[Ticket]([Number] ASC, [TicketStatus] ASC, [ToolNo3] ASC);


GO
CREATE NONCLUSTERED INDEX [NCI_Ticket_NumStatTool4]
    ON [dbo].[Ticket]([Number] ASC, [TicketStatus] ASC, [ToolNo4] ASC);


GO
CREATE NONCLUSTERED INDEX [NCI_Ticket_OrderDateTicketType]
    ON [dbo].[Ticket]([OrderDate] ASC, [TicketType] ASC);

GO
CREATE NONCLUSTERED INDEX [NCI_Ticket_CustNumDtShippedTicketType]
    ON [dbo].[Ticket] ([DateShipped],[TicketType])
    INCLUDE ([CustomerNum])
