CREATE TABLE [dbo].[TicketItem] (
    [ID]                    NVARCHAR (255)  NOT NULL,
    [TICKETNUMBER]          NVARCHAR (4000) NULL,
    [PRODUCTNUMBER]         NVARCHAR (4000) NULL,
    [DESCRIPTION]           NVARCHAR (4000) NULL,
    [NOCOLORS]              SMALLINT        NULL,
    [COLORDESCR]            NVARCHAR (4000) NULL,
    [NOFLOODS]              SMALLINT        NULL,
    [DESC2]                 NVARCHAR (4000) NULL,
    [ORDERQUANTITY]         INT             NULL,
    [MACHINECOUNT]          INT             NULL,
    [JOBTYPE]               NVARCHAR (4000) NULL,
    [LOCATION]              NVARCHAR (4000) NULL,
    [COSTM]                 REAL            NULL,
    [CONSECNO]              NVARCHAR (4000) NULL,
    [PRICEM]                REAL            NULL,
    [UNIQUEPRICE]           BIT             NULL,
    [PRICEMODE]             NVARCHAR (4000) NULL,
    [STOCKPRODUCTID]        NVARCHAR (4000) NULL,
    [LINETOTAL]             REAL            NULL,
    [STCKPRDSHIPSTAT]       NVARCHAR (4000) NULL,
    [UNIQUEPRODID]          NVARCHAR (4000) NULL,
    [EQUIP_NOCOLORS]        SMALLINT        NULL,
    [EQUIP_NOFLOODS]        SMALLINT        NULL,
    [PO_NUMBER]             NVARCHAR (4000) NULL,
    [UNIT_WEIGHT]           REAL            NULL,
    [LINE_WEIGHT]           REAL            NULL,
    [WORK_STATUS]           NVARCHAR (4000) NULL,
    [ASSIGNED]              NVARCHAR (4000) NULL,
    [ART]                   BIT             NULL,
    [PROOF]                 BIT             NULL,
    [PLATE]                 BIT             NULL,
    [ART_TICKET]            BIT             NULL,
    [PROOF_TICKET]          BIT             NULL,
    [PLATE_TICKET]          BIT             NULL,
    [ART_ITEM]              BIT             NULL,
    [PROOF_ITEM]            BIT             NULL,
    [PLATE_ITEM]            BIT             NULL,
    [PROOF_OUT]             DATETIME        NULL,
    [PRESS_NULL_CYCLES]     INT             NULL,
    [EQUIP_NULL_CYCLES]     INT             NULL,
    [ETRAXX_CUSTOMER_NOTES] NVARCHAR (4000) NULL,
    [EQUIP3_NOCOLORS]       SMALLINT        NULL,
    [EQUIP3_NOFLOODS]       SMALLINT        NULL,
    [EQUIP3_NULL_CYCLES]    SMALLINT        NULL,
    [EQUIP4_NOCOLORS]       SMALLINT        NULL,
    [EQUIP4_NOFLOODS]       SMALLINT        NULL,
    [EQUIP4_NULL_CYCLES]    SMALLINT        NULL,
    [FC_PRICEM]             REAL            NULL,
    [FC_LINETOTAL]          REAL            NULL,
    [JOBTYPE_LOCAL]         NVARCHAR (4000) NULL,
    [PK_UUID]               NVARCHAR (4000) NULL,
    [UpdateTimeDateStamp]     DATETIME        NULL
);


GO
CREATE NONCLUSTERED INDEX [NCI_TicketItem_TktNumUniqueProID]
    ON [dbo].[TicketItem]([TicketNumber] ASC)
    INCLUDE([UniqueProdID]);

