CREATE TABLE [dbo].[Tooling] (
    [Number]             NVARCHAR (4000) NULL,
    [Flexo_HotS]         NVARCHAR (4000) NULL,
    [DieSize]            REAL            NULL,
    [SizeAcross]         REAL            NULL,
    [SizeAround]         REAL            NULL,
    [ColSpace]           REAL            NULL,
    [RowSpace]           REAL            NULL,
    [NoAcross]           SMALLINT        NULL,
    [NoAround]           SMALLINT        NULL,
    [LabelRepeat]        REAL            NULL,
    [GearTeeth]          SMALLINT        NULL,
    [Pitch]              NVARCHAR (4000) NULL,
    [Shape]              NVARCHAR (4000) NULL,
    [AutoApplied]        BIT             NULL,
    [DieCut]             SMALLINT        NULL,
    [LinerCaliper]       NVARCHAR (4000) NULL,
    [FaceStock]          NVARCHAR (4000) NULL,
    [Steel]              NVARCHAR (4000) NULL,
    [CornerRadius]       REAL            NULL,
    [SupplierID]         NVARCHAR (4000) NULL,
    [DateOrdered]        DATETIME        NULL,
    [ToolIn]             BIT             NULL,
    [Price]              REAL            NULL,
    [ExclusiveUse]       BIT             NULL,
    [Revolutions]        INT             NULL,
    [Notes]              NVARCHAR (4000) NULL,
    [ChromePlate]        BIT             NULL,
    [Quantity]           SMALLINT        NULL,
    [Maint_subtable]     INT             NULL,
    [Owner]              NVARCHAR (4000) NULL,
    [Is_Used_by_eStore]  BIT             NULL,
    [Location]           NVARCHAR (4000) NULL,
    [Drawing]            VARBINARY (1)   NULL,
    [Source_Appl]        NVARCHAR (4000) NULL,
    [File_Name]          NVARCHAR (4000) NULL,
    [DrawRptNotes]       NVARCHAR (4000) NULL,
    [PictDisplayFormat]  NVARCHAR (4000) NULL,
    [PictPrintFormat]    NVARCHAR (4000) NULL,
    [InternetQuery]      BIT             NULL,
    [SerialNumber]       NVARCHAR (4000) NULL,
    [Inactive]           BIT             NULL,
    [GearTeethRemainder] REAL            NULL,
    [EnteredBy]          NVARCHAR (4000) NULL,
    [ModifiedBy]         NVARCHAR (4000) NULL,
    [EnteredDate]        DATETIME        NULL,
    [ModifiedDate]       DATETIME        NULL,
    [EnteredTime]        TIME (7)        NULL,
    [ModifiedTime]       TIME (7)        NULL,
    [Drawing_Size]       REAL            NULL,
    [Pitch_Local]        NVARCHAR (4000) NULL,
    [DieCut_Local]       NVARCHAR (4000) NULL,
    [PK_UUID]            NVARCHAR (4000) NULL,
    [Flexo_HotS_Local]   NVARCHAR (4000) NULL,
    [UpdateTimeDateStamp]     DATETIME        NULL
);


GO
CREATE NONCLUSTERED INDEX [NCI_Tooling_Number]
    ON [dbo].[Tooling]([Number] ASC);

