apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: airflow-workload
spec:
  template:
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      taints:
        - key: karpenter.sh/nodepool
          effect: NoExecute
      requirements:
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["t3a.2xlarge"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["on-demand"]
  limits:
    cpu: "10"
    memory: 30Gi