apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: rules-engine-workload
spec:
  template:
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      taints:
        - key: karpenter.sh/nodepool
          effect: NoExecute
      requirements:
        # - key: node.kubernetes.io/instance-type
        #   operator: In
        #   values: ["m7a.2xlarge"]
        - key: "karpenter.k8s.aws/instance-category"
          operator: In
          values: ["m"]
        - key: "karpenter.k8s.aws/instance-generation"
          operator: Gt
          values: ["4"]
        - key: "karpenter.k8s.aws/instance-cpu"
          operator: In
          values: ["4","8"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["spot", "on-demand"]
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 2m
    budgets:
    - nodes: 100%
      reasons:
      - Empty
    - nodes: 90%
      reasons:
      - Drifted
      - Underutilized
  limits:
    cpu: "100"
    memory: 300Gi